-- NonDPR.vhd

-- Generated using ACDS version 24.1 115

library IEEE;
library PR_Test_Top_clock_in;
library data_mem;
library NonDPR_master_0;
library NonDPR_npu_system_28;
library out_mem;
library PR_Test_Top_reset_in;
library weight_mem;
library altera_mm_interconnect_1920;
library altera_reset_controller_1922;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity NonDPR is
	port (
		clk_clk     : in std_logic := '0'; --   clk.clk
		reset_reset : in std_logic := '0'  -- reset.reset
	);
end entity NonDPR;

architecture rtl of NonDPR is
	component PR_Test_Top_clock_in_cmp is
		port (
			in_clk  : in  std_logic := 'X'; -- clk
			out_clk : out std_logic         -- clk
		);
	end component PR_Test_Top_clock_in_cmp;

	component data_mem_cmp is
		port (
			clk         : in  std_logic                     := 'X';             -- clk
			address     : in  std_logic_vector(9 downto 0)  := (others => 'X'); -- address
			clken       : in  std_logic                     := 'X';             -- clken
			chipselect  : in  std_logic                     := 'X';             -- chipselect
			write       : in  std_logic                     := 'X';             -- write
			readdata    : out std_logic_vector(31 downto 0);                    -- readdata
			writedata   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			byteenable  : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			reset       : in  std_logic                     := 'X';             -- reset
			reset_req   : in  std_logic                     := 'X';             -- reset_req
			address2    : in  std_logic_vector(9 downto 0)  := (others => 'X'); -- address
			chipselect2 : in  std_logic                     := 'X';             -- chipselect
			clken2      : in  std_logic                     := 'X';             -- clken
			write2      : in  std_logic                     := 'X';             -- write
			readdata2   : out std_logic_vector(31 downto 0);                    -- readdata
			writedata2  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			byteenable2 : in  std_logic_vector(3 downto 0)  := (others => 'X')  -- byteenable
		);
	end component data_mem_cmp;

	component NonDPR_master_0_cmp is
		port (
			clk_clk              : in  std_logic                     := 'X';             -- clk
			clk_reset_reset      : in  std_logic                     := 'X';             -- reset
			master_reset_reset   : out std_logic;                                        -- reset
			master_address       : out std_logic_vector(31 downto 0);                    -- address
			master_readdata      : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			master_read          : out std_logic;                                        -- read
			master_write         : out std_logic;                                        -- write
			master_writedata     : out std_logic_vector(31 downto 0);                    -- writedata
			master_waitrequest   : in  std_logic                     := 'X';             -- waitrequest
			master_readdatavalid : in  std_logic                     := 'X';             -- readdatavalid
			master_byteenable    : out std_logic_vector(3 downto 0)                      -- byteenable
		);
	end component NonDPR_master_0_cmp;

	component NonDPR_npu_system_28_cmp is
		port (
			clk                 : in  std_logic                     := 'X';             -- clk
			reset_n             : in  std_logic                     := 'X';             -- reset_n
			avs_address         : in  std_logic_vector(4 downto 0)  := (others => 'X'); -- address
			avs_write           : in  std_logic                     := 'X';             -- write
			avs_writedata       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			avs_read            : in  std_logic                     := 'X';             -- read
			avs_readdata        : out std_logic_vector(31 downto 0);                    -- readdata
			avs_waitrequest     : out std_logic;                                        -- waitrequest
			avm_act_address     : out std_logic_vector(31 downto 0);                    -- address
			avm_act_read        : out std_logic;                                        -- read
			avm_act_readdata    : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			avm_act_waitreq     : in  std_logic                     := 'X';             -- waitrequest
			avm_weight_address  : out std_logic_vector(31 downto 0);                    -- address
			avm_weight_read     : out std_logic;                                        -- read
			avm_weight_readdata : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			avm_weight_waitreq  : in  std_logic                     := 'X';             -- waitrequest
			avm_out_address     : out std_logic_vector(31 downto 0);                    -- address
			avm_out_write       : out std_logic;                                        -- write
			avm_out_writedata   : out std_logic_vector(31 downto 0);                    -- writedata
			avm_out_waitreq     : in  std_logic                     := 'X'              -- waitrequest
		);
	end component NonDPR_npu_system_28_cmp;

	component out_mem_cmp is
		port (
			clk         : in  std_logic                     := 'X';             -- clk
			address     : in  std_logic_vector(9 downto 0)  := (others => 'X'); -- address
			clken       : in  std_logic                     := 'X';             -- clken
			chipselect  : in  std_logic                     := 'X';             -- chipselect
			write       : in  std_logic                     := 'X';             -- write
			readdata    : out std_logic_vector(31 downto 0);                    -- readdata
			writedata   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			byteenable  : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			reset       : in  std_logic                     := 'X';             -- reset
			reset_req   : in  std_logic                     := 'X';             -- reset_req
			address2    : in  std_logic_vector(9 downto 0)  := (others => 'X'); -- address
			chipselect2 : in  std_logic                     := 'X';             -- chipselect
			clken2      : in  std_logic                     := 'X';             -- clken
			write2      : in  std_logic                     := 'X';             -- write
			readdata2   : out std_logic_vector(31 downto 0);                    -- readdata
			writedata2  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			byteenable2 : in  std_logic_vector(3 downto 0)  := (others => 'X')  -- byteenable
		);
	end component out_mem_cmp;

	component PR_Test_Top_reset_in_cmp is
		port (
			clk       : in  std_logic := 'X'; -- clk
			in_reset  : in  std_logic := 'X'; -- reset
			out_reset : out std_logic         -- reset
		);
	end component PR_Test_Top_reset_in_cmp;

	component weight_mem_cmp is
		port (
			clk         : in  std_logic                     := 'X';             -- clk
			address     : in  std_logic_vector(9 downto 0)  := (others => 'X'); -- address
			clken       : in  std_logic                     := 'X';             -- clken
			chipselect  : in  std_logic                     := 'X';             -- chipselect
			write       : in  std_logic                     := 'X';             -- write
			readdata    : out std_logic_vector(31 downto 0);                    -- readdata
			writedata   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			byteenable  : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			reset       : in  std_logic                     := 'X';             -- reset
			reset_req   : in  std_logic                     := 'X';             -- reset_req
			address2    : in  std_logic_vector(9 downto 0)  := (others => 'X'); -- address
			chipselect2 : in  std_logic                     := 'X';             -- chipselect
			clken2      : in  std_logic                     := 'X';             -- clken
			write2      : in  std_logic                     := 'X';             -- write
			readdata2   : out std_logic_vector(31 downto 0);                    -- readdata
			writedata2  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			byteenable2 : in  std_logic_vector(3 downto 0)  := (others => 'X')  -- byteenable
		);
	end component weight_mem_cmp;

	component NonDPR_altera_mm_interconnect_1920_y3bfzfy_cmp is
		port (
			npu_system_0_act_address                       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- address
			npu_system_0_act_waitrequest                   : out std_logic;                                        -- waitrequest
			npu_system_0_act_read                          : in  std_logic                     := 'X';             -- read
			npu_system_0_act_readdata                      : out std_logic_vector(31 downto 0);                    -- readdata
			data_mem_s2_address                            : out std_logic_vector(9 downto 0);                     -- address
			data_mem_s2_write                              : out std_logic;                                        -- write
			data_mem_s2_readdata                           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			data_mem_s2_writedata                          : out std_logic_vector(31 downto 0);                    -- writedata
			data_mem_s2_byteenable                         : out std_logic_vector(3 downto 0);                     -- byteenable
			data_mem_s2_chipselect                         : out std_logic;                                        -- chipselect
			data_mem_s2_clken                              : out std_logic;                                        -- clken
			npu_system_0_reset_reset_bridge_in_reset_reset : in  std_logic                     := 'X';             -- reset
			clock_in_out_clk_clk                           : in  std_logic                     := 'X'              -- clk
		);
	end component NonDPR_altera_mm_interconnect_1920_y3bfzfy_cmp;

	component NonDPR_altera_mm_interconnect_1920_efcorai_cmp is
		port (
			master_0_master_address                        : in  std_logic_vector(31 downto 0) := (others => 'X'); -- address
			master_0_master_waitrequest                    : out std_logic;                                        -- waitrequest
			master_0_master_byteenable                     : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			master_0_master_read                           : in  std_logic                     := 'X';             -- read
			master_0_master_readdata                       : out std_logic_vector(31 downto 0);                    -- readdata
			master_0_master_readdatavalid                  : out std_logic;                                        -- readdatavalid
			master_0_master_write                          : in  std_logic                     := 'X';             -- write
			master_0_master_writedata                      : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			npu_system_0_avalon_slave_0_address            : out std_logic_vector(4 downto 0);                     -- address
			npu_system_0_avalon_slave_0_write              : out std_logic;                                        -- write
			npu_system_0_avalon_slave_0_read               : out std_logic;                                        -- read
			npu_system_0_avalon_slave_0_readdata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			npu_system_0_avalon_slave_0_writedata          : out std_logic_vector(31 downto 0);                    -- writedata
			npu_system_0_avalon_slave_0_waitrequest        : in  std_logic                     := 'X';             -- waitrequest
			data_mem_s1_address                            : out std_logic_vector(9 downto 0);                     -- address
			data_mem_s1_write                              : out std_logic;                                        -- write
			data_mem_s1_readdata                           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			data_mem_s1_writedata                          : out std_logic_vector(31 downto 0);                    -- writedata
			data_mem_s1_byteenable                         : out std_logic_vector(3 downto 0);                     -- byteenable
			data_mem_s1_chipselect                         : out std_logic;                                        -- chipselect
			data_mem_s1_clken                              : out std_logic;                                        -- clken
			weight_mem_s1_address                          : out std_logic_vector(9 downto 0);                     -- address
			weight_mem_s1_write                            : out std_logic;                                        -- write
			weight_mem_s1_readdata                         : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			weight_mem_s1_writedata                        : out std_logic_vector(31 downto 0);                    -- writedata
			weight_mem_s1_byteenable                       : out std_logic_vector(3 downto 0);                     -- byteenable
			weight_mem_s1_chipselect                       : out std_logic;                                        -- chipselect
			weight_mem_s1_clken                            : out std_logic;                                        -- clken
			out_mem_s1_address                             : out std_logic_vector(9 downto 0);                     -- address
			out_mem_s1_write                               : out std_logic;                                        -- write
			out_mem_s1_readdata                            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			out_mem_s1_writedata                           : out std_logic_vector(31 downto 0);                    -- writedata
			out_mem_s1_byteenable                          : out std_logic_vector(3 downto 0);                     -- byteenable
			out_mem_s1_chipselect                          : out std_logic;                                        -- chipselect
			out_mem_s1_clken                               : out std_logic;                                        -- clken
			npu_system_0_reset_reset_bridge_in_reset_reset : in  std_logic                     := 'X';             -- reset
			clock_in_out_clk_clk                           : in  std_logic                     := 'X'              -- clk
		);
	end component NonDPR_altera_mm_interconnect_1920_efcorai_cmp;

	component NonDPR_altera_mm_interconnect_1920_ak3ihbq_cmp is
		port (
			npu_system_0_out_address                       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- address
			npu_system_0_out_waitrequest                   : out std_logic;                                        -- waitrequest
			npu_system_0_out_write                         : in  std_logic                     := 'X';             -- write
			npu_system_0_out_writedata                     : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			out_mem_s2_address                             : out std_logic_vector(9 downto 0);                     -- address
			out_mem_s2_write                               : out std_logic;                                        -- write
			out_mem_s2_readdata                            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			out_mem_s2_writedata                           : out std_logic_vector(31 downto 0);                    -- writedata
			out_mem_s2_byteenable                          : out std_logic_vector(3 downto 0);                     -- byteenable
			out_mem_s2_chipselect                          : out std_logic;                                        -- chipselect
			out_mem_s2_clken                               : out std_logic;                                        -- clken
			npu_system_0_reset_reset_bridge_in_reset_reset : in  std_logic                     := 'X';             -- reset
			clock_in_out_clk_clk                           : in  std_logic                     := 'X'              -- clk
		);
	end component NonDPR_altera_mm_interconnect_1920_ak3ihbq_cmp;

	component NonDPR_altera_mm_interconnect_1920_iwcms7y_cmp is
		port (
			npu_system_0_weight_address                    : in  std_logic_vector(31 downto 0) := (others => 'X'); -- address
			npu_system_0_weight_waitrequest                : out std_logic;                                        -- waitrequest
			npu_system_0_weight_read                       : in  std_logic                     := 'X';             -- read
			npu_system_0_weight_readdata                   : out std_logic_vector(31 downto 0);                    -- readdata
			weight_mem_s2_address                          : out std_logic_vector(9 downto 0);                     -- address
			weight_mem_s2_write                            : out std_logic;                                        -- write
			weight_mem_s2_readdata                         : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			weight_mem_s2_writedata                        : out std_logic_vector(31 downto 0);                    -- writedata
			weight_mem_s2_byteenable                       : out std_logic_vector(3 downto 0);                     -- byteenable
			weight_mem_s2_chipselect                       : out std_logic;                                        -- chipselect
			weight_mem_s2_clken                            : out std_logic;                                        -- clken
			npu_system_0_reset_reset_bridge_in_reset_reset : in  std_logic                     := 'X';             -- reset
			clock_in_out_clk_clk                           : in  std_logic                     := 'X'              -- clk
		);
	end component NonDPR_altera_mm_interconnect_1920_iwcms7y_cmp;

	component altera_reset_controller_cmp is
		generic (
			NUM_RESET_INPUTS          : integer := 6;
			OUTPUT_RESET_SYNC_EDGES   : string  := "deassert";
			SYNC_DEPTH                : integer := 2;
			RESET_REQUEST_PRESENT     : integer := 0;
			RESET_REQ_WAIT_TIME       : integer := 1;
			MIN_RST_ASSERTION_TIME    : integer := 3;
			RESET_REQ_EARLY_DSRT_TIME : integer := 1;
			USE_RESET_REQUEST_IN0     : integer := 0;
			USE_RESET_REQUEST_IN1     : integer := 0;
			USE_RESET_REQUEST_IN2     : integer := 0;
			USE_RESET_REQUEST_IN3     : integer := 0;
			USE_RESET_REQUEST_IN4     : integer := 0;
			USE_RESET_REQUEST_IN5     : integer := 0;
			USE_RESET_REQUEST_IN6     : integer := 0;
			USE_RESET_REQUEST_IN7     : integer := 0;
			USE_RESET_REQUEST_IN8     : integer := 0;
			USE_RESET_REQUEST_IN9     : integer := 0;
			USE_RESET_REQUEST_IN10    : integer := 0;
			USE_RESET_REQUEST_IN11    : integer := 0;
			USE_RESET_REQUEST_IN12    : integer := 0;
			USE_RESET_REQUEST_IN13    : integer := 0;
			USE_RESET_REQUEST_IN14    : integer := 0;
			USE_RESET_REQUEST_IN15    : integer := 0;
			ADAPT_RESET_REQUEST       : integer := 0
		);
		port (
			reset_in0      : in  std_logic := 'X'; -- reset
			clk            : in  std_logic := 'X'; -- clk
			reset_out      : out std_logic;        -- reset
			reset_req      : out std_logic;        -- reset_req
			reset_req_in0  : in  std_logic := 'X'; -- reset_req
			reset_in1      : in  std_logic := 'X'; -- reset
			reset_req_in1  : in  std_logic := 'X'; -- reset_req
			reset_in2      : in  std_logic := 'X'; -- reset
			reset_req_in2  : in  std_logic := 'X'; -- reset_req
			reset_in3      : in  std_logic := 'X'; -- reset
			reset_req_in3  : in  std_logic := 'X'; -- reset_req
			reset_in4      : in  std_logic := 'X'; -- reset
			reset_req_in4  : in  std_logic := 'X'; -- reset_req
			reset_in5      : in  std_logic := 'X'; -- reset
			reset_req_in5  : in  std_logic := 'X'; -- reset_req
			reset_in6      : in  std_logic := 'X'; -- reset
			reset_req_in6  : in  std_logic := 'X'; -- reset_req
			reset_in7      : in  std_logic := 'X'; -- reset
			reset_req_in7  : in  std_logic := 'X'; -- reset_req
			reset_in8      : in  std_logic := 'X'; -- reset
			reset_req_in8  : in  std_logic := 'X'; -- reset_req
			reset_in9      : in  std_logic := 'X'; -- reset
			reset_req_in9  : in  std_logic := 'X'; -- reset_req
			reset_in10     : in  std_logic := 'X'; -- reset
			reset_req_in10 : in  std_logic := 'X'; -- reset_req
			reset_in11     : in  std_logic := 'X'; -- reset
			reset_req_in11 : in  std_logic := 'X'; -- reset_req
			reset_in12     : in  std_logic := 'X'; -- reset
			reset_req_in12 : in  std_logic := 'X'; -- reset_req
			reset_in13     : in  std_logic := 'X'; -- reset
			reset_req_in13 : in  std_logic := 'X'; -- reset_req
			reset_in14     : in  std_logic := 'X'; -- reset
			reset_req_in14 : in  std_logic := 'X'; -- reset_req
			reset_in15     : in  std_logic := 'X'; -- reset
			reset_req_in15 : in  std_logic := 'X'  -- reset_req
		);
	end component altera_reset_controller_cmp;

	signal clock_in_out_clk_clk                                      : std_logic;                     -- clock_in:out_clk -> [data_mem:clk, master_0:clk_clk, mm_interconnect_0:clock_in_out_clk_clk, mm_interconnect_1:clock_in_out_clk_clk, mm_interconnect_2:clock_in_out_clk_clk, mm_interconnect_3:clock_in_out_clk_clk, npu_system_0:clk, out_mem:clk, reset_in:clk, rst_controller:clk, weight_mem:clk]
	signal reset_in_out_reset_reset                                  : std_logic;                     -- reset_in:out_reset -> [master_0:clk_reset_reset, rst_controller:reset_in0]
	signal npu_system_0_act_readdata                                 : std_logic_vector(31 downto 0); -- mm_interconnect_0:npu_system_0_act_readdata -> npu_system_0:avm_act_readdata
	signal npu_system_0_act_waitrequest                              : std_logic;                     -- mm_interconnect_0:npu_system_0_act_waitrequest -> npu_system_0:avm_act_waitreq
	signal npu_system_0_act_address                                  : std_logic_vector(31 downto 0); -- npu_system_0:avm_act_address -> mm_interconnect_0:npu_system_0_act_address
	signal npu_system_0_act_read                                     : std_logic;                     -- npu_system_0:avm_act_read -> mm_interconnect_0:npu_system_0_act_read
	signal mm_interconnect_0_data_mem_s2_chipselect                  : std_logic;                     -- mm_interconnect_0:data_mem_s2_chipselect -> data_mem:chipselect2
	signal mm_interconnect_0_data_mem_s2_readdata                    : std_logic_vector(31 downto 0); -- data_mem:readdata2 -> mm_interconnect_0:data_mem_s2_readdata
	signal mm_interconnect_0_data_mem_s2_address                     : std_logic_vector(9 downto 0);  -- mm_interconnect_0:data_mem_s2_address -> data_mem:address2
	signal mm_interconnect_0_data_mem_s2_byteenable                  : std_logic_vector(3 downto 0);  -- mm_interconnect_0:data_mem_s2_byteenable -> data_mem:byteenable2
	signal mm_interconnect_0_data_mem_s2_write                       : std_logic;                     -- mm_interconnect_0:data_mem_s2_write -> data_mem:write2
	signal mm_interconnect_0_data_mem_s2_writedata                   : std_logic_vector(31 downto 0); -- mm_interconnect_0:data_mem_s2_writedata -> data_mem:writedata2
	signal mm_interconnect_0_data_mem_s2_clken                       : std_logic;                     -- mm_interconnect_0:data_mem_s2_clken -> data_mem:clken2
	signal master_0_master_readdata                                  : std_logic_vector(31 downto 0); -- mm_interconnect_1:master_0_master_readdata -> master_0:master_readdata
	signal master_0_master_waitrequest                               : std_logic;                     -- mm_interconnect_1:master_0_master_waitrequest -> master_0:master_waitrequest
	signal master_0_master_address                                   : std_logic_vector(31 downto 0); -- master_0:master_address -> mm_interconnect_1:master_0_master_address
	signal master_0_master_read                                      : std_logic;                     -- master_0:master_read -> mm_interconnect_1:master_0_master_read
	signal master_0_master_byteenable                                : std_logic_vector(3 downto 0);  -- master_0:master_byteenable -> mm_interconnect_1:master_0_master_byteenable
	signal master_0_master_readdatavalid                             : std_logic;                     -- mm_interconnect_1:master_0_master_readdatavalid -> master_0:master_readdatavalid
	signal master_0_master_write                                     : std_logic;                     -- master_0:master_write -> mm_interconnect_1:master_0_master_write
	signal master_0_master_writedata                                 : std_logic_vector(31 downto 0); -- master_0:master_writedata -> mm_interconnect_1:master_0_master_writedata
	signal mm_interconnect_1_npu_system_0_avalon_slave_0_readdata    : std_logic_vector(31 downto 0); -- npu_system_0:avs_readdata -> mm_interconnect_1:npu_system_0_avalon_slave_0_readdata
	signal mm_interconnect_1_npu_system_0_avalon_slave_0_waitrequest : std_logic;                     -- npu_system_0:avs_waitrequest -> mm_interconnect_1:npu_system_0_avalon_slave_0_waitrequest
	signal mm_interconnect_1_npu_system_0_avalon_slave_0_address     : std_logic_vector(4 downto 0);  -- mm_interconnect_1:npu_system_0_avalon_slave_0_address -> npu_system_0:avs_address
	signal mm_interconnect_1_npu_system_0_avalon_slave_0_read        : std_logic;                     -- mm_interconnect_1:npu_system_0_avalon_slave_0_read -> npu_system_0:avs_read
	signal mm_interconnect_1_npu_system_0_avalon_slave_0_write       : std_logic;                     -- mm_interconnect_1:npu_system_0_avalon_slave_0_write -> npu_system_0:avs_write
	signal mm_interconnect_1_npu_system_0_avalon_slave_0_writedata   : std_logic_vector(31 downto 0); -- mm_interconnect_1:npu_system_0_avalon_slave_0_writedata -> npu_system_0:avs_writedata
	signal mm_interconnect_1_data_mem_s1_chipselect                  : std_logic;                     -- mm_interconnect_1:data_mem_s1_chipselect -> data_mem:chipselect
	signal mm_interconnect_1_data_mem_s1_readdata                    : std_logic_vector(31 downto 0); -- data_mem:readdata -> mm_interconnect_1:data_mem_s1_readdata
	signal mm_interconnect_1_data_mem_s1_address                     : std_logic_vector(9 downto 0);  -- mm_interconnect_1:data_mem_s1_address -> data_mem:address
	signal mm_interconnect_1_data_mem_s1_byteenable                  : std_logic_vector(3 downto 0);  -- mm_interconnect_1:data_mem_s1_byteenable -> data_mem:byteenable
	signal mm_interconnect_1_data_mem_s1_write                       : std_logic;                     -- mm_interconnect_1:data_mem_s1_write -> data_mem:write
	signal mm_interconnect_1_data_mem_s1_writedata                   : std_logic_vector(31 downto 0); -- mm_interconnect_1:data_mem_s1_writedata -> data_mem:writedata
	signal mm_interconnect_1_data_mem_s1_clken                       : std_logic;                     -- mm_interconnect_1:data_mem_s1_clken -> data_mem:clken
	signal mm_interconnect_1_weight_mem_s1_chipselect                : std_logic;                     -- mm_interconnect_1:weight_mem_s1_chipselect -> weight_mem:chipselect
	signal mm_interconnect_1_weight_mem_s1_readdata                  : std_logic_vector(31 downto 0); -- weight_mem:readdata -> mm_interconnect_1:weight_mem_s1_readdata
	signal mm_interconnect_1_weight_mem_s1_address                   : std_logic_vector(9 downto 0);  -- mm_interconnect_1:weight_mem_s1_address -> weight_mem:address
	signal mm_interconnect_1_weight_mem_s1_byteenable                : std_logic_vector(3 downto 0);  -- mm_interconnect_1:weight_mem_s1_byteenable -> weight_mem:byteenable
	signal mm_interconnect_1_weight_mem_s1_write                     : std_logic;                     -- mm_interconnect_1:weight_mem_s1_write -> weight_mem:write
	signal mm_interconnect_1_weight_mem_s1_writedata                 : std_logic_vector(31 downto 0); -- mm_interconnect_1:weight_mem_s1_writedata -> weight_mem:writedata
	signal mm_interconnect_1_weight_mem_s1_clken                     : std_logic;                     -- mm_interconnect_1:weight_mem_s1_clken -> weight_mem:clken
	signal mm_interconnect_1_out_mem_s1_chipselect                   : std_logic;                     -- mm_interconnect_1:out_mem_s1_chipselect -> out_mem:chipselect
	signal mm_interconnect_1_out_mem_s1_readdata                     : std_logic_vector(31 downto 0); -- out_mem:readdata -> mm_interconnect_1:out_mem_s1_readdata
	signal mm_interconnect_1_out_mem_s1_address                      : std_logic_vector(9 downto 0);  -- mm_interconnect_1:out_mem_s1_address -> out_mem:address
	signal mm_interconnect_1_out_mem_s1_byteenable                   : std_logic_vector(3 downto 0);  -- mm_interconnect_1:out_mem_s1_byteenable -> out_mem:byteenable
	signal mm_interconnect_1_out_mem_s1_write                        : std_logic;                     -- mm_interconnect_1:out_mem_s1_write -> out_mem:write
	signal mm_interconnect_1_out_mem_s1_writedata                    : std_logic_vector(31 downto 0); -- mm_interconnect_1:out_mem_s1_writedata -> out_mem:writedata
	signal mm_interconnect_1_out_mem_s1_clken                        : std_logic;                     -- mm_interconnect_1:out_mem_s1_clken -> out_mem:clken
	signal npu_system_0_out_waitrequest                              : std_logic;                     -- mm_interconnect_2:npu_system_0_out_waitrequest -> npu_system_0:avm_out_waitreq
	signal npu_system_0_out_address                                  : std_logic_vector(31 downto 0); -- npu_system_0:avm_out_address -> mm_interconnect_2:npu_system_0_out_address
	signal npu_system_0_out_write                                    : std_logic;                     -- npu_system_0:avm_out_write -> mm_interconnect_2:npu_system_0_out_write
	signal npu_system_0_out_writedata                                : std_logic_vector(31 downto 0); -- npu_system_0:avm_out_writedata -> mm_interconnect_2:npu_system_0_out_writedata
	signal mm_interconnect_2_out_mem_s2_chipselect                   : std_logic;                     -- mm_interconnect_2:out_mem_s2_chipselect -> out_mem:chipselect2
	signal mm_interconnect_2_out_mem_s2_readdata                     : std_logic_vector(31 downto 0); -- out_mem:readdata2 -> mm_interconnect_2:out_mem_s2_readdata
	signal mm_interconnect_2_out_mem_s2_address                      : std_logic_vector(9 downto 0);  -- mm_interconnect_2:out_mem_s2_address -> out_mem:address2
	signal mm_interconnect_2_out_mem_s2_byteenable                   : std_logic_vector(3 downto 0);  -- mm_interconnect_2:out_mem_s2_byteenable -> out_mem:byteenable2
	signal mm_interconnect_2_out_mem_s2_write                        : std_logic;                     -- mm_interconnect_2:out_mem_s2_write -> out_mem:write2
	signal mm_interconnect_2_out_mem_s2_writedata                    : std_logic_vector(31 downto 0); -- mm_interconnect_2:out_mem_s2_writedata -> out_mem:writedata2
	signal mm_interconnect_2_out_mem_s2_clken                        : std_logic;                     -- mm_interconnect_2:out_mem_s2_clken -> out_mem:clken2
	signal npu_system_0_weight_readdata                              : std_logic_vector(31 downto 0); -- mm_interconnect_3:npu_system_0_weight_readdata -> npu_system_0:avm_weight_readdata
	signal npu_system_0_weight_waitrequest                           : std_logic;                     -- mm_interconnect_3:npu_system_0_weight_waitrequest -> npu_system_0:avm_weight_waitreq
	signal npu_system_0_weight_address                               : std_logic_vector(31 downto 0); -- npu_system_0:avm_weight_address -> mm_interconnect_3:npu_system_0_weight_address
	signal npu_system_0_weight_read                                  : std_logic;                     -- npu_system_0:avm_weight_read -> mm_interconnect_3:npu_system_0_weight_read
	signal mm_interconnect_3_weight_mem_s2_chipselect                : std_logic;                     -- mm_interconnect_3:weight_mem_s2_chipselect -> weight_mem:chipselect2
	signal mm_interconnect_3_weight_mem_s2_readdata                  : std_logic_vector(31 downto 0); -- weight_mem:readdata2 -> mm_interconnect_3:weight_mem_s2_readdata
	signal mm_interconnect_3_weight_mem_s2_address                   : std_logic_vector(9 downto 0);  -- mm_interconnect_3:weight_mem_s2_address -> weight_mem:address2
	signal mm_interconnect_3_weight_mem_s2_byteenable                : std_logic_vector(3 downto 0);  -- mm_interconnect_3:weight_mem_s2_byteenable -> weight_mem:byteenable2
	signal mm_interconnect_3_weight_mem_s2_write                     : std_logic;                     -- mm_interconnect_3:weight_mem_s2_write -> weight_mem:write2
	signal mm_interconnect_3_weight_mem_s2_writedata                 : std_logic_vector(31 downto 0); -- mm_interconnect_3:weight_mem_s2_writedata -> weight_mem:writedata2
	signal mm_interconnect_3_weight_mem_s2_clken                     : std_logic;                     -- mm_interconnect_3:weight_mem_s2_clken -> weight_mem:clken2
	signal rst_controller_reset_out_reset                            : std_logic;                     -- rst_controller:reset_out -> [data_mem:reset, mm_interconnect_0:npu_system_0_reset_reset_bridge_in_reset_reset, mm_interconnect_1:npu_system_0_reset_reset_bridge_in_reset_reset, mm_interconnect_2:npu_system_0_reset_reset_bridge_in_reset_reset, mm_interconnect_3:npu_system_0_reset_reset_bridge_in_reset_reset, out_mem:reset, rst_controller_reset_out_reset:in, rst_translator:in_reset, weight_mem:reset]
	signal rst_controller_reset_out_reset_req                        : std_logic;                     -- rst_controller:reset_req -> [data_mem:reset_req, out_mem:reset_req, rst_translator:reset_req_in, weight_mem:reset_req]
	signal rst_controller_reset_out_reset_ports_inv                  : std_logic;                     -- rst_controller_reset_out_reset:inv -> npu_system_0:reset_n

	for clock_in : PR_Test_Top_clock_in_cmp
		use entity PR_Test_Top_clock_in.PR_Test_Top_clock_in;
	for data_mem : data_mem_cmp
		use entity data_mem.data_mem;
	for master_0 : NonDPR_master_0_cmp
		use entity NonDPR_master_0.NonDPR_master_0;
	for npu_system_0 : NonDPR_npu_system_28_cmp
		use entity NonDPR_npu_system_28.NonDPR_npu_system_28;
	for out_mem : out_mem_cmp
		use entity out_mem.out_mem;
	for reset_in : PR_Test_Top_reset_in_cmp
		use entity PR_Test_Top_reset_in.PR_Test_Top_reset_in;
	for weight_mem : weight_mem_cmp
		use entity weight_mem.weight_mem;
	for mm_interconnect_0 : NonDPR_altera_mm_interconnect_1920_y3bfzfy_cmp
		use entity altera_mm_interconnect_1920.NonDPR_altera_mm_interconnect_1920_y3bfzfy;
	for mm_interconnect_1 : NonDPR_altera_mm_interconnect_1920_efcorai_cmp
		use entity altera_mm_interconnect_1920.NonDPR_altera_mm_interconnect_1920_efcorai;
	for mm_interconnect_2 : NonDPR_altera_mm_interconnect_1920_ak3ihbq_cmp
		use entity altera_mm_interconnect_1920.NonDPR_altera_mm_interconnect_1920_ak3ihbq;
	for mm_interconnect_3 : NonDPR_altera_mm_interconnect_1920_iwcms7y_cmp
		use entity altera_mm_interconnect_1920.NonDPR_altera_mm_interconnect_1920_iwcms7y;
	for rst_controller : altera_reset_controller_cmp
		use entity altera_reset_controller_1922.altera_reset_controller;
begin

	clock_in : component PR_Test_Top_clock_in_cmp
		port map (
			in_clk  => clk_clk,              --  in_clk.clk
			out_clk => clock_in_out_clk_clk  -- out_clk.clk
		);

	data_mem : component data_mem_cmp
		port map (
			clk         => clock_in_out_clk_clk,                     --   clk1.clk
			address     => mm_interconnect_1_data_mem_s1_address,    --     s1.address
			clken       => mm_interconnect_1_data_mem_s1_clken,      --       .clken
			chipselect  => mm_interconnect_1_data_mem_s1_chipselect, --       .chipselect
			write       => mm_interconnect_1_data_mem_s1_write,      --       .write
			readdata    => mm_interconnect_1_data_mem_s1_readdata,   --       .readdata
			writedata   => mm_interconnect_1_data_mem_s1_writedata,  --       .writedata
			byteenable  => mm_interconnect_1_data_mem_s1_byteenable, --       .byteenable
			reset       => rst_controller_reset_out_reset,           -- reset1.reset
			reset_req   => rst_controller_reset_out_reset_req,       --       .reset_req
			address2    => mm_interconnect_0_data_mem_s2_address,    --     s2.address
			chipselect2 => mm_interconnect_0_data_mem_s2_chipselect, --       .chipselect
			clken2      => mm_interconnect_0_data_mem_s2_clken,      --       .clken
			write2      => mm_interconnect_0_data_mem_s2_write,      --       .write
			readdata2   => mm_interconnect_0_data_mem_s2_readdata,   --       .readdata
			writedata2  => mm_interconnect_0_data_mem_s2_writedata,  --       .writedata
			byteenable2 => mm_interconnect_0_data_mem_s2_byteenable  --       .byteenable
		);

	master_0 : component NonDPR_master_0_cmp
		port map (
			clk_clk              => clock_in_out_clk_clk,          --          clk.clk
			clk_reset_reset      => reset_in_out_reset_reset,      --    clk_reset.reset
			master_reset_reset   => open,                          -- master_reset.reset
			master_address       => master_0_master_address,       --       master.address
			master_readdata      => master_0_master_readdata,      --             .readdata
			master_read          => master_0_master_read,          --             .read
			master_write         => master_0_master_write,         --             .write
			master_writedata     => master_0_master_writedata,     --             .writedata
			master_waitrequest   => master_0_master_waitrequest,   --             .waitrequest
			master_readdatavalid => master_0_master_readdatavalid, --             .readdatavalid
			master_byteenable    => master_0_master_byteenable     --             .byteenable
		);

	npu_system_0 : component NonDPR_npu_system_28_cmp
		port map (
			clk                 => clock_in_out_clk_clk,                                      --          clock.clk
			reset_n             => rst_controller_reset_out_reset_ports_inv,                  --          reset.reset_n
			avs_address         => mm_interconnect_1_npu_system_0_avalon_slave_0_address,     -- avalon_slave_0.address
			avs_write           => mm_interconnect_1_npu_system_0_avalon_slave_0_write,       --               .write
			avs_writedata       => mm_interconnect_1_npu_system_0_avalon_slave_0_writedata,   --               .writedata
			avs_read            => mm_interconnect_1_npu_system_0_avalon_slave_0_read,        --               .read
			avs_readdata        => mm_interconnect_1_npu_system_0_avalon_slave_0_readdata,    --               .readdata
			avs_waitrequest     => mm_interconnect_1_npu_system_0_avalon_slave_0_waitrequest, --               .waitrequest
			avm_act_address     => npu_system_0_act_address,                                  --            act.address
			avm_act_read        => npu_system_0_act_read,                                     --               .read
			avm_act_readdata    => npu_system_0_act_readdata,                                 --               .readdata
			avm_act_waitreq     => npu_system_0_act_waitrequest,                              --               .waitrequest
			avm_weight_address  => npu_system_0_weight_address,                               --         weight.address
			avm_weight_read     => npu_system_0_weight_read,                                  --               .read
			avm_weight_readdata => npu_system_0_weight_readdata,                              --               .readdata
			avm_weight_waitreq  => npu_system_0_weight_waitrequest,                           --               .waitrequest
			avm_out_address     => npu_system_0_out_address,                                  --            out.address
			avm_out_write       => npu_system_0_out_write,                                    --               .write
			avm_out_writedata   => npu_system_0_out_writedata,                                --               .writedata
			avm_out_waitreq     => npu_system_0_out_waitrequest                               --               .waitrequest
		);

	out_mem : component out_mem_cmp
		port map (
			clk         => clock_in_out_clk_clk,                    --   clk1.clk
			address     => mm_interconnect_1_out_mem_s1_address,    --     s1.address
			clken       => mm_interconnect_1_out_mem_s1_clken,      --       .clken
			chipselect  => mm_interconnect_1_out_mem_s1_chipselect, --       .chipselect
			write       => mm_interconnect_1_out_mem_s1_write,      --       .write
			readdata    => mm_interconnect_1_out_mem_s1_readdata,   --       .readdata
			writedata   => mm_interconnect_1_out_mem_s1_writedata,  --       .writedata
			byteenable  => mm_interconnect_1_out_mem_s1_byteenable, --       .byteenable
			reset       => rst_controller_reset_out_reset,          -- reset1.reset
			reset_req   => rst_controller_reset_out_reset_req,      --       .reset_req
			address2    => mm_interconnect_2_out_mem_s2_address,    --     s2.address
			chipselect2 => mm_interconnect_2_out_mem_s2_chipselect, --       .chipselect
			clken2      => mm_interconnect_2_out_mem_s2_clken,      --       .clken
			write2      => mm_interconnect_2_out_mem_s2_write,      --       .write
			readdata2   => mm_interconnect_2_out_mem_s2_readdata,   --       .readdata
			writedata2  => mm_interconnect_2_out_mem_s2_writedata,  --       .writedata
			byteenable2 => mm_interconnect_2_out_mem_s2_byteenable  --       .byteenable
		);

	reset_in : component PR_Test_Top_reset_in_cmp
		port map (
			clk       => clock_in_out_clk_clk,     --       clk.clk
			in_reset  => reset_reset,              --  in_reset.reset
			out_reset => reset_in_out_reset_reset  -- out_reset.reset
		);

	weight_mem : component weight_mem_cmp
		port map (
			clk         => clock_in_out_clk_clk,                       --   clk1.clk
			address     => mm_interconnect_1_weight_mem_s1_address,    --     s1.address
			clken       => mm_interconnect_1_weight_mem_s1_clken,      --       .clken
			chipselect  => mm_interconnect_1_weight_mem_s1_chipselect, --       .chipselect
			write       => mm_interconnect_1_weight_mem_s1_write,      --       .write
			readdata    => mm_interconnect_1_weight_mem_s1_readdata,   --       .readdata
			writedata   => mm_interconnect_1_weight_mem_s1_writedata,  --       .writedata
			byteenable  => mm_interconnect_1_weight_mem_s1_byteenable, --       .byteenable
			reset       => rst_controller_reset_out_reset,             -- reset1.reset
			reset_req   => rst_controller_reset_out_reset_req,         --       .reset_req
			address2    => mm_interconnect_3_weight_mem_s2_address,    --     s2.address
			chipselect2 => mm_interconnect_3_weight_mem_s2_chipselect, --       .chipselect
			clken2      => mm_interconnect_3_weight_mem_s2_clken,      --       .clken
			write2      => mm_interconnect_3_weight_mem_s2_write,      --       .write
			readdata2   => mm_interconnect_3_weight_mem_s2_readdata,   --       .readdata
			writedata2  => mm_interconnect_3_weight_mem_s2_writedata,  --       .writedata
			byteenable2 => mm_interconnect_3_weight_mem_s2_byteenable  --       .byteenable
		);

	mm_interconnect_0 : component NonDPR_altera_mm_interconnect_1920_y3bfzfy_cmp
		port map (
			npu_system_0_act_address                       => npu_system_0_act_address,                 --                         npu_system_0_act.address
			npu_system_0_act_waitrequest                   => npu_system_0_act_waitrequest,             --                                         .waitrequest
			npu_system_0_act_read                          => npu_system_0_act_read,                    --                                         .read
			npu_system_0_act_readdata                      => npu_system_0_act_readdata,                --                                         .readdata
			data_mem_s2_address                            => mm_interconnect_0_data_mem_s2_address,    --                              data_mem_s2.address
			data_mem_s2_write                              => mm_interconnect_0_data_mem_s2_write,      --                                         .write
			data_mem_s2_readdata                           => mm_interconnect_0_data_mem_s2_readdata,   --                                         .readdata
			data_mem_s2_writedata                          => mm_interconnect_0_data_mem_s2_writedata,  --                                         .writedata
			data_mem_s2_byteenable                         => mm_interconnect_0_data_mem_s2_byteenable, --                                         .byteenable
			data_mem_s2_chipselect                         => mm_interconnect_0_data_mem_s2_chipselect, --                                         .chipselect
			data_mem_s2_clken                              => mm_interconnect_0_data_mem_s2_clken,      --                                         .clken
			npu_system_0_reset_reset_bridge_in_reset_reset => rst_controller_reset_out_reset,           -- npu_system_0_reset_reset_bridge_in_reset.reset
			clock_in_out_clk_clk                           => clock_in_out_clk_clk                      --                         clock_in_out_clk.clk
		);

	mm_interconnect_1 : component NonDPR_altera_mm_interconnect_1920_efcorai_cmp
		port map (
			master_0_master_address                        => master_0_master_address,                                   --                          master_0_master.address
			master_0_master_waitrequest                    => master_0_master_waitrequest,                               --                                         .waitrequest
			master_0_master_byteenable                     => master_0_master_byteenable,                                --                                         .byteenable
			master_0_master_read                           => master_0_master_read,                                      --                                         .read
			master_0_master_readdata                       => master_0_master_readdata,                                  --                                         .readdata
			master_0_master_readdatavalid                  => master_0_master_readdatavalid,                             --                                         .readdatavalid
			master_0_master_write                          => master_0_master_write,                                     --                                         .write
			master_0_master_writedata                      => master_0_master_writedata,                                 --                                         .writedata
			npu_system_0_avalon_slave_0_address            => mm_interconnect_1_npu_system_0_avalon_slave_0_address,     --              npu_system_0_avalon_slave_0.address
			npu_system_0_avalon_slave_0_write              => mm_interconnect_1_npu_system_0_avalon_slave_0_write,       --                                         .write
			npu_system_0_avalon_slave_0_read               => mm_interconnect_1_npu_system_0_avalon_slave_0_read,        --                                         .read
			npu_system_0_avalon_slave_0_readdata           => mm_interconnect_1_npu_system_0_avalon_slave_0_readdata,    --                                         .readdata
			npu_system_0_avalon_slave_0_writedata          => mm_interconnect_1_npu_system_0_avalon_slave_0_writedata,   --                                         .writedata
			npu_system_0_avalon_slave_0_waitrequest        => mm_interconnect_1_npu_system_0_avalon_slave_0_waitrequest, --                                         .waitrequest
			data_mem_s1_address                            => mm_interconnect_1_data_mem_s1_address,                     --                              data_mem_s1.address
			data_mem_s1_write                              => mm_interconnect_1_data_mem_s1_write,                       --                                         .write
			data_mem_s1_readdata                           => mm_interconnect_1_data_mem_s1_readdata,                    --                                         .readdata
			data_mem_s1_writedata                          => mm_interconnect_1_data_mem_s1_writedata,                   --                                         .writedata
			data_mem_s1_byteenable                         => mm_interconnect_1_data_mem_s1_byteenable,                  --                                         .byteenable
			data_mem_s1_chipselect                         => mm_interconnect_1_data_mem_s1_chipselect,                  --                                         .chipselect
			data_mem_s1_clken                              => mm_interconnect_1_data_mem_s1_clken,                       --                                         .clken
			weight_mem_s1_address                          => mm_interconnect_1_weight_mem_s1_address,                   --                            weight_mem_s1.address
			weight_mem_s1_write                            => mm_interconnect_1_weight_mem_s1_write,                     --                                         .write
			weight_mem_s1_readdata                         => mm_interconnect_1_weight_mem_s1_readdata,                  --                                         .readdata
			weight_mem_s1_writedata                        => mm_interconnect_1_weight_mem_s1_writedata,                 --                                         .writedata
			weight_mem_s1_byteenable                       => mm_interconnect_1_weight_mem_s1_byteenable,                --                                         .byteenable
			weight_mem_s1_chipselect                       => mm_interconnect_1_weight_mem_s1_chipselect,                --                                         .chipselect
			weight_mem_s1_clken                            => mm_interconnect_1_weight_mem_s1_clken,                     --                                         .clken
			out_mem_s1_address                             => mm_interconnect_1_out_mem_s1_address,                      --                               out_mem_s1.address
			out_mem_s1_write                               => mm_interconnect_1_out_mem_s1_write,                        --                                         .write
			out_mem_s1_readdata                            => mm_interconnect_1_out_mem_s1_readdata,                     --                                         .readdata
			out_mem_s1_writedata                           => mm_interconnect_1_out_mem_s1_writedata,                    --                                         .writedata
			out_mem_s1_byteenable                          => mm_interconnect_1_out_mem_s1_byteenable,                   --                                         .byteenable
			out_mem_s1_chipselect                          => mm_interconnect_1_out_mem_s1_chipselect,                   --                                         .chipselect
			out_mem_s1_clken                               => mm_interconnect_1_out_mem_s1_clken,                        --                                         .clken
			npu_system_0_reset_reset_bridge_in_reset_reset => rst_controller_reset_out_reset,                            -- npu_system_0_reset_reset_bridge_in_reset.reset
			clock_in_out_clk_clk                           => clock_in_out_clk_clk                                       --                         clock_in_out_clk.clk
		);

	mm_interconnect_2 : component NonDPR_altera_mm_interconnect_1920_ak3ihbq_cmp
		port map (
			npu_system_0_out_address                       => npu_system_0_out_address,                --                         npu_system_0_out.address
			npu_system_0_out_waitrequest                   => npu_system_0_out_waitrequest,            --                                         .waitrequest
			npu_system_0_out_write                         => npu_system_0_out_write,                  --                                         .write
			npu_system_0_out_writedata                     => npu_system_0_out_writedata,              --                                         .writedata
			out_mem_s2_address                             => mm_interconnect_2_out_mem_s2_address,    --                               out_mem_s2.address
			out_mem_s2_write                               => mm_interconnect_2_out_mem_s2_write,      --                                         .write
			out_mem_s2_readdata                            => mm_interconnect_2_out_mem_s2_readdata,   --                                         .readdata
			out_mem_s2_writedata                           => mm_interconnect_2_out_mem_s2_writedata,  --                                         .writedata
			out_mem_s2_byteenable                          => mm_interconnect_2_out_mem_s2_byteenable, --                                         .byteenable
			out_mem_s2_chipselect                          => mm_interconnect_2_out_mem_s2_chipselect, --                                         .chipselect
			out_mem_s2_clken                               => mm_interconnect_2_out_mem_s2_clken,      --                                         .clken
			npu_system_0_reset_reset_bridge_in_reset_reset => rst_controller_reset_out_reset,          -- npu_system_0_reset_reset_bridge_in_reset.reset
			clock_in_out_clk_clk                           => clock_in_out_clk_clk                     --                         clock_in_out_clk.clk
		);

	mm_interconnect_3 : component NonDPR_altera_mm_interconnect_1920_iwcms7y_cmp
		port map (
			npu_system_0_weight_address                    => npu_system_0_weight_address,                --                      npu_system_0_weight.address
			npu_system_0_weight_waitrequest                => npu_system_0_weight_waitrequest,            --                                         .waitrequest
			npu_system_0_weight_read                       => npu_system_0_weight_read,                   --                                         .read
			npu_system_0_weight_readdata                   => npu_system_0_weight_readdata,               --                                         .readdata
			weight_mem_s2_address                          => mm_interconnect_3_weight_mem_s2_address,    --                            weight_mem_s2.address
			weight_mem_s2_write                            => mm_interconnect_3_weight_mem_s2_write,      --                                         .write
			weight_mem_s2_readdata                         => mm_interconnect_3_weight_mem_s2_readdata,   --                                         .readdata
			weight_mem_s2_writedata                        => mm_interconnect_3_weight_mem_s2_writedata,  --                                         .writedata
			weight_mem_s2_byteenable                       => mm_interconnect_3_weight_mem_s2_byteenable, --                                         .byteenable
			weight_mem_s2_chipselect                       => mm_interconnect_3_weight_mem_s2_chipselect, --                                         .chipselect
			weight_mem_s2_clken                            => mm_interconnect_3_weight_mem_s2_clken,      --                                         .clken
			npu_system_0_reset_reset_bridge_in_reset_reset => rst_controller_reset_out_reset,             -- npu_system_0_reset_reset_bridge_in_reset.reset
			clock_in_out_clk_clk                           => clock_in_out_clk_clk                        --                         clock_in_out_clk.clk
		);

	rst_controller : component altera_reset_controller_cmp
		generic map (
			NUM_RESET_INPUTS          => 1,
			OUTPUT_RESET_SYNC_EDGES   => "deassert",
			SYNC_DEPTH                => 2,
			RESET_REQUEST_PRESENT     => 1,
			RESET_REQ_WAIT_TIME       => 1,
			MIN_RST_ASSERTION_TIME    => 3,
			RESET_REQ_EARLY_DSRT_TIME => 1,
			USE_RESET_REQUEST_IN0     => 0,
			USE_RESET_REQUEST_IN1     => 0,
			USE_RESET_REQUEST_IN2     => 0,
			USE_RESET_REQUEST_IN3     => 0,
			USE_RESET_REQUEST_IN4     => 0,
			USE_RESET_REQUEST_IN5     => 0,
			USE_RESET_REQUEST_IN6     => 0,
			USE_RESET_REQUEST_IN7     => 0,
			USE_RESET_REQUEST_IN8     => 0,
			USE_RESET_REQUEST_IN9     => 0,
			USE_RESET_REQUEST_IN10    => 0,
			USE_RESET_REQUEST_IN11    => 0,
			USE_RESET_REQUEST_IN12    => 0,
			USE_RESET_REQUEST_IN13    => 0,
			USE_RESET_REQUEST_IN14    => 0,
			USE_RESET_REQUEST_IN15    => 0,
			ADAPT_RESET_REQUEST       => 0
		)
		port map (
			reset_in0      => reset_in_out_reset_reset,           -- reset_in0.reset
			clk            => clock_in_out_clk_clk,               --       clk.clk
			reset_out      => rst_controller_reset_out_reset,     -- reset_out.reset
			reset_req      => rst_controller_reset_out_reset_req, --          .reset_req
			reset_req_in0  => '0',                                -- (terminated)
			reset_in1      => '0',                                -- (terminated)
			reset_req_in1  => '0',                                -- (terminated)
			reset_in2      => '0',                                -- (terminated)
			reset_req_in2  => '0',                                -- (terminated)
			reset_in3      => '0',                                -- (terminated)
			reset_req_in3  => '0',                                -- (terminated)
			reset_in4      => '0',                                -- (terminated)
			reset_req_in4  => '0',                                -- (terminated)
			reset_in5      => '0',                                -- (terminated)
			reset_req_in5  => '0',                                -- (terminated)
			reset_in6      => '0',                                -- (terminated)
			reset_req_in6  => '0',                                -- (terminated)
			reset_in7      => '0',                                -- (terminated)
			reset_req_in7  => '0',                                -- (terminated)
			reset_in8      => '0',                                -- (terminated)
			reset_req_in8  => '0',                                -- (terminated)
			reset_in9      => '0',                                -- (terminated)
			reset_req_in9  => '0',                                -- (terminated)
			reset_in10     => '0',                                -- (terminated)
			reset_req_in10 => '0',                                -- (terminated)
			reset_in11     => '0',                                -- (terminated)
			reset_req_in11 => '0',                                -- (terminated)
			reset_in12     => '0',                                -- (terminated)
			reset_req_in12 => '0',                                -- (terminated)
			reset_in13     => '0',                                -- (terminated)
			reset_req_in13 => '0',                                -- (terminated)
			reset_in14     => '0',                                -- (terminated)
			reset_req_in14 => '0',                                -- (terminated)
			reset_in15     => '0',                                -- (terminated)
			reset_req_in15 => '0'                                 -- (terminated)
		);

	rst_controller_reset_out_reset_ports_inv <= not rst_controller_reset_out_reset;

end architecture rtl; -- of NonDPR
