-- SDRAM_altera_ip_col_if_1911_rqtxiaa.vhd

-- This file was auto-generated from altera_ip_col_if_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 24.1 115

library IEEE;
library altera_avalon_mm_bridge_2010;
library alt_mem_if_jtag_master_191;
library altera_mm_interconnect_1920;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity SDRAM_altera_ip_col_if_1911_rqtxiaa is
	port (
		avl_clk_in_clk         : in  std_logic                     := '0';             --  avl_clk_in.clk,          Clock Input
		avl_clk_out_clk        : out std_logic;                                        -- avl_clk_out.clk,          Clock Output
		avl_rst_in_reset       : in  std_logic                     := '0';             --  avl_rst_in.reset,        Reset Input
		avl_rst_out_reset      : out std_logic;                                        -- avl_rst_out.reset,        Reset Output
		to_ioaux_waitrequest   : in  std_logic                     := '0';             --    to_ioaux.waitrequest
		to_ioaux_readdata      : in  std_logic_vector(31 downto 0) := (others => '0'); --            .readdata
		to_ioaux_readdatavalid : in  std_logic                     := '0';             --            .readdatavalid
		to_ioaux_burstcount    : out std_logic_vector(0 downto 0);                     --            .burstcount
		to_ioaux_writedata     : out std_logic_vector(31 downto 0);                    --            .writedata
		to_ioaux_address       : out std_logic_vector(29 downto 0);                    --            .address
		to_ioaux_write         : out std_logic;                                        --            .write
		to_ioaux_read          : out std_logic;                                        --            .read
		to_ioaux_byteenable    : out std_logic_vector(3 downto 0);                     --            .byteenable
		to_ioaux_debugaccess   : out std_logic                                         --            .debugaccess
	);
end entity SDRAM_altera_ip_col_if_1911_rqtxiaa;

architecture rtl of SDRAM_altera_ip_col_if_1911_rqtxiaa is
	component SDRAM_altera_avalon_mm_bridge_2010_xnk2xbi_cmp is
		generic (
			DATA_WIDTH               : integer := 32;
			SYMBOL_WIDTH             : integer := 8;
			HDL_ADDR_WIDTH           : integer := 10;
			BURSTCOUNT_WIDTH         : integer := 1;
			PIPELINE_COMMAND         : integer := 1;
			PIPELINE_RESPONSE        : integer := 1;
			SYNC_RESET               : integer := 0;
			USE_WRITERESPONSE        : integer := 0;
			S0_WAITREQUEST_ALLOWANCE : integer := 0;
			M0_WAITREQUEST_ALLOWANCE : integer := 0
		);
		port (
			clk                   : in  std_logic                                     := 'X';             -- clk
			reset                 : in  std_logic                                     := 'X';             -- reset
			s0_waitrequest        : out std_logic;                                                        -- waitrequest
			s0_readdata           : out std_logic_vector(DATA_WIDTH-1 downto 0);                          -- readdata
			s0_readdatavalid      : out std_logic;                                                        -- readdatavalid
			s0_burstcount         : in  std_logic_vector(BURSTCOUNT_WIDTH-1 downto 0) := (others => 'X'); -- burstcount
			s0_writedata          : in  std_logic_vector(DATA_WIDTH-1 downto 0)       := (others => 'X'); -- writedata
			s0_address            : in  std_logic_vector(HDL_ADDR_WIDTH-1 downto 0)   := (others => 'X'); -- address
			s0_write              : in  std_logic                                     := 'X';             -- write
			s0_read               : in  std_logic                                     := 'X';             -- read
			s0_byteenable         : in  std_logic_vector(3 downto 0)                  := (others => 'X'); -- byteenable
			s0_debugaccess        : in  std_logic                                     := 'X';             -- debugaccess
			m0_waitrequest        : in  std_logic                                     := 'X';             -- waitrequest
			m0_readdata           : in  std_logic_vector(DATA_WIDTH-1 downto 0)       := (others => 'X'); -- readdata
			m0_readdatavalid      : in  std_logic                                     := 'X';             -- readdatavalid
			m0_burstcount         : out std_logic_vector(BURSTCOUNT_WIDTH-1 downto 0);                    -- burstcount
			m0_writedata          : out std_logic_vector(DATA_WIDTH-1 downto 0);                          -- writedata
			m0_address            : out std_logic_vector(HDL_ADDR_WIDTH-1 downto 0);                      -- address
			m0_write              : out std_logic;                                                        -- write
			m0_read               : out std_logic;                                                        -- read
			m0_byteenable         : out std_logic_vector(3 downto 0);                                     -- byteenable
			m0_debugaccess        : out std_logic;                                                        -- debugaccess
			s0_response           : out std_logic_vector(1 downto 0);                                     -- response
			s0_writeresponsevalid : out std_logic;                                                        -- writeresponsevalid
			m0_response           : in  std_logic_vector(1 downto 0)                  := (others => 'X'); -- response
			m0_writeresponsevalid : in  std_logic                                     := 'X'              -- writeresponsevalid
		);
	end component SDRAM_altera_avalon_mm_bridge_2010_xnk2xbi_cmp;

	component SDRAM_alt_mem_if_jtag_master_191_rksoe3i_cmp is
		generic (
			USE_PLI     : integer := 0;
			PLI_PORT    : integer := 50000;
			FIFO_DEPTHS : integer := 2
		);
		port (
			clk_clk              : in  std_logic                     := 'X';             -- clk
			clk_reset_reset      : in  std_logic                     := 'X';             -- reset
			master_reset_reset   : out std_logic;                                        -- reset
			master_address       : out std_logic_vector(31 downto 0);                    -- address
			master_readdata      : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			master_read          : out std_logic;                                        -- read
			master_write         : out std_logic;                                        -- write
			master_writedata     : out std_logic_vector(31 downto 0);                    -- writedata
			master_waitrequest   : in  std_logic                     := 'X';             -- waitrequest
			master_readdatavalid : in  std_logic                     := 'X';             -- readdatavalid
			master_byteenable    : out std_logic_vector(3 downto 0)                      -- byteenable
		);
	end component SDRAM_alt_mem_if_jtag_master_191_rksoe3i_cmp;

	component SDRAM_altera_mm_interconnect_1920_mlnx7ry_cmp is
		port (
			colmaster_master_address                         : in  std_logic_vector(31 downto 0) := (others => 'X'); -- address
			colmaster_master_waitrequest                     : out std_logic;                                        -- waitrequest
			colmaster_master_byteenable                      : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			colmaster_master_read                            : in  std_logic                     := 'X';             -- read
			colmaster_master_readdata                        : out std_logic_vector(31 downto 0);                    -- readdata
			colmaster_master_readdatavalid                   : out std_logic;                                        -- readdatavalid
			colmaster_master_write                           : in  std_logic                     := 'X';             -- write
			colmaster_master_writedata                       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			avl_bridge_out_s0_address                        : out std_logic_vector(29 downto 0);                    -- address
			avl_bridge_out_s0_write                          : out std_logic;                                        -- write
			avl_bridge_out_s0_read                           : out std_logic;                                        -- read
			avl_bridge_out_s0_readdata                       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			avl_bridge_out_s0_writedata                      : out std_logic_vector(31 downto 0);                    -- writedata
			avl_bridge_out_s0_burstcount                     : out std_logic_vector(0 downto 0);                     -- burstcount
			avl_bridge_out_s0_byteenable                     : out std_logic_vector(3 downto 0);                     -- byteenable
			avl_bridge_out_s0_readdatavalid                  : in  std_logic                     := 'X';             -- readdatavalid
			avl_bridge_out_s0_waitrequest                    : in  std_logic                     := 'X';             -- waitrequest
			avl_bridge_out_s0_debugaccess                    : out std_logic;                                        -- debugaccess
			avl_bridge_out_reset_reset_bridge_in_reset_reset : in  std_logic                     := 'X';             -- reset
			clk_bridge_out_clk_1_clk                         : in  std_logic                     := 'X'              -- clk
		);
	end component SDRAM_altera_mm_interconnect_1920_mlnx7ry_cmp;

	signal colmaster_master_readdata                         : std_logic_vector(31 downto 0); -- mm_interconnect_0:colmaster_master_readdata -> colmaster:master_readdata
	signal colmaster_master_waitrequest                      : std_logic;                     -- mm_interconnect_0:colmaster_master_waitrequest -> colmaster:master_waitrequest
	signal colmaster_master_address                          : std_logic_vector(31 downto 0); -- colmaster:master_address -> mm_interconnect_0:colmaster_master_address
	signal colmaster_master_read                             : std_logic;                     -- colmaster:master_read -> mm_interconnect_0:colmaster_master_read
	signal colmaster_master_byteenable                       : std_logic_vector(3 downto 0);  -- colmaster:master_byteenable -> mm_interconnect_0:colmaster_master_byteenable
	signal colmaster_master_readdatavalid                    : std_logic;                     -- mm_interconnect_0:colmaster_master_readdatavalid -> colmaster:master_readdatavalid
	signal colmaster_master_write                            : std_logic;                     -- colmaster:master_write -> mm_interconnect_0:colmaster_master_write
	signal colmaster_master_writedata                        : std_logic_vector(31 downto 0); -- colmaster:master_writedata -> mm_interconnect_0:colmaster_master_writedata
	signal mm_interconnect_0_avl_bridge_out_s0_readdata      : std_logic_vector(31 downto 0); -- avl_bridge_out:s0_readdata -> mm_interconnect_0:avl_bridge_out_s0_readdata
	signal mm_interconnect_0_avl_bridge_out_s0_waitrequest   : std_logic;                     -- avl_bridge_out:s0_waitrequest -> mm_interconnect_0:avl_bridge_out_s0_waitrequest
	signal mm_interconnect_0_avl_bridge_out_s0_debugaccess   : std_logic;                     -- mm_interconnect_0:avl_bridge_out_s0_debugaccess -> avl_bridge_out:s0_debugaccess
	signal mm_interconnect_0_avl_bridge_out_s0_address       : std_logic_vector(29 downto 0); -- mm_interconnect_0:avl_bridge_out_s0_address -> avl_bridge_out:s0_address
	signal mm_interconnect_0_avl_bridge_out_s0_read          : std_logic;                     -- mm_interconnect_0:avl_bridge_out_s0_read -> avl_bridge_out:s0_read
	signal mm_interconnect_0_avl_bridge_out_s0_byteenable    : std_logic_vector(3 downto 0);  -- mm_interconnect_0:avl_bridge_out_s0_byteenable -> avl_bridge_out:s0_byteenable
	signal mm_interconnect_0_avl_bridge_out_s0_readdatavalid : std_logic;                     -- avl_bridge_out:s0_readdatavalid -> mm_interconnect_0:avl_bridge_out_s0_readdatavalid
	signal mm_interconnect_0_avl_bridge_out_s0_write         : std_logic;                     -- mm_interconnect_0:avl_bridge_out_s0_write -> avl_bridge_out:s0_write
	signal mm_interconnect_0_avl_bridge_out_s0_writedata     : std_logic_vector(31 downto 0); -- mm_interconnect_0:avl_bridge_out_s0_writedata -> avl_bridge_out:s0_writedata
	signal mm_interconnect_0_avl_bridge_out_s0_burstcount    : std_logic_vector(0 downto 0);  -- mm_interconnect_0:avl_bridge_out_s0_burstcount -> avl_bridge_out:s0_burstcount

	for avl_bridge_out : SDRAM_altera_avalon_mm_bridge_2010_xnk2xbi_cmp
		use entity altera_avalon_mm_bridge_2010.SDRAM_altera_avalon_mm_bridge_2010_xnk2xbi;
	for colmaster : SDRAM_alt_mem_if_jtag_master_191_rksoe3i_cmp
		use entity alt_mem_if_jtag_master_191.SDRAM_alt_mem_if_jtag_master_191_rksoe3i;
	for mm_interconnect_0 : SDRAM_altera_mm_interconnect_1920_mlnx7ry_cmp
		use entity altera_mm_interconnect_1920.SDRAM_altera_mm_interconnect_1920_mlnx7ry;
begin

	avl_bridge_out : component SDRAM_altera_avalon_mm_bridge_2010_xnk2xbi_cmp
		generic map (
			DATA_WIDTH               => 32,
			SYMBOL_WIDTH             => 8,
			HDL_ADDR_WIDTH           => 30,
			BURSTCOUNT_WIDTH         => 1,
			PIPELINE_COMMAND         => 1,
			PIPELINE_RESPONSE        => 1,
			SYNC_RESET               => 0,
			USE_WRITERESPONSE        => 0,
			S0_WAITREQUEST_ALLOWANCE => 0,
			M0_WAITREQUEST_ALLOWANCE => 0
		)
		port map (
			clk                   => avl_clk_in_clk,                                    --   clk.clk
			reset                 => avl_rst_in_reset,                                  -- reset.reset
			s0_waitrequest        => mm_interconnect_0_avl_bridge_out_s0_waitrequest,   --    s0.waitrequest
			s0_readdata           => mm_interconnect_0_avl_bridge_out_s0_readdata,      --      .readdata
			s0_readdatavalid      => mm_interconnect_0_avl_bridge_out_s0_readdatavalid, --      .readdatavalid
			s0_burstcount         => mm_interconnect_0_avl_bridge_out_s0_burstcount,    --      .burstcount
			s0_writedata          => mm_interconnect_0_avl_bridge_out_s0_writedata,     --      .writedata
			s0_address            => mm_interconnect_0_avl_bridge_out_s0_address,       --      .address
			s0_write              => mm_interconnect_0_avl_bridge_out_s0_write,         --      .write
			s0_read               => mm_interconnect_0_avl_bridge_out_s0_read,          --      .read
			s0_byteenable         => mm_interconnect_0_avl_bridge_out_s0_byteenable,    --      .byteenable
			s0_debugaccess        => mm_interconnect_0_avl_bridge_out_s0_debugaccess,   --      .debugaccess
			m0_waitrequest        => to_ioaux_waitrequest,                              --    m0.waitrequest
			m0_readdata           => to_ioaux_readdata,                                 --      .readdata
			m0_readdatavalid      => to_ioaux_readdatavalid,                            --      .readdatavalid
			m0_burstcount         => to_ioaux_burstcount,                               --      .burstcount
			m0_writedata          => to_ioaux_writedata,                                --      .writedata
			m0_address            => to_ioaux_address,                                  --      .address
			m0_write              => to_ioaux_write,                                    --      .write
			m0_read               => to_ioaux_read,                                     --      .read
			m0_byteenable         => to_ioaux_byteenable,                               --      .byteenable
			m0_debugaccess        => to_ioaux_debugaccess,                              --      .debugaccess
			s0_response           => open,                                              -- (terminated)
			s0_writeresponsevalid => open,                                              -- (terminated)
			m0_response           => "00",                                              -- (terminated)
			m0_writeresponsevalid => '0'                                                -- (terminated)
		);

	colmaster : component SDRAM_alt_mem_if_jtag_master_191_rksoe3i_cmp
		generic map (
			USE_PLI     => 0,
			PLI_PORT    => 50000,
			FIFO_DEPTHS => 2
		)
		port map (
			clk_clk              => avl_clk_in_clk,                 --          clk.clk
			clk_reset_reset      => avl_rst_in_reset,               --    clk_reset.reset
			master_reset_reset   => open,                           -- master_reset.reset
			master_address       => colmaster_master_address,       --       master.address
			master_readdata      => colmaster_master_readdata,      --             .readdata
			master_read          => colmaster_master_read,          --             .read
			master_write         => colmaster_master_write,         --             .write
			master_writedata     => colmaster_master_writedata,     --             .writedata
			master_waitrequest   => colmaster_master_waitrequest,   --             .waitrequest
			master_readdatavalid => colmaster_master_readdatavalid, --             .readdatavalid
			master_byteenable    => colmaster_master_byteenable     --             .byteenable
		);

	mm_interconnect_0 : component SDRAM_altera_mm_interconnect_1920_mlnx7ry_cmp
		port map (
			colmaster_master_address                         => colmaster_master_address,                          --                           colmaster_master.address
			colmaster_master_waitrequest                     => colmaster_master_waitrequest,                      --                                           .waitrequest
			colmaster_master_byteenable                      => colmaster_master_byteenable,                       --                                           .byteenable
			colmaster_master_read                            => colmaster_master_read,                             --                                           .read
			colmaster_master_readdata                        => colmaster_master_readdata,                         --                                           .readdata
			colmaster_master_readdatavalid                   => colmaster_master_readdatavalid,                    --                                           .readdatavalid
			colmaster_master_write                           => colmaster_master_write,                            --                                           .write
			colmaster_master_writedata                       => colmaster_master_writedata,                        --                                           .writedata
			avl_bridge_out_s0_address                        => mm_interconnect_0_avl_bridge_out_s0_address,       --                          avl_bridge_out_s0.address
			avl_bridge_out_s0_write                          => mm_interconnect_0_avl_bridge_out_s0_write,         --                                           .write
			avl_bridge_out_s0_read                           => mm_interconnect_0_avl_bridge_out_s0_read,          --                                           .read
			avl_bridge_out_s0_readdata                       => mm_interconnect_0_avl_bridge_out_s0_readdata,      --                                           .readdata
			avl_bridge_out_s0_writedata                      => mm_interconnect_0_avl_bridge_out_s0_writedata,     --                                           .writedata
			avl_bridge_out_s0_burstcount                     => mm_interconnect_0_avl_bridge_out_s0_burstcount,    --                                           .burstcount
			avl_bridge_out_s0_byteenable                     => mm_interconnect_0_avl_bridge_out_s0_byteenable,    --                                           .byteenable
			avl_bridge_out_s0_readdatavalid                  => mm_interconnect_0_avl_bridge_out_s0_readdatavalid, --                                           .readdatavalid
			avl_bridge_out_s0_waitrequest                    => mm_interconnect_0_avl_bridge_out_s0_waitrequest,   --                                           .waitrequest
			avl_bridge_out_s0_debugaccess                    => mm_interconnect_0_avl_bridge_out_s0_debugaccess,   --                                           .debugaccess
			avl_bridge_out_reset_reset_bridge_in_reset_reset => avl_rst_in_reset,                                  -- avl_bridge_out_reset_reset_bridge_in_reset.reset
			clk_bridge_out_clk_1_clk                         => avl_clk_in_clk                                     --                       clk_bridge_out_clk_1.clk
		);

	avl_clk_out_clk <= avl_clk_in_clk;

	avl_rst_out_reset <= avl_rst_in_reset;

end architecture rtl; -- of SDRAM_altera_ip_col_if_1911_rqtxiaa
