// debug.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module debug (
		output wire [0:0] source,     //    sources.source
		input  wire       source_clk, // source_clk.clk
		input  wire [0:0] probe       //     probes.probe
	);

	altsource_probe_top #(
		.sld_auto_instance_index ("YES"),
		.sld_instance_index      (0),
		.instance_id             ("NONE"),
		.probe_width             (1),
		.source_width            (1),
		.source_initial_value    ("0"),
		.enable_metastability    ("YES")
	) in_system_sources_probes_0 (
		.source     (source),     //  output,  width = 1,    sources.source
		.source_clk (source_clk), //   input,  width = 1, source_clk.clk
		.probe      (probe),      //   input,  width = 1,     probes.probe
		.source_ena (1'b1)        // (terminated),                        
	);

endmodule
