-- WeightBuffer2.vhd

-- Generated using ACDS version 25.3 109

library IEEE;
library ram_2port_2060;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity WeightBuffer2 is
	port (
		data_a    : in  std_logic_vector(15 downto 0) := (others => '0'); --    data_a.datain_a,  Data input to port A of the memory.The data port is required for all RAM operation modes:SINGLE_PORT,DUAL_PORT,BIDIR_DUAL_PORT,QUAD_PORT
		q_a       : out std_logic_vector(15 downto 0);                    --       q_a.dataout_a, Data output from port A of the memory. The data port is required if the operation modes parameter is set to any of the following values:SINGLE_PORT,BIDIR_DUAL_PORT,QUAD_PORT,ROM
		data_b    : in  std_logic_vector(15 downto 0) := (others => '0'); --    data_b.datain_b,  Data input to port B of the memory.The data_b port is required if the operation_mode parameter is set to BIDIR_DUAL_PORT and QUAD_PORT
		q_b       : out std_logic_vector(15 downto 0);                    --       q_b.dataout_b, Data output from port B of the memory. The q_b port is required if the operation_mode is set to the following values:DUAL_PORT,BIDIR_DUAL_PORT,QUAD_PORT
		address_a : in  std_logic_vector(9 downto 0)  := (others => '0'); -- address_a.address_a, Address input to port A of the memory.The address_a signal is required for all operation modes.
		address_b : in  std_logic_vector(9 downto 0)  := (others => '0'); -- address_b.address_b, Address input to port B of the memory.The address_b port is required if the operation_mode parameter is set to the following values:DUAL_PORT,BIDIR_DUAL_PORT,QUAD_PORT
		wren_a    : in  std_logic                     := '0';             --    wren_a.wren_a,    Write enable input for address_a port.The wren_a signal is required all RAM operation modes:SINGLE_PORT,DUAL_PORT,BIDIR_DUAL_PORT,QUAD_PORT
		wren_b    : in  std_logic                     := '0';             --    wren_b.wren_b,    Write enable input for address_b port.The wren_b port is required if operation_mode is set to BIDIR_DUAL_PORT and QUAD_PORT.
		clock     : in  std_logic                     := '0';             --     clock.clk,       Memory clock, refer to user guide for specific details
		freeze    : in  std_logic                     := '0';             --    freeze.freeze
		enable    : in  std_logic                     := '0';             --    enable.enable
		aclr      : in  std_logic                     := '0'              --      aclr.reset,     Asynchronously clear the output ports. The asynchronous clear effect on the registered ports can be controlled through their corresponding clear parameter, such as outdata_aclr_a and outdata_aclr_b.
	);
end entity WeightBuffer2;

architecture rtl of WeightBuffer2 is
	component WeightBuffer2_ram_2port_2060_u3jegsa_cmp is
		port (
			data_a    : in  std_logic_vector(15 downto 0) := (others => 'X'); -- datain_a
			q_a       : out std_logic_vector(15 downto 0);                    -- dataout_a
			data_b    : in  std_logic_vector(15 downto 0) := (others => 'X'); -- datain_b
			q_b       : out std_logic_vector(15 downto 0);                    -- dataout_b
			address_a : in  std_logic_vector(9 downto 0)  := (others => 'X'); -- address_a
			address_b : in  std_logic_vector(9 downto 0)  := (others => 'X'); -- address_b
			wren_a    : in  std_logic                     := 'X';             -- wren_a
			wren_b    : in  std_logic                     := 'X';             -- wren_b
			clock     : in  std_logic                     := 'X';             -- clk
			freeze    : in  std_logic                     := 'X';             -- freeze
			enable    : in  std_logic                     := 'X';             -- enable
			aclr      : in  std_logic                     := 'X'              -- reset
		);
	end component WeightBuffer2_ram_2port_2060_u3jegsa_cmp;

	for ram_2port_0 : WeightBuffer2_ram_2port_2060_u3jegsa_cmp
		use entity ram_2port_2060.WeightBuffer2_ram_2port_2060_u3jegsa;
begin

	ram_2port_0 : component WeightBuffer2_ram_2port_2060_u3jegsa_cmp
		port map (
			data_a    => data_a,    --    data_a.datain_a
			q_a       => q_a,       --       q_a.dataout_a
			data_b    => data_b,    --    data_b.datain_b
			q_b       => q_b,       --       q_b.dataout_b
			address_a => address_a, -- address_a.address_a
			address_b => address_b, -- address_b.address_b
			wren_a    => wren_a,    --    wren_a.wren_a
			wren_b    => wren_b,    --    wren_b.wren_b
			clock     => clock,     --     clock.clk
			freeze    => freeze,    --    freeze.freeze
			enable    => enable,    --    enable.enable
			aclr      => aclr       --      aclr.reset
		);

end architecture rtl; -- of WeightBuffer2
