// mSGDMA_PR_altera_msgdma_1924_or724ii.v

// This file was auto-generated from altera_msgdma_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module mSGDMA_PR_altera_msgdma_1924_or724ii (
		input  wire         clock_clk,                    //            clock.clk,          Clock Input
		input  wire         reset_n_reset_n,              //          reset_n.reset_n,      Reset Input
		input  wire [31:0]  csr_writedata,                //              csr.writedata
		input  wire         csr_write,                    //                 .write
		input  wire [3:0]   csr_byteenable,               //                 .byteenable
		output wire [31:0]  csr_readdata,                 //                 .readdata
		input  wire         csr_read,                     //                 .read
		input  wire [2:0]   csr_address,                  //                 .address
		input  wire         descriptor_slave_write,       // descriptor_slave.write
		output wire         descriptor_slave_waitrequest, //                 .waitrequest
		input  wire [127:0] descriptor_slave_writedata,   //                 .writedata
		input  wire [15:0]  descriptor_slave_byteenable,  //                 .byteenable
		output wire         csr_irq_irq,                  //          csr_irq.irq
		output wire [31:0]  mm_read_address,              //          mm_read.address
		output wire         mm_read_read,                 //                 .read
		output wire [3:0]   mm_read_byteenable,           //                 .byteenable
		input  wire [31:0]  mm_read_readdata,             //                 .readdata
		input  wire         mm_read_waitrequest,          //                 .waitrequest
		input  wire         mm_read_readdatavalid,        //                 .readdatavalid
		output wire [1:0]   mm_read_burstcount,           //                 .burstcount
		output wire [31:0]  mm_write_address,             //         mm_write.address
		output wire         mm_write_write,               //                 .write
		output wire [3:0]   mm_write_byteenable,          //                 .byteenable
		output wire [31:0]  mm_write_writedata,           //                 .writedata
		input  wire         mm_write_waitrequest,         //                 .waitrequest
		output wire [1:0]   mm_write_burstcount           //                 .burstcount
	);

	wire          read_mstr_internal_data_source_valid;           // read_mstr_internal:src_valid -> write_mstr_internal:snk_valid
	wire   [31:0] read_mstr_internal_data_source_data;            // read_mstr_internal:src_data -> write_mstr_internal:snk_data
	wire          read_mstr_internal_data_source_ready;           // write_mstr_internal:snk_ready -> read_mstr_internal:src_ready
	wire          dispatcher_internal_read_command_source_valid;  // dispatcher_internal:src_read_master_valid -> read_mstr_internal:snk_command_valid
	wire  [255:0] dispatcher_internal_read_command_source_data;   // dispatcher_internal:src_read_master_data -> read_mstr_internal:snk_command_data
	wire          dispatcher_internal_read_command_source_ready;  // read_mstr_internal:snk_command_ready -> dispatcher_internal:src_read_master_ready
	wire          read_mstr_internal_response_source_valid;       // read_mstr_internal:src_response_valid -> dispatcher_internal:snk_read_master_valid
	wire  [255:0] read_mstr_internal_response_source_data;        // read_mstr_internal:src_response_data -> dispatcher_internal:snk_read_master_data
	wire          read_mstr_internal_response_source_ready;       // dispatcher_internal:snk_read_master_ready -> read_mstr_internal:src_response_ready
	wire          dispatcher_internal_write_command_source_valid; // dispatcher_internal:src_write_master_valid -> write_mstr_internal:snk_command_valid
	wire  [255:0] dispatcher_internal_write_command_source_data;  // dispatcher_internal:src_write_master_data -> write_mstr_internal:snk_command_data
	wire          dispatcher_internal_write_command_source_ready; // write_mstr_internal:snk_command_ready -> dispatcher_internal:src_write_master_ready
	wire          write_mstr_internal_response_source_valid;      // write_mstr_internal:src_response_valid -> dispatcher_internal:snk_write_master_valid
	wire  [255:0] write_mstr_internal_response_source_data;       // write_mstr_internal:src_response_data -> dispatcher_internal:snk_write_master_data
	wire          write_mstr_internal_response_source_ready;      // dispatcher_internal:snk_write_master_ready -> write_mstr_internal:src_response_ready

	dispatcher #(
		.DEVICE_FAMILY                 ("Arria 10"),
		.PREFETCHER_USE_CASE           (0),
		.MODE                          (0),
		.RESPONSE_PORT                 (2),
		.DESCRIPTOR_INTERFACE          (0),
		.DESCRIPTOR_FIFO_DEPTH         (128),
		.ENHANCED_FEATURES             (0),
		.DESCRIPTOR_WIDTH              (128),
		.DESCRIPTOR_BYTEENABLE_WIDTH   (16),
		.DATA_WIDTH_DERIVED            (2),
		.DATA_FIFO_DEPTH_DERIVED       (2),
		.MAX_BYTE_DERIVED              (0),
		.TRANSFER_TYPE_DERIVED         (0),
		.BURST_ENABLE                  (1),
		.MAX_BURST_COUNT_DERIVED       (0),
		.BURST_WRAPPING_SUPPORT        (0),
		.STRIDE_ENABLE_DERIVED         (0),
		.MAX_STRIDE_DERIVED            (0),
		.PROGRAMMABLE_BURST_ENABLE     (0),
		.CHANNEL_ENABLE                (0),
		.CHANNEL_WIDTH_DERIVED         (7),
		.ERROR_ENABLE                  (0),
		.ERROR_WIDTH_DERIVED           (7),
		.PACKET_ENABLE                 (0),
		.DESCRIPTOR_FIFO_DEPTH_DERIVED (4)
	) dispatcher_internal (
		.clk                     (clock_clk),                                                                                                                             //   input,    width = 1,                clock.clk
		.reset                   (~reset_n_reset_n),                                                                                                                      //   input,    width = 1,          clock_reset.reset
		.csr_writedata           (csr_writedata),                                                                                                                         //   input,   width = 32,                  CSR.writedata
		.csr_write               (csr_write),                                                                                                                             //   input,    width = 1,                     .write
		.csr_byteenable          (csr_byteenable),                                                                                                                        //   input,    width = 4,                     .byteenable
		.csr_readdata            (csr_readdata),                                                                                                                          //  output,   width = 32,                     .readdata
		.csr_read                (csr_read),                                                                                                                              //   input,    width = 1,                     .read
		.csr_address             (csr_address),                                                                                                                           //   input,    width = 3,                     .address
		.descriptor_write        (descriptor_slave_write),                                                                                                                //   input,    width = 1,     Descriptor_Slave.write
		.descriptor_waitrequest  (descriptor_slave_waitrequest),                                                                                                          //  output,    width = 1,                     .waitrequest
		.descriptor_writedata    (descriptor_slave_writedata),                                                                                                            //   input,  width = 128,                     .writedata
		.descriptor_byteenable   (descriptor_slave_byteenable),                                                                                                           //   input,   width = 16,                     .byteenable
		.src_write_master_data   (dispatcher_internal_write_command_source_data),                                                                                         //  output,  width = 256, Write_Command_Source.data
		.src_write_master_valid  (dispatcher_internal_write_command_source_valid),                                                                                        //  output,    width = 1,                     .valid
		.src_write_master_ready  (dispatcher_internal_write_command_source_ready),                                                                                        //   input,    width = 1,                     .ready
		.snk_write_master_data   (write_mstr_internal_response_source_data),                                                                                              //   input,  width = 256,  Write_Response_Sink.data
		.snk_write_master_valid  (write_mstr_internal_response_source_valid),                                                                                             //   input,    width = 1,                     .valid
		.snk_write_master_ready  (write_mstr_internal_response_source_ready),                                                                                             //  output,    width = 1,                     .ready
		.src_read_master_data    (dispatcher_internal_read_command_source_data),                                                                                          //  output,  width = 256,  Read_Command_Source.data
		.src_read_master_valid   (dispatcher_internal_read_command_source_valid),                                                                                         //  output,    width = 1,                     .valid
		.src_read_master_ready   (dispatcher_internal_read_command_source_ready),                                                                                         //   input,    width = 1,                     .ready
		.snk_read_master_data    (read_mstr_internal_response_source_data),                                                                                               //   input,  width = 256,   Read_Response_Sink.data
		.snk_read_master_valid   (read_mstr_internal_response_source_valid),                                                                                              //   input,    width = 1,                     .valid
		.snk_read_master_ready   (read_mstr_internal_response_source_ready),                                                                                              //  output,    width = 1,                     .ready
		.csr_irq                 (csr_irq_irq),                                                                                                                           //  output,    width = 1,              csr_irq.irq
		.src_response_data       (),                                                                                                                                      // (terminated),                                    
		.src_response_valid      (),                                                                                                                                      // (terminated),                                    
		.src_response_ready      (1'b0),                                                                                                                                  // (terminated),                                    
		.snk_descriptor_data     (128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000), // (terminated),                                    
		.snk_descriptor_valid    (1'b0),                                                                                                                                  // (terminated),                                    
		.snk_descriptor_ready    (),                                                                                                                                      // (terminated),                                    
		.mm_response_waitrequest (),                                                                                                                                      // (terminated),                                    
		.mm_response_byteenable  (4'b0000),                                                                                                                               // (terminated),                                    
		.mm_response_address     (1'b0),                                                                                                                                  // (terminated),                                    
		.mm_response_readdata    (),                                                                                                                                      // (terminated),                                    
		.mm_response_read        (1'b0)                                                                                                                                   // (terminated),                                    
	);

	read_master #(
		.DEVICE_FAMILY             ("Arria 10"),
		.DATA_WIDTH                (32),
		.LENGTH_WIDTH              (11),
		.FIFO_DEPTH                (64),
		.STRIDE_ENABLE             (0),
		.BURST_ENABLE              (1),
		.PACKET_ENABLE             (0),
		.ERROR_ENABLE              (0),
		.ERROR_WIDTH               (8),
		.CHANNEL_ENABLE            (0),
		.CHANNEL_WIDTH             (8),
		.BYTE_ENABLE_WIDTH         (4),
		.BYTE_ENABLE_WIDTH_LOG2    (2),
		.ADDRESS_WIDTH             (32),
		.FIFO_DEPTH_LOG2           (6),
		.SYMBOL_WIDTH              (8),
		.NUMBER_OF_SYMBOLS         (4),
		.NUMBER_OF_SYMBOLS_LOG2    (2),
		.MAX_BURST_COUNT_WIDTH     (2),
		.UNALIGNED_ACCESSES_ENABLE (0),
		.ONLY_FULL_ACCESS_ENABLE   (1),
		.BURST_WRAPPING_SUPPORT    (0),
		.PROGRAMMABLE_BURST_ENABLE (0),
		.MAX_BURST_COUNT           (2),
		.FIFO_SPEED_OPTIMIZATION   (1),
		.STRIDE_WIDTH              (1)
	) read_mstr_internal (
		.clk                  (clock_clk),                                     //   input,    width = 1,            Clock.clk
		.reset                (~reset_n_reset_n),                              //   input,    width = 1,      Clock_reset.reset
		.master_address       (mm_read_address),                               //  output,   width = 32, Data_Read_Master.address
		.master_read          (mm_read_read),                                  //  output,    width = 1,                 .read
		.master_byteenable    (mm_read_byteenable),                            //  output,    width = 4,                 .byteenable
		.master_readdata      (mm_read_readdata),                              //   input,   width = 32,                 .readdata
		.master_waitrequest   (mm_read_waitrequest),                           //   input,    width = 1,                 .waitrequest
		.master_readdatavalid (mm_read_readdatavalid),                         //   input,    width = 1,                 .readdatavalid
		.master_burstcount    (mm_read_burstcount),                            //  output,    width = 2,                 .burstcount
		.src_data             (read_mstr_internal_data_source_data),           //  output,   width = 32,      Data_Source.data
		.src_valid            (read_mstr_internal_data_source_valid),          //  output,    width = 1,                 .valid
		.src_ready            (read_mstr_internal_data_source_ready),          //   input,    width = 1,                 .ready
		.snk_command_data     (dispatcher_internal_read_command_source_data),  //   input,  width = 256,     Command_Sink.data
		.snk_command_valid    (dispatcher_internal_read_command_source_valid), //   input,    width = 1,                 .valid
		.snk_command_ready    (dispatcher_internal_read_command_source_ready), //  output,    width = 1,                 .ready
		.src_response_data    (read_mstr_internal_response_source_data),       //  output,  width = 256,  Response_Source.data
		.src_response_valid   (read_mstr_internal_response_source_valid),      //  output,    width = 1,                 .valid
		.src_response_ready   (read_mstr_internal_response_source_ready),      //   input,    width = 1,                 .ready
		.src_sop              (),                                              // (terminated),                                
		.src_eop              (),                                              // (terminated),                                
		.src_empty            (),                                              // (terminated),                                
		.src_error            (),                                              // (terminated),                                
		.src_channel          ()                                               // (terminated),                                
	);

	write_master #(
		.DEVICE_FAMILY                  ("Arria 10"),
		.DATA_WIDTH                     (32),
		.LENGTH_WIDTH                   (11),
		.FIFO_DEPTH                     (64),
		.STRIDE_ENABLE                  (0),
		.BURST_ENABLE                   (1),
		.WRITE_RESPONSE_ENABLE          (0),
		.PACKET_ENABLE                  (0),
		.ERROR_ENABLE                   (0),
		.ERROR_WIDTH                    (8),
		.BYTE_ENABLE_WIDTH              (4),
		.BYTE_ENABLE_WIDTH_LOG2         (2),
		.NO_BYTEENABLES                 (0),
		.ADDRESS_WIDTH                  (32),
		.FIFO_DEPTH_LOG2                (6),
		.SYMBOL_WIDTH                   (8),
		.NUMBER_OF_SYMBOLS              (4),
		.NUMBER_OF_SYMBOLS_LOG2         (2),
		.MAX_BURST_COUNT_WIDTH          (2),
		.UNALIGNED_ACCESSES_ENABLE      (0),
		.ONLY_FULL_ACCESS_ENABLE        (1),
		.BURST_WRAPPING_SUPPORT         (0),
		.PROGRAMMABLE_BURST_ENABLE      (0),
		.MAX_BURST_COUNT                (2),
		.FIFO_SPEED_OPTIMIZATION        (1),
		.STRIDE_WIDTH                   (1),
		.ACTUAL_BYTES_TRANSFERRED_WIDTH (32)
	) write_mstr_internal (
		.clk                       (clock_clk),                                      //   input,    width = 1,             Clock.clk
		.reset                     (~reset_n_reset_n),                               //   input,    width = 1,       Clock_reset.reset
		.master_address            (mm_write_address),                               //  output,   width = 32, Data_Write_Master.address
		.master_write              (mm_write_write),                                 //  output,    width = 1,                  .write
		.master_byteenable         (mm_write_byteenable),                            //  output,    width = 4,                  .byteenable
		.master_writedata          (mm_write_writedata),                             //  output,   width = 32,                  .writedata
		.master_waitrequest        (mm_write_waitrequest),                           //   input,    width = 1,                  .waitrequest
		.master_burstcount         (mm_write_burstcount),                            //  output,    width = 2,                  .burstcount
		.snk_data                  (read_mstr_internal_data_source_data),            //   input,   width = 32,         Data_Sink.data
		.snk_valid                 (read_mstr_internal_data_source_valid),           //   input,    width = 1,                  .valid
		.snk_ready                 (read_mstr_internal_data_source_ready),           //  output,    width = 1,                  .ready
		.snk_command_data          (dispatcher_internal_write_command_source_data),  //   input,  width = 256,      Command_Sink.data
		.snk_command_valid         (dispatcher_internal_write_command_source_valid), //   input,    width = 1,                  .valid
		.snk_command_ready         (dispatcher_internal_write_command_source_ready), //  output,    width = 1,                  .ready
		.src_response_data         (write_mstr_internal_response_source_data),       //  output,  width = 256,   Response_Source.data
		.src_response_valid        (write_mstr_internal_response_source_valid),      //  output,    width = 1,                  .valid
		.src_response_ready        (write_mstr_internal_response_source_ready),      //   input,    width = 1,                  .ready
		.master_response           (2'b00),                                          // (terminated),                                 
		.master_writeresponsevalid (1'b0),                                           // (terminated),                                 
		.snk_sop                   (1'b0),                                           // (terminated),                                 
		.snk_eop                   (1'b0),                                           // (terminated),                                 
		.snk_empty                 (2'b00),                                          // (terminated),                                 
		.snk_error                 (8'b00000000)                                     // (terminated),                                 
	);

endmodule
