// NonDPR.sv

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module NonDPR (
		input  wire  clk_clk,     //   clk.clk
		input  wire  reset_reset  // reset.reset
	);

	wire         clock_in_out_clk_clk;                                    // clock_in:out_clk -> [data_mem:clk, master_0:clk_clk, mm_interconnect_0:clock_in_out_clk_clk, mm_interconnect_1:clock_in_out_clk_clk, mm_interconnect_2:clock_in_out_clk_clk, npu_system_0:clk, reset_in:clk, rst_controller:clk, weight_mem:clk]
	wire         reset_in_out_reset_reset;                                // reset_in:out_reset -> [master_0:clk_reset_reset, mm_interconnect_1:master_0_master_translator_reset_reset_bridge_in_reset_reset]
	wire  [31:0] npu_system_0_act_readdata;                               // mm_interconnect_0:npu_system_0_act_readdata -> npu_system_0:avm_act_readdata
	wire         npu_system_0_act_waitrequest;                            // mm_interconnect_0:npu_system_0_act_waitrequest -> npu_system_0:avm_act_waitreq
	wire  [31:0] npu_system_0_act_address;                                // npu_system_0:avm_act_address -> mm_interconnect_0:npu_system_0_act_address
	wire         npu_system_0_act_read;                                   // npu_system_0:avm_act_read -> mm_interconnect_0:npu_system_0_act_read
	wire         mm_interconnect_0_data_mem_s2_chipselect;                // mm_interconnect_0:data_mem_s2_chipselect -> data_mem:chipselect2
	wire  [31:0] mm_interconnect_0_data_mem_s2_readdata;                  // data_mem:readdata2 -> mm_interconnect_0:data_mem_s2_readdata
	wire   [9:0] mm_interconnect_0_data_mem_s2_address;                   // mm_interconnect_0:data_mem_s2_address -> data_mem:address2
	wire   [3:0] mm_interconnect_0_data_mem_s2_byteenable;                // mm_interconnect_0:data_mem_s2_byteenable -> data_mem:byteenable2
	wire         mm_interconnect_0_data_mem_s2_write;                     // mm_interconnect_0:data_mem_s2_write -> data_mem:write2
	wire  [31:0] mm_interconnect_0_data_mem_s2_writedata;                 // mm_interconnect_0:data_mem_s2_writedata -> data_mem:writedata2
	wire         mm_interconnect_0_data_mem_s2_clken;                     // mm_interconnect_0:data_mem_s2_clken -> data_mem:clken2
	wire  [31:0] master_0_master_readdata;                                // mm_interconnect_1:master_0_master_readdata -> master_0:master_readdata
	wire         master_0_master_waitrequest;                             // mm_interconnect_1:master_0_master_waitrequest -> master_0:master_waitrequest
	wire  [31:0] master_0_master_address;                                 // master_0:master_address -> mm_interconnect_1:master_0_master_address
	wire         master_0_master_read;                                    // master_0:master_read -> mm_interconnect_1:master_0_master_read
	wire   [3:0] master_0_master_byteenable;                              // master_0:master_byteenable -> mm_interconnect_1:master_0_master_byteenable
	wire         master_0_master_readdatavalid;                           // mm_interconnect_1:master_0_master_readdatavalid -> master_0:master_readdatavalid
	wire         master_0_master_write;                                   // master_0:master_write -> mm_interconnect_1:master_0_master_write
	wire  [31:0] master_0_master_writedata;                               // master_0:master_writedata -> mm_interconnect_1:master_0_master_writedata
	wire  [31:0] mm_interconnect_1_npu_system_0_avalon_slave_0_readdata;  // npu_system_0:avs_readdata -> mm_interconnect_1:npu_system_0_avalon_slave_0_readdata
	wire   [3:0] mm_interconnect_1_npu_system_0_avalon_slave_0_address;   // mm_interconnect_1:npu_system_0_avalon_slave_0_address -> npu_system_0:avs_address
	wire         mm_interconnect_1_npu_system_0_avalon_slave_0_read;      // mm_interconnect_1:npu_system_0_avalon_slave_0_read -> npu_system_0:avs_read
	wire         mm_interconnect_1_npu_system_0_avalon_slave_0_write;     // mm_interconnect_1:npu_system_0_avalon_slave_0_write -> npu_system_0:avs_write
	wire  [31:0] mm_interconnect_1_npu_system_0_avalon_slave_0_writedata; // mm_interconnect_1:npu_system_0_avalon_slave_0_writedata -> npu_system_0:avs_writedata
	wire         mm_interconnect_1_data_mem_s1_chipselect;                // mm_interconnect_1:data_mem_s1_chipselect -> data_mem:chipselect
	wire  [31:0] mm_interconnect_1_data_mem_s1_readdata;                  // data_mem:readdata -> mm_interconnect_1:data_mem_s1_readdata
	wire   [9:0] mm_interconnect_1_data_mem_s1_address;                   // mm_interconnect_1:data_mem_s1_address -> data_mem:address
	wire   [3:0] mm_interconnect_1_data_mem_s1_byteenable;                // mm_interconnect_1:data_mem_s1_byteenable -> data_mem:byteenable
	wire         mm_interconnect_1_data_mem_s1_write;                     // mm_interconnect_1:data_mem_s1_write -> data_mem:write
	wire  [31:0] mm_interconnect_1_data_mem_s1_writedata;                 // mm_interconnect_1:data_mem_s1_writedata -> data_mem:writedata
	wire         mm_interconnect_1_data_mem_s1_clken;                     // mm_interconnect_1:data_mem_s1_clken -> data_mem:clken
	wire         mm_interconnect_1_weight_mem_s1_chipselect;              // mm_interconnect_1:weight_mem_s1_chipselect -> weight_mem:chipselect
	wire  [31:0] mm_interconnect_1_weight_mem_s1_readdata;                // weight_mem:readdata -> mm_interconnect_1:weight_mem_s1_readdata
	wire   [9:0] mm_interconnect_1_weight_mem_s1_address;                 // mm_interconnect_1:weight_mem_s1_address -> weight_mem:address
	wire   [3:0] mm_interconnect_1_weight_mem_s1_byteenable;              // mm_interconnect_1:weight_mem_s1_byteenable -> weight_mem:byteenable
	wire         mm_interconnect_1_weight_mem_s1_write;                   // mm_interconnect_1:weight_mem_s1_write -> weight_mem:write
	wire  [31:0] mm_interconnect_1_weight_mem_s1_writedata;               // mm_interconnect_1:weight_mem_s1_writedata -> weight_mem:writedata
	wire         mm_interconnect_1_weight_mem_s1_clken;                   // mm_interconnect_1:weight_mem_s1_clken -> weight_mem:clken
	wire  [31:0] npu_system_0_weight_readdata;                            // mm_interconnect_2:npu_system_0_weight_readdata -> npu_system_0:avm_weight_readdata
	wire         npu_system_0_weight_waitrequest;                         // mm_interconnect_2:npu_system_0_weight_waitrequest -> npu_system_0:avm_weight_waitreq
	wire  [31:0] npu_system_0_weight_address;                             // npu_system_0:avm_weight_address -> mm_interconnect_2:npu_system_0_weight_address
	wire         npu_system_0_weight_read;                                // npu_system_0:avm_weight_read -> mm_interconnect_2:npu_system_0_weight_read
	wire         mm_interconnect_2_weight_mem_s2_chipselect;              // mm_interconnect_2:weight_mem_s2_chipselect -> weight_mem:chipselect2
	wire  [31:0] mm_interconnect_2_weight_mem_s2_readdata;                // weight_mem:readdata2 -> mm_interconnect_2:weight_mem_s2_readdata
	wire   [9:0] mm_interconnect_2_weight_mem_s2_address;                 // mm_interconnect_2:weight_mem_s2_address -> weight_mem:address2
	wire   [3:0] mm_interconnect_2_weight_mem_s2_byteenable;              // mm_interconnect_2:weight_mem_s2_byteenable -> weight_mem:byteenable2
	wire         mm_interconnect_2_weight_mem_s2_write;                   // mm_interconnect_2:weight_mem_s2_write -> weight_mem:write2
	wire  [31:0] mm_interconnect_2_weight_mem_s2_writedata;               // mm_interconnect_2:weight_mem_s2_writedata -> weight_mem:writedata2
	wire         mm_interconnect_2_weight_mem_s2_clken;                   // mm_interconnect_2:weight_mem_s2_clken -> weight_mem:clken2
	wire         rst_controller_reset_out_reset;                          // rst_controller:reset_out -> [data_mem:reset, mm_interconnect_0:npu_system_0_reset_reset_bridge_in_reset_reset, mm_interconnect_1:npu_system_0_reset_reset_bridge_in_reset_reset, mm_interconnect_2:npu_system_0_reset_reset_bridge_in_reset_reset, npu_system_0:reset_n, rst_translator:in_reset, weight_mem:reset]
	wire         rst_controller_reset_out_reset_req;                      // rst_controller:reset_req -> [data_mem:reset_req, rst_translator:reset_req_in, weight_mem:reset_req]
	wire         master_0_master_reset_reset;                             // master_0:master_reset_reset -> rst_controller:reset_in0

	PR_Test_Top_clock_in clock_in (
		.in_clk  (clk_clk),              //   input,  width = 1,  in_clk.clk
		.out_clk (clock_in_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	data_mem data_mem (
		.clk         (clock_in_out_clk_clk),                     //   input,   width = 1,   clk1.clk
		.address     (mm_interconnect_1_data_mem_s1_address),    //   input,  width = 10,     s1.address
		.clken       (mm_interconnect_1_data_mem_s1_clken),      //   input,   width = 1,       .clken
		.chipselect  (mm_interconnect_1_data_mem_s1_chipselect), //   input,   width = 1,       .chipselect
		.write       (mm_interconnect_1_data_mem_s1_write),      //   input,   width = 1,       .write
		.readdata    (mm_interconnect_1_data_mem_s1_readdata),   //  output,  width = 32,       .readdata
		.writedata   (mm_interconnect_1_data_mem_s1_writedata),  //   input,  width = 32,       .writedata
		.byteenable  (mm_interconnect_1_data_mem_s1_byteenable), //   input,   width = 4,       .byteenable
		.reset       (rst_controller_reset_out_reset),           //   input,   width = 1, reset1.reset
		.reset_req   (rst_controller_reset_out_reset_req),       //   input,   width = 1,       .reset_req
		.address2    (mm_interconnect_0_data_mem_s2_address),    //   input,  width = 10,     s2.address
		.chipselect2 (mm_interconnect_0_data_mem_s2_chipselect), //   input,   width = 1,       .chipselect
		.clken2      (mm_interconnect_0_data_mem_s2_clken),      //   input,   width = 1,       .clken
		.write2      (mm_interconnect_0_data_mem_s2_write),      //   input,   width = 1,       .write
		.readdata2   (mm_interconnect_0_data_mem_s2_readdata),   //  output,  width = 32,       .readdata
		.writedata2  (mm_interconnect_0_data_mem_s2_writedata),  //   input,  width = 32,       .writedata
		.byteenable2 (mm_interconnect_0_data_mem_s2_byteenable)  //   input,   width = 4,       .byteenable
	);

	NonDPR_master_0 master_0 (
		.clk_clk              (clock_in_out_clk_clk),          //   input,   width = 1,          clk.clk
		.clk_reset_reset      (reset_in_out_reset_reset),      //   input,   width = 1,    clk_reset.reset
		.master_reset_reset   (master_0_master_reset_reset),   //  output,   width = 1, master_reset.reset
		.master_address       (master_0_master_address),       //  output,  width = 32,       master.address
		.master_readdata      (master_0_master_readdata),      //   input,  width = 32,             .readdata
		.master_read          (master_0_master_read),          //  output,   width = 1,             .read
		.master_write         (master_0_master_write),         //  output,   width = 1,             .write
		.master_writedata     (master_0_master_writedata),     //  output,  width = 32,             .writedata
		.master_waitrequest   (master_0_master_waitrequest),   //   input,   width = 1,             .waitrequest
		.master_readdatavalid (master_0_master_readdatavalid), //   input,   width = 1,             .readdatavalid
		.master_byteenable    (master_0_master_byteenable)     //  output,   width = 4,             .byteenable
	);

	NonDPR_npu_system_0 npu_system_0 (
		.clk                 (clock_in_out_clk_clk),                                    //   input,   width = 1,          clock.clk
		.reset_n             (~rst_controller_reset_out_reset),                         //   input,   width = 1,          reset.reset_n
		.avs_address         (mm_interconnect_1_npu_system_0_avalon_slave_0_address),   //   input,   width = 4, avalon_slave_0.address
		.avs_write           (mm_interconnect_1_npu_system_0_avalon_slave_0_write),     //   input,   width = 1,               .write
		.avs_writedata       (mm_interconnect_1_npu_system_0_avalon_slave_0_writedata), //   input,  width = 32,               .writedata
		.avs_read            (mm_interconnect_1_npu_system_0_avalon_slave_0_read),      //   input,   width = 1,               .read
		.avs_readdata        (mm_interconnect_1_npu_system_0_avalon_slave_0_readdata),  //  output,  width = 32,               .readdata
		.avm_act_address     (npu_system_0_act_address),                                //  output,  width = 32,            act.address
		.avm_act_read        (npu_system_0_act_read),                                   //  output,   width = 1,               .read
		.avm_act_readdata    (npu_system_0_act_readdata),                               //   input,  width = 32,               .readdata
		.avm_act_waitreq     (npu_system_0_act_waitrequest),                            //   input,   width = 1,               .waitrequest
		.avm_weight_address  (npu_system_0_weight_address),                             //  output,  width = 32,         weight.address
		.avm_weight_read     (npu_system_0_weight_read),                                //  output,   width = 1,               .read
		.avm_weight_readdata (npu_system_0_weight_readdata),                            //   input,  width = 32,               .readdata
		.avm_weight_waitreq  (npu_system_0_weight_waitrequest)                          //   input,   width = 1,               .waitrequest
	);

	PR_Test_Top_reset_in reset_in (
		.clk       (clock_in_out_clk_clk),     //   input,  width = 1,       clk.clk
		.in_reset  (reset_reset),              //   input,  width = 1,  in_reset.reset
		.out_reset (reset_in_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	weight_mem weight_mem (
		.clk         (clock_in_out_clk_clk),                       //   input,   width = 1,   clk1.clk
		.address     (mm_interconnect_1_weight_mem_s1_address),    //   input,  width = 10,     s1.address
		.clken       (mm_interconnect_1_weight_mem_s1_clken),      //   input,   width = 1,       .clken
		.chipselect  (mm_interconnect_1_weight_mem_s1_chipselect), //   input,   width = 1,       .chipselect
		.write       (mm_interconnect_1_weight_mem_s1_write),      //   input,   width = 1,       .write
		.readdata    (mm_interconnect_1_weight_mem_s1_readdata),   //  output,  width = 32,       .readdata
		.writedata   (mm_interconnect_1_weight_mem_s1_writedata),  //   input,  width = 32,       .writedata
		.byteenable  (mm_interconnect_1_weight_mem_s1_byteenable), //   input,   width = 4,       .byteenable
		.reset       (rst_controller_reset_out_reset),             //   input,   width = 1, reset1.reset
		.reset_req   (rst_controller_reset_out_reset_req),         //   input,   width = 1,       .reset_req
		.address2    (mm_interconnect_2_weight_mem_s2_address),    //   input,  width = 10,     s2.address
		.chipselect2 (mm_interconnect_2_weight_mem_s2_chipselect), //   input,   width = 1,       .chipselect
		.clken2      (mm_interconnect_2_weight_mem_s2_clken),      //   input,   width = 1,       .clken
		.write2      (mm_interconnect_2_weight_mem_s2_write),      //   input,   width = 1,       .write
		.readdata2   (mm_interconnect_2_weight_mem_s2_readdata),   //  output,  width = 32,       .readdata
		.writedata2  (mm_interconnect_2_weight_mem_s2_writedata),  //   input,  width = 32,       .writedata
		.byteenable2 (mm_interconnect_2_weight_mem_s2_byteenable)  //   input,   width = 4,       .byteenable
	);

	NonDPR_altera_mm_interconnect_1920_mcc4doa mm_interconnect_0 (
		.npu_system_0_act_address                       (npu_system_0_act_address),                 //   input,  width = 32,                         npu_system_0_act.address
		.npu_system_0_act_waitrequest                   (npu_system_0_act_waitrequest),             //  output,   width = 1,                                         .waitrequest
		.npu_system_0_act_read                          (npu_system_0_act_read),                    //   input,   width = 1,                                         .read
		.npu_system_0_act_readdata                      (npu_system_0_act_readdata),                //  output,  width = 32,                                         .readdata
		.data_mem_s2_address                            (mm_interconnect_0_data_mem_s2_address),    //  output,  width = 10,                              data_mem_s2.address
		.data_mem_s2_write                              (mm_interconnect_0_data_mem_s2_write),      //  output,   width = 1,                                         .write
		.data_mem_s2_readdata                           (mm_interconnect_0_data_mem_s2_readdata),   //   input,  width = 32,                                         .readdata
		.data_mem_s2_writedata                          (mm_interconnect_0_data_mem_s2_writedata),  //  output,  width = 32,                                         .writedata
		.data_mem_s2_byteenable                         (mm_interconnect_0_data_mem_s2_byteenable), //  output,   width = 4,                                         .byteenable
		.data_mem_s2_chipselect                         (mm_interconnect_0_data_mem_s2_chipselect), //  output,   width = 1,                                         .chipselect
		.data_mem_s2_clken                              (mm_interconnect_0_data_mem_s2_clken),      //  output,   width = 1,                                         .clken
		.npu_system_0_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),           //   input,   width = 1, npu_system_0_reset_reset_bridge_in_reset.reset
		.clock_in_out_clk_clk                           (clock_in_out_clk_clk)                      //   input,   width = 1,                         clock_in_out_clk.clk
	);

	NonDPR_altera_mm_interconnect_1920_mxt6g6y mm_interconnect_1 (
		.master_0_master_address                                      (master_0_master_address),                                 //   input,  width = 32,                                        master_0_master.address
		.master_0_master_waitrequest                                  (master_0_master_waitrequest),                             //  output,   width = 1,                                                       .waitrequest
		.master_0_master_byteenable                                   (master_0_master_byteenable),                              //   input,   width = 4,                                                       .byteenable
		.master_0_master_read                                         (master_0_master_read),                                    //   input,   width = 1,                                                       .read
		.master_0_master_readdata                                     (master_0_master_readdata),                                //  output,  width = 32,                                                       .readdata
		.master_0_master_readdatavalid                                (master_0_master_readdatavalid),                           //  output,   width = 1,                                                       .readdatavalid
		.master_0_master_write                                        (master_0_master_write),                                   //   input,   width = 1,                                                       .write
		.master_0_master_writedata                                    (master_0_master_writedata),                               //   input,  width = 32,                                                       .writedata
		.npu_system_0_avalon_slave_0_address                          (mm_interconnect_1_npu_system_0_avalon_slave_0_address),   //  output,   width = 4,                            npu_system_0_avalon_slave_0.address
		.npu_system_0_avalon_slave_0_write                            (mm_interconnect_1_npu_system_0_avalon_slave_0_write),     //  output,   width = 1,                                                       .write
		.npu_system_0_avalon_slave_0_read                             (mm_interconnect_1_npu_system_0_avalon_slave_0_read),      //  output,   width = 1,                                                       .read
		.npu_system_0_avalon_slave_0_readdata                         (mm_interconnect_1_npu_system_0_avalon_slave_0_readdata),  //   input,  width = 32,                                                       .readdata
		.npu_system_0_avalon_slave_0_writedata                        (mm_interconnect_1_npu_system_0_avalon_slave_0_writedata), //  output,  width = 32,                                                       .writedata
		.data_mem_s1_address                                          (mm_interconnect_1_data_mem_s1_address),                   //  output,  width = 10,                                            data_mem_s1.address
		.data_mem_s1_write                                            (mm_interconnect_1_data_mem_s1_write),                     //  output,   width = 1,                                                       .write
		.data_mem_s1_readdata                                         (mm_interconnect_1_data_mem_s1_readdata),                  //   input,  width = 32,                                                       .readdata
		.data_mem_s1_writedata                                        (mm_interconnect_1_data_mem_s1_writedata),                 //  output,  width = 32,                                                       .writedata
		.data_mem_s1_byteenable                                       (mm_interconnect_1_data_mem_s1_byteenable),                //  output,   width = 4,                                                       .byteenable
		.data_mem_s1_chipselect                                       (mm_interconnect_1_data_mem_s1_chipselect),                //  output,   width = 1,                                                       .chipselect
		.data_mem_s1_clken                                            (mm_interconnect_1_data_mem_s1_clken),                     //  output,   width = 1,                                                       .clken
		.weight_mem_s1_address                                        (mm_interconnect_1_weight_mem_s1_address),                 //  output,  width = 10,                                          weight_mem_s1.address
		.weight_mem_s1_write                                          (mm_interconnect_1_weight_mem_s1_write),                   //  output,   width = 1,                                                       .write
		.weight_mem_s1_readdata                                       (mm_interconnect_1_weight_mem_s1_readdata),                //   input,  width = 32,                                                       .readdata
		.weight_mem_s1_writedata                                      (mm_interconnect_1_weight_mem_s1_writedata),               //  output,  width = 32,                                                       .writedata
		.weight_mem_s1_byteenable                                     (mm_interconnect_1_weight_mem_s1_byteenable),              //  output,   width = 4,                                                       .byteenable
		.weight_mem_s1_chipselect                                     (mm_interconnect_1_weight_mem_s1_chipselect),              //  output,   width = 1,                                                       .chipselect
		.weight_mem_s1_clken                                          (mm_interconnect_1_weight_mem_s1_clken),                   //  output,   width = 1,                                                       .clken
		.npu_system_0_reset_reset_bridge_in_reset_reset               (rst_controller_reset_out_reset),                          //   input,   width = 1,               npu_system_0_reset_reset_bridge_in_reset.reset
		.master_0_master_translator_reset_reset_bridge_in_reset_reset (reset_in_out_reset_reset),                                //   input,   width = 1, master_0_master_translator_reset_reset_bridge_in_reset.reset
		.clock_in_out_clk_clk                                         (clock_in_out_clk_clk)                                     //   input,   width = 1,                                       clock_in_out_clk.clk
	);

	NonDPR_altera_mm_interconnect_1920_zn5rfly mm_interconnect_2 (
		.npu_system_0_weight_address                    (npu_system_0_weight_address),                //   input,  width = 32,                      npu_system_0_weight.address
		.npu_system_0_weight_waitrequest                (npu_system_0_weight_waitrequest),            //  output,   width = 1,                                         .waitrequest
		.npu_system_0_weight_read                       (npu_system_0_weight_read),                   //   input,   width = 1,                                         .read
		.npu_system_0_weight_readdata                   (npu_system_0_weight_readdata),               //  output,  width = 32,                                         .readdata
		.weight_mem_s2_address                          (mm_interconnect_2_weight_mem_s2_address),    //  output,  width = 10,                            weight_mem_s2.address
		.weight_mem_s2_write                            (mm_interconnect_2_weight_mem_s2_write),      //  output,   width = 1,                                         .write
		.weight_mem_s2_readdata                         (mm_interconnect_2_weight_mem_s2_readdata),   //   input,  width = 32,                                         .readdata
		.weight_mem_s2_writedata                        (mm_interconnect_2_weight_mem_s2_writedata),  //  output,  width = 32,                                         .writedata
		.weight_mem_s2_byteenable                       (mm_interconnect_2_weight_mem_s2_byteenable), //  output,   width = 4,                                         .byteenable
		.weight_mem_s2_chipselect                       (mm_interconnect_2_weight_mem_s2_chipselect), //  output,   width = 1,                                         .chipselect
		.weight_mem_s2_clken                            (mm_interconnect_2_weight_mem_s2_clken),      //  output,   width = 1,                                         .clken
		.npu_system_0_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),             //   input,   width = 1, npu_system_0_reset_reset_bridge_in_reset.reset
		.clock_in_out_clk_clk                           (clock_in_out_clk_clk)                        //   input,   width = 1,                         clock_in_out_clk.clk
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (master_0_master_reset_reset),        //   input,  width = 1, reset_in0.reset
		.clk            (clock_in_out_clk_clk),               //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     //  output,  width = 1, reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //  output,  width = 1,          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated),                       
		.reset_in1      (1'b0),                               // (terminated),                       
		.reset_req_in1  (1'b0),                               // (terminated),                       
		.reset_in2      (1'b0),                               // (terminated),                       
		.reset_req_in2  (1'b0),                               // (terminated),                       
		.reset_in3      (1'b0),                               // (terminated),                       
		.reset_req_in3  (1'b0),                               // (terminated),                       
		.reset_in4      (1'b0),                               // (terminated),                       
		.reset_req_in4  (1'b0),                               // (terminated),                       
		.reset_in5      (1'b0),                               // (terminated),                       
		.reset_req_in5  (1'b0),                               // (terminated),                       
		.reset_in6      (1'b0),                               // (terminated),                       
		.reset_req_in6  (1'b0),                               // (terminated),                       
		.reset_in7      (1'b0),                               // (terminated),                       
		.reset_req_in7  (1'b0),                               // (terminated),                       
		.reset_in8      (1'b0),                               // (terminated),                       
		.reset_req_in8  (1'b0),                               // (terminated),                       
		.reset_in9      (1'b0),                               // (terminated),                       
		.reset_req_in9  (1'b0),                               // (terminated),                       
		.reset_in10     (1'b0),                               // (terminated),                       
		.reset_req_in10 (1'b0),                               // (terminated),                       
		.reset_in11     (1'b0),                               // (terminated),                       
		.reset_req_in11 (1'b0),                               // (terminated),                       
		.reset_in12     (1'b0),                               // (terminated),                       
		.reset_req_in12 (1'b0),                               // (terminated),                       
		.reset_in13     (1'b0),                               // (terminated),                       
		.reset_req_in13 (1'b0),                               // (terminated),                       
		.reset_in14     (1'b0),                               // (terminated),                       
		.reset_req_in14 (1'b0),                               // (terminated),                       
		.reset_in15     (1'b0),                               // (terminated),                       
		.reset_req_in15 (1'b0)                                // (terminated),                       
	);

endmodule
