-- SDRAM_altera_mm_interconnect_1920_mnl7iba.vhd

-- This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 24.1 115

library IEEE;
library altera_merlin_master_translator_192;
library altera_merlin_slave_translator_191;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity SDRAM_altera_mm_interconnect_1920_mnl7iba is
	port (
		col_if_to_ioaux_address                       : in  std_logic_vector(29 downto 0) := (others => '0'); --                         col_if_to_ioaux.address
		col_if_to_ioaux_waitrequest                   : out std_logic;                                        --                                        .waitrequest
		col_if_to_ioaux_burstcount                    : in  std_logic_vector(0 downto 0)  := (others => '0'); --                                        .burstcount
		col_if_to_ioaux_byteenable                    : in  std_logic_vector(3 downto 0)  := (others => '0'); --                                        .byteenable
		col_if_to_ioaux_read                          : in  std_logic                     := '0';             --                                        .read
		col_if_to_ioaux_readdata                      : out std_logic_vector(31 downto 0);                    --                                        .readdata
		col_if_to_ioaux_readdatavalid                 : out std_logic;                                        --                                        .readdatavalid
		col_if_to_ioaux_write                         : in  std_logic                     := '0';             --                                        .write
		col_if_to_ioaux_writedata                     : in  std_logic_vector(31 downto 0) := (others => '0'); --                                        .writedata
		col_if_to_ioaux_debugaccess                   : in  std_logic                     := '0';             --                                        .debugaccess
		arch_cal_debug_address                        : out std_logic_vector(23 downto 0);                    --                          arch_cal_debug.address
		arch_cal_debug_write                          : out std_logic;                                        --                                        .write
		arch_cal_debug_read                           : out std_logic;                                        --                                        .read
		arch_cal_debug_readdata                       : in  std_logic_vector(31 downto 0) := (others => '0'); --                                        .readdata
		arch_cal_debug_writedata                      : out std_logic_vector(31 downto 0);                    --                                        .writedata
		arch_cal_debug_byteenable                     : out std_logic_vector(3 downto 0);                     --                                        .byteenable
		arch_cal_debug_readdatavalid                  : in  std_logic                     := '0';             --                                        .readdatavalid
		arch_cal_debug_waitrequest                    : in  std_logic                     := '0';             --                                        .waitrequest
		col_if_avl_rst_in_reset_bridge_in_reset_reset : in  std_logic                     := '0';             -- col_if_avl_rst_in_reset_bridge_in_reset.reset,        Reset Input
		arch_cal_master_clk_clk                       : in  std_logic                     := '0'              --                     arch_cal_master_clk.clk,          Clock Input
	);
end entity SDRAM_altera_mm_interconnect_1920_mnl7iba;

architecture rtl of SDRAM_altera_mm_interconnect_1920_mnl7iba is
	component SDRAM_altera_merlin_master_translator_192_lykd4la_cmp is
		generic (
			AV_ADDRESS_W                : integer := 32;
			AV_DATA_W                   : integer := 32;
			AV_BURSTCOUNT_W             : integer := 4;
			AV_BYTEENABLE_W             : integer := 4;
			UAV_ADDRESS_W               : integer := 38;
			UAV_BURSTCOUNT_W            : integer := 10;
			USE_READ                    : integer := 1;
			USE_WRITE                   : integer := 1;
			USE_BEGINBURSTTRANSFER      : integer := 0;
			USE_BEGINTRANSFER           : integer := 0;
			USE_CHIPSELECT              : integer := 0;
			USE_BURSTCOUNT              : integer := 1;
			USE_READDATAVALID           : integer := 1;
			USE_WAITREQUEST             : integer := 1;
			USE_READRESPONSE            : integer := 0;
			USE_WRITERESPONSE           : integer := 0;
			AV_SYMBOLS_PER_WORD         : integer := 4;
			AV_ADDRESS_SYMBOLS          : integer := 0;
			AV_BURSTCOUNT_SYMBOLS       : integer := 0;
			AV_CONSTANT_BURST_BEHAVIOR  : integer := 0;
			UAV_CONSTANT_BURST_BEHAVIOR : integer := 0;
			AV_LINEWRAPBURSTS           : integer := 0;
			AV_REGISTERINCOMINGSIGNALS  : integer := 0;
			SYNC_RESET                  : integer := 0;
			WAITREQUEST_ALLOWANCE       : integer := 0;
			USE_OUTPUTENABLE            : integer := 0
		);
		port (
			clk                    : in  std_logic                     := 'X';             -- clk
			reset                  : in  std_logic                     := 'X';             -- reset
			uav_address            : out std_logic_vector(31 downto 0);                    -- address
			uav_burstcount         : out std_logic_vector(2 downto 0);                     -- burstcount
			uav_read               : out std_logic;                                        -- read
			uav_write              : out std_logic;                                        -- write
			uav_waitrequest        : in  std_logic                     := 'X';             -- waitrequest
			uav_readdatavalid      : in  std_logic                     := 'X';             -- readdatavalid
			uav_byteenable         : out std_logic_vector(3 downto 0);                     -- byteenable
			uav_readdata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			uav_writedata          : out std_logic_vector(31 downto 0);                    -- writedata
			uav_lock               : out std_logic;                                        -- lock
			uav_debugaccess        : out std_logic;                                        -- debugaccess
			av_address             : in  std_logic_vector(29 downto 0) := (others => 'X'); -- address
			av_waitrequest         : out std_logic;                                        -- waitrequest
			av_burstcount          : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- burstcount
			av_byteenable          : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			av_read                : in  std_logic                     := 'X';             -- read
			av_readdata            : out std_logic_vector(31 downto 0);                    -- readdata
			av_readdatavalid       : out std_logic;                                        -- readdatavalid
			av_write               : in  std_logic                     := 'X';             -- write
			av_writedata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			av_debugaccess         : in  std_logic                     := 'X';             -- debugaccess
			av_beginbursttransfer  : in  std_logic                     := 'X';             -- beginbursttransfer
			av_begintransfer       : in  std_logic                     := 'X';             -- begintransfer
			av_chipselect          : in  std_logic                     := 'X';             -- chipselect
			av_lock                : in  std_logic                     := 'X';             -- lock
			uav_outputenable       : in  std_logic                     := 'X';             -- outputenable
			uav_clken              : out std_logic;                                        -- clken
			av_clken               : in  std_logic                     := 'X';             -- clken
			uav_response           : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- response
			av_response            : out std_logic_vector(1 downto 0);                     -- response
			uav_writeresponsevalid : in  std_logic                     := 'X';             -- writeresponsevalid
			av_writeresponsevalid  : out std_logic                                         -- writeresponsevalid
		);
	end component SDRAM_altera_merlin_master_translator_192_lykd4la_cmp;

	component SDRAM_altera_merlin_slave_translator_191_x56fcki_cmp is
		generic (
			AV_ADDRESS_W                   : integer := 30;
			AV_DATA_W                      : integer := 32;
			UAV_DATA_W                     : integer := 32;
			AV_BURSTCOUNT_W                : integer := 4;
			AV_BYTEENABLE_W                : integer := 4;
			UAV_BYTEENABLE_W               : integer := 4;
			UAV_ADDRESS_W                  : integer := 32;
			UAV_BURSTCOUNT_W               : integer := 4;
			AV_READLATENCY                 : integer := 0;
			USE_READDATAVALID              : integer := 1;
			USE_WAITREQUEST                : integer := 1;
			USE_UAV_CLKEN                  : integer := 0;
			USE_READRESPONSE               : integer := 0;
			USE_WRITERESPONSE              : integer := 0;
			AV_SYMBOLS_PER_WORD            : integer := 4;
			AV_ADDRESS_SYMBOLS             : integer := 0;
			AV_BURSTCOUNT_SYMBOLS          : integer := 0;
			AV_CONSTANT_BURST_BEHAVIOR     : integer := 0;
			UAV_CONSTANT_BURST_BEHAVIOR    : integer := 0;
			AV_REQUIRE_UNALIGNED_ADDRESSES : integer := 0;
			CHIPSELECT_THROUGH_READLATENCY : integer := 0;
			AV_READ_WAIT_CYCLES            : integer := 0;
			AV_WRITE_WAIT_CYCLES           : integer := 0;
			AV_SETUP_WAIT_CYCLES           : integer := 0;
			AV_DATA_HOLD_CYCLES            : integer := 0;
			WAITREQUEST_ALLOWANCE          : integer := 0;
			SYNC_RESET                     : integer := 0
		);
		port (
			clk                    : in  std_logic                     := 'X';             -- clk
			reset                  : in  std_logic                     := 'X';             -- reset
			uav_address            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- address
			uav_burstcount         : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- burstcount
			uav_read               : in  std_logic                     := 'X';             -- read
			uav_write              : in  std_logic                     := 'X';             -- write
			uav_waitrequest        : out std_logic;                                        -- waitrequest
			uav_readdatavalid      : out std_logic;                                        -- readdatavalid
			uav_byteenable         : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			uav_readdata           : out std_logic_vector(31 downto 0);                    -- readdata
			uav_writedata          : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			uav_lock               : in  std_logic                     := 'X';             -- lock
			uav_debugaccess        : in  std_logic                     := 'X';             -- debugaccess
			av_address             : out std_logic_vector(23 downto 0);                    -- address
			av_write               : out std_logic;                                        -- write
			av_read                : out std_logic;                                        -- read
			av_readdata            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			av_writedata           : out std_logic_vector(31 downto 0);                    -- writedata
			av_byteenable          : out std_logic_vector(3 downto 0);                     -- byteenable
			av_readdatavalid       : in  std_logic                     := 'X';             -- readdatavalid
			av_waitrequest         : in  std_logic                     := 'X';             -- waitrequest
			av_begintransfer       : out std_logic;                                        -- begintransfer
			av_beginbursttransfer  : out std_logic;                                        -- beginbursttransfer
			av_burstcount          : out std_logic_vector(0 downto 0);                     -- burstcount
			av_writebyteenable     : out std_logic_vector(3 downto 0);                     -- writebyteenable
			av_lock                : out std_logic;                                        -- lock
			av_chipselect          : out std_logic;                                        -- chipselect
			av_clken               : out std_logic;                                        -- clken
			uav_clken              : in  std_logic                     := 'X';             -- clken
			av_debugaccess         : out std_logic;                                        -- debugaccess
			av_outputenable        : out std_logic;                                        -- outputenable
			uav_response           : out std_logic_vector(1 downto 0);                     -- response
			av_response            : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- response
			uav_writeresponsevalid : out std_logic;                                        -- writeresponsevalid
			av_writeresponsevalid  : in  std_logic                     := 'X'              -- writeresponsevalid
		);
	end component SDRAM_altera_merlin_slave_translator_191_x56fcki_cmp;

	signal col_if_to_ioaux_translator_avalon_universal_master_0_waitrequest   : std_logic;                     -- arch_cal_debug_translator:uav_waitrequest -> col_if_to_ioaux_translator:uav_waitrequest
	signal col_if_to_ioaux_translator_avalon_universal_master_0_readdata      : std_logic_vector(31 downto 0); -- arch_cal_debug_translator:uav_readdata -> col_if_to_ioaux_translator:uav_readdata
	signal col_if_to_ioaux_translator_avalon_universal_master_0_debugaccess   : std_logic;                     -- col_if_to_ioaux_translator:uav_debugaccess -> arch_cal_debug_translator:uav_debugaccess
	signal col_if_to_ioaux_translator_avalon_universal_master_0_address       : std_logic_vector(31 downto 0); -- col_if_to_ioaux_translator:uav_address -> arch_cal_debug_translator:uav_address
	signal col_if_to_ioaux_translator_avalon_universal_master_0_read          : std_logic;                     -- col_if_to_ioaux_translator:uav_read -> arch_cal_debug_translator:uav_read
	signal col_if_to_ioaux_translator_avalon_universal_master_0_byteenable    : std_logic_vector(3 downto 0);  -- col_if_to_ioaux_translator:uav_byteenable -> arch_cal_debug_translator:uav_byteenable
	signal col_if_to_ioaux_translator_avalon_universal_master_0_readdatavalid : std_logic;                     -- arch_cal_debug_translator:uav_readdatavalid -> col_if_to_ioaux_translator:uav_readdatavalid
	signal col_if_to_ioaux_translator_avalon_universal_master_0_lock          : std_logic;                     -- col_if_to_ioaux_translator:uav_lock -> arch_cal_debug_translator:uav_lock
	signal col_if_to_ioaux_translator_avalon_universal_master_0_write         : std_logic;                     -- col_if_to_ioaux_translator:uav_write -> arch_cal_debug_translator:uav_write
	signal col_if_to_ioaux_translator_avalon_universal_master_0_writedata     : std_logic_vector(31 downto 0); -- col_if_to_ioaux_translator:uav_writedata -> arch_cal_debug_translator:uav_writedata
	signal col_if_to_ioaux_translator_avalon_universal_master_0_burstcount    : std_logic_vector(2 downto 0);  -- col_if_to_ioaux_translator:uav_burstcount -> arch_cal_debug_translator:uav_burstcount

	for col_if_to_ioaux_translator : SDRAM_altera_merlin_master_translator_192_lykd4la_cmp
		use entity altera_merlin_master_translator_192.SDRAM_altera_merlin_master_translator_192_lykd4la;
	for arch_cal_debug_translator : SDRAM_altera_merlin_slave_translator_191_x56fcki_cmp
		use entity altera_merlin_slave_translator_191.SDRAM_altera_merlin_slave_translator_191_x56fcki;
begin

	col_if_to_ioaux_translator : component SDRAM_altera_merlin_master_translator_192_lykd4la_cmp
		generic map (
			AV_ADDRESS_W                => 30,
			AV_DATA_W                   => 32,
			AV_BURSTCOUNT_W             => 1,
			AV_BYTEENABLE_W             => 4,
			UAV_ADDRESS_W               => 32,
			UAV_BURSTCOUNT_W            => 3,
			USE_READ                    => 1,
			USE_WRITE                   => 1,
			USE_BEGINBURSTTRANSFER      => 0,
			USE_BEGINTRANSFER           => 0,
			USE_CHIPSELECT              => 0,
			USE_BURSTCOUNT              => 1,
			USE_READDATAVALID           => 1,
			USE_WAITREQUEST             => 1,
			USE_READRESPONSE            => 0,
			USE_WRITERESPONSE           => 0,
			AV_SYMBOLS_PER_WORD         => 4,
			AV_ADDRESS_SYMBOLS          => 0,
			AV_BURSTCOUNT_SYMBOLS       => 0,
			AV_CONSTANT_BURST_BEHAVIOR  => 0,
			UAV_CONSTANT_BURST_BEHAVIOR => 0,
			AV_LINEWRAPBURSTS           => 0,
			AV_REGISTERINCOMINGSIGNALS  => 0,
			SYNC_RESET                  => 0,
			WAITREQUEST_ALLOWANCE       => 0,
			USE_OUTPUTENABLE            => 0
		)
		port map (
			clk                    => arch_cal_master_clk_clk,                                            --                       clk.clk
			reset                  => col_if_avl_rst_in_reset_bridge_in_reset_reset,                      --                     reset.reset
			uav_address            => col_if_to_ioaux_translator_avalon_universal_master_0_address,       -- avalon_universal_master_0.address
			uav_burstcount         => col_if_to_ioaux_translator_avalon_universal_master_0_burstcount,    --                          .burstcount
			uav_read               => col_if_to_ioaux_translator_avalon_universal_master_0_read,          --                          .read
			uav_write              => col_if_to_ioaux_translator_avalon_universal_master_0_write,         --                          .write
			uav_waitrequest        => col_if_to_ioaux_translator_avalon_universal_master_0_waitrequest,   --                          .waitrequest
			uav_readdatavalid      => col_if_to_ioaux_translator_avalon_universal_master_0_readdatavalid, --                          .readdatavalid
			uav_byteenable         => col_if_to_ioaux_translator_avalon_universal_master_0_byteenable,    --                          .byteenable
			uav_readdata           => col_if_to_ioaux_translator_avalon_universal_master_0_readdata,      --                          .readdata
			uav_writedata          => col_if_to_ioaux_translator_avalon_universal_master_0_writedata,     --                          .writedata
			uav_lock               => col_if_to_ioaux_translator_avalon_universal_master_0_lock,          --                          .lock
			uav_debugaccess        => col_if_to_ioaux_translator_avalon_universal_master_0_debugaccess,   --                          .debugaccess
			av_address             => col_if_to_ioaux_address,                                            --      avalon_anti_master_0.address
			av_waitrequest         => col_if_to_ioaux_waitrequest,                                        --                          .waitrequest
			av_burstcount          => col_if_to_ioaux_burstcount,                                         --                          .burstcount
			av_byteenable          => col_if_to_ioaux_byteenable,                                         --                          .byteenable
			av_read                => col_if_to_ioaux_read,                                               --                          .read
			av_readdata            => col_if_to_ioaux_readdata,                                           --                          .readdata
			av_readdatavalid       => col_if_to_ioaux_readdatavalid,                                      --                          .readdatavalid
			av_write               => col_if_to_ioaux_write,                                              --                          .write
			av_writedata           => col_if_to_ioaux_writedata,                                          --                          .writedata
			av_debugaccess         => col_if_to_ioaux_debugaccess,                                        --                          .debugaccess
			av_beginbursttransfer  => '0',                                                                --               (terminated)
			av_begintransfer       => '0',                                                                --               (terminated)
			av_chipselect          => '0',                                                                --               (terminated)
			av_lock                => '0',                                                                --               (terminated)
			uav_outputenable       => '0',                                                                --               (terminated)
			uav_clken              => open,                                                               --               (terminated)
			av_clken               => '1',                                                                --               (terminated)
			uav_response           => "00",                                                               --               (terminated)
			av_response            => open,                                                               --               (terminated)
			uav_writeresponsevalid => '0',                                                                --               (terminated)
			av_writeresponsevalid  => open                                                                --               (terminated)
		);

	arch_cal_debug_translator : component SDRAM_altera_merlin_slave_translator_191_x56fcki_cmp
		generic map (
			AV_ADDRESS_W                   => 24,
			AV_DATA_W                      => 32,
			UAV_DATA_W                     => 32,
			AV_BURSTCOUNT_W                => 1,
			AV_BYTEENABLE_W                => 4,
			UAV_BYTEENABLE_W               => 4,
			UAV_ADDRESS_W                  => 32,
			UAV_BURSTCOUNT_W               => 3,
			AV_READLATENCY                 => 0,
			USE_READDATAVALID              => 1,
			USE_WAITREQUEST                => 1,
			USE_UAV_CLKEN                  => 0,
			USE_READRESPONSE               => 0,
			USE_WRITERESPONSE              => 0,
			AV_SYMBOLS_PER_WORD            => 4,
			AV_ADDRESS_SYMBOLS             => 1,
			AV_BURSTCOUNT_SYMBOLS          => 0,
			AV_CONSTANT_BURST_BEHAVIOR     => 0,
			UAV_CONSTANT_BURST_BEHAVIOR    => 0,
			AV_REQUIRE_UNALIGNED_ADDRESSES => 0,
			CHIPSELECT_THROUGH_READLATENCY => 0,
			AV_READ_WAIT_CYCLES            => 1,
			AV_WRITE_WAIT_CYCLES           => 0,
			AV_SETUP_WAIT_CYCLES           => 0,
			AV_DATA_HOLD_CYCLES            => 0,
			WAITREQUEST_ALLOWANCE          => 0,
			SYNC_RESET                     => 0
		)
		port map (
			clk                    => arch_cal_master_clk_clk,                                            --                      clk.clk
			reset                  => col_if_avl_rst_in_reset_bridge_in_reset_reset,                      --                    reset.reset
			uav_address            => col_if_to_ioaux_translator_avalon_universal_master_0_address,       -- avalon_universal_slave_0.address
			uav_burstcount         => col_if_to_ioaux_translator_avalon_universal_master_0_burstcount,    --                         .burstcount
			uav_read               => col_if_to_ioaux_translator_avalon_universal_master_0_read,          --                         .read
			uav_write              => col_if_to_ioaux_translator_avalon_universal_master_0_write,         --                         .write
			uav_waitrequest        => col_if_to_ioaux_translator_avalon_universal_master_0_waitrequest,   --                         .waitrequest
			uav_readdatavalid      => col_if_to_ioaux_translator_avalon_universal_master_0_readdatavalid, --                         .readdatavalid
			uav_byteenable         => col_if_to_ioaux_translator_avalon_universal_master_0_byteenable,    --                         .byteenable
			uav_readdata           => col_if_to_ioaux_translator_avalon_universal_master_0_readdata,      --                         .readdata
			uav_writedata          => col_if_to_ioaux_translator_avalon_universal_master_0_writedata,     --                         .writedata
			uav_lock               => col_if_to_ioaux_translator_avalon_universal_master_0_lock,          --                         .lock
			uav_debugaccess        => col_if_to_ioaux_translator_avalon_universal_master_0_debugaccess,   --                         .debugaccess
			av_address             => arch_cal_debug_address,                                             --      avalon_anti_slave_0.address
			av_write               => arch_cal_debug_write,                                               --                         .write
			av_read                => arch_cal_debug_read,                                                --                         .read
			av_readdata            => arch_cal_debug_readdata,                                            --                         .readdata
			av_writedata           => arch_cal_debug_writedata,                                           --                         .writedata
			av_byteenable          => arch_cal_debug_byteenable,                                          --                         .byteenable
			av_readdatavalid       => arch_cal_debug_readdatavalid,                                       --                         .readdatavalid
			av_waitrequest         => arch_cal_debug_waitrequest,                                         --                         .waitrequest
			av_begintransfer       => open,                                                               --              (terminated)
			av_beginbursttransfer  => open,                                                               --              (terminated)
			av_burstcount          => open,                                                               --              (terminated)
			av_writebyteenable     => open,                                                               --              (terminated)
			av_lock                => open,                                                               --              (terminated)
			av_chipselect          => open,                                                               --              (terminated)
			av_clken               => open,                                                               --              (terminated)
			uav_clken              => '0',                                                                --              (terminated)
			av_debugaccess         => open,                                                               --              (terminated)
			av_outputenable        => open,                                                               --              (terminated)
			uav_response           => open,                                                               --              (terminated)
			av_response            => "00",                                                               --              (terminated)
			uav_writeresponsevalid => open,                                                               --              (terminated)
			av_writeresponsevalid  => '0'                                                                 --              (terminated)
		);

end architecture rtl; -- of SDRAM_altera_mm_interconnect_1920_mnl7iba
