// WeightBuffer1.v

// Generated using ACDS version 24.1 115

`timescale 1 ps / 1 ps
module WeightBuffer1 (
		input  wire [15:0] data_a,    //    data_a.datain_a,  Data input to port A of the memory.The data port is required for all RAM operation modes:SINGLE_PORT,DUAL_PORT,BIDIR_DUAL_PORT,QUAD_PORT
		output wire [15:0] q_a,       //       q_a.dataout_a, Data output from port A of the memory. The data port is required if the operation modes parameter is set to any of the following values:SINGLE_PORT,BIDIR_DUAL_PORT,QUAD_PORT,ROM
		input  wire [15:0] data_b,    //    data_b.datain_b,  Data input to port B of the memory.The data_b port is required if the operation_mode parameter is set to BIDIR_DUAL_PORT and QUAD_PORT
		output wire [15:0] q_b,       //       q_b.dataout_b, Data output from port B of the memory. The q_b port is required if the operation_mode is set to the following values:DUAL_PORT,BIDIR_DUAL_PORT,QUAD_PORT
		input  wire [9:0]  address_a, // address_a.address_a, Address input to port A of the memory.The address_a signal is required for all operation modes.
		input  wire [9:0]  address_b, // address_b.address_b, Address input to port B of the memory.The address_b port is required if the operation_mode parameter is set to the following values:DUAL_PORT,BIDIR_DUAL_PORT,QUAD_PORT
		input  wire        wren_a,    //    wren_a.wren_a,    Write enable input for address_a port.The wren_a signal is required all RAM operation modes:SINGLE_PORT,DUAL_PORT,BIDIR_DUAL_PORT,QUAD_PORT
		input  wire        wren_b,    //    wren_b.wren_b,    Write enable input for address_b port.The wren_b port is required if operation_mode is set to BIDIR_DUAL_PORT and QUAD_PORT.
		input  wire        clock,     //     clock.clk,       Memory clock, refer to user guide for specific details
		input  wire        freeze,    //    freeze.freeze
		input  wire        enable,    //    enable.enable
		input  wire        aclr       //      aclr.reset,     Asynchronously clear the output ports. The asynchronous clear effect on the registered ports can be controlled through their corresponding clear parameter, such as outdata_aclr_a and outdata_aclr_b.
	);

	WeightBuffer1_ram_2port_2041_3stzzty ram_2port_0 (
		.data_a    (data_a),    //   input,  width = 16,    data_a.datain_a
		.q_a       (q_a),       //  output,  width = 16,       q_a.dataout_a
		.data_b    (data_b),    //   input,  width = 16,    data_b.datain_b
		.q_b       (q_b),       //  output,  width = 16,       q_b.dataout_b
		.address_a (address_a), //   input,  width = 10, address_a.address_a
		.address_b (address_b), //   input,  width = 10, address_b.address_b
		.wren_a    (wren_a),    //   input,   width = 1,    wren_a.wren_a
		.wren_b    (wren_b),    //   input,   width = 1,    wren_b.wren_b
		.clock     (clock),     //   input,   width = 1,     clock.clk
		.freeze    (freeze),    //   input,   width = 1,    freeze.freeze
		.enable    (enable),    //   input,   width = 1,    enable.enable
		.aclr      (aclr)       //   input,   width = 1,      aclr.reset
	);

endmodule
