-- PR_Test_Top_altera_mm_interconnect_1920_lu2bh2a.vhd

-- This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 24.1 115

library IEEE;
library altera_merlin_master_translator_192;
library altera_merlin_slave_translator_191;
library altera_merlin_master_agent_1922;
library altera_merlin_slave_agent_1921;
library altera_avalon_sc_fifo_1932;
library altera_merlin_router_1921;
library altera_merlin_burst_adapter_1932;
library altera_merlin_demultiplexer_1921;
library altera_merlin_multiplexer_1922;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity PR_Test_Top_altera_mm_interconnect_1920_lu2bh2a is
	port (
		msgdma_pr_mm_write_address                       : in  std_logic_vector(31 downto 0) := (others => '0'); --                         msgdma_pr_mm_write.address
		msgdma_pr_mm_write_waitrequest                   : out std_logic;                                        --                                           .waitrequest
		msgdma_pr_mm_write_burstcount                    : in  std_logic_vector(1 downto 0)  := (others => '0'); --                                           .burstcount
		msgdma_pr_mm_write_byteenable                    : in  std_logic_vector(3 downto 0)  := (others => '0'); --                                           .byteenable
		msgdma_pr_mm_write_write                         : in  std_logic                     := '0';             --                                           .write
		msgdma_pr_mm_write_writedata                     : in  std_logic_vector(31 downto 0) := (others => '0'); --                                           .writedata
		pr_controller_avmm_slave_address                 : out std_logic_vector(3 downto 0);                     --                   pr_controller_avmm_slave.address
		pr_controller_avmm_slave_write                   : out std_logic;                                        --                                           .write
		pr_controller_avmm_slave_read                    : out std_logic;                                        --                                           .read
		pr_controller_avmm_slave_readdata                : in  std_logic_vector(31 downto 0) := (others => '0'); --                                           .readdata
		pr_controller_avmm_slave_writedata               : out std_logic_vector(31 downto 0);                    --                                           .writedata
		pr_controller_avmm_slave_waitrequest             : in  std_logic                     := '0';             --                                           .waitrequest
		pr_controller_nreset_reset_bridge_in_reset_reset : in  std_logic                     := '0';             -- pr_controller_nreset_reset_bridge_in_reset.reset,      Reset Input
		clock_in_out_clk_clk                             : in  std_logic                     := '0'              --                           clock_in_out_clk.clk,        Clock Input
	);
end entity PR_Test_Top_altera_mm_interconnect_1920_lu2bh2a;

architecture rtl of PR_Test_Top_altera_mm_interconnect_1920_lu2bh2a is
	component PR_Test_Top_altera_merlin_master_translator_192_lykd4la_cmp is
		generic (
			AV_ADDRESS_W                : integer := 32;
			AV_DATA_W                   : integer := 32;
			AV_BURSTCOUNT_W             : integer := 4;
			AV_BYTEENABLE_W             : integer := 4;
			UAV_ADDRESS_W               : integer := 38;
			UAV_BURSTCOUNT_W            : integer := 10;
			USE_READ                    : integer := 1;
			USE_WRITE                   : integer := 1;
			USE_BEGINBURSTTRANSFER      : integer := 0;
			USE_BEGINTRANSFER           : integer := 0;
			USE_CHIPSELECT              : integer := 0;
			USE_BURSTCOUNT              : integer := 1;
			USE_READDATAVALID           : integer := 1;
			USE_WAITREQUEST             : integer := 1;
			USE_READRESPONSE            : integer := 0;
			USE_WRITERESPONSE           : integer := 0;
			AV_SYMBOLS_PER_WORD         : integer := 4;
			AV_ADDRESS_SYMBOLS          : integer := 0;
			AV_BURSTCOUNT_SYMBOLS       : integer := 0;
			AV_CONSTANT_BURST_BEHAVIOR  : integer := 0;
			UAV_CONSTANT_BURST_BEHAVIOR : integer := 0;
			AV_LINEWRAPBURSTS           : integer := 0;
			AV_REGISTERINCOMINGSIGNALS  : integer := 0;
			SYNC_RESET                  : integer := 0;
			WAITREQUEST_ALLOWANCE       : integer := 0;
			USE_OUTPUTENABLE            : integer := 0
		);
		port (
			clk                    : in  std_logic                     := 'X';             -- clk
			reset                  : in  std_logic                     := 'X';             -- reset
			uav_address            : out std_logic_vector(31 downto 0);                    -- address
			uav_burstcount         : out std_logic_vector(3 downto 0);                     -- burstcount
			uav_read               : out std_logic;                                        -- read
			uav_write              : out std_logic;                                        -- write
			uav_waitrequest        : in  std_logic                     := 'X';             -- waitrequest
			uav_readdatavalid      : in  std_logic                     := 'X';             -- readdatavalid
			uav_byteenable         : out std_logic_vector(3 downto 0);                     -- byteenable
			uav_readdata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			uav_writedata          : out std_logic_vector(31 downto 0);                    -- writedata
			uav_lock               : out std_logic;                                        -- lock
			uav_debugaccess        : out std_logic;                                        -- debugaccess
			av_address             : in  std_logic_vector(31 downto 0) := (others => 'X'); -- address
			av_waitrequest         : out std_logic;                                        -- waitrequest
			av_burstcount          : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- burstcount
			av_byteenable          : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			av_write               : in  std_logic                     := 'X';             -- write
			av_writedata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			av_beginbursttransfer  : in  std_logic                     := 'X';             -- beginbursttransfer
			av_begintransfer       : in  std_logic                     := 'X';             -- begintransfer
			av_chipselect          : in  std_logic                     := 'X';             -- chipselect
			av_read                : in  std_logic                     := 'X';             -- read
			av_readdata            : out std_logic_vector(31 downto 0);                    -- readdata
			av_readdatavalid       : out std_logic;                                        -- readdatavalid
			av_lock                : in  std_logic                     := 'X';             -- lock
			av_debugaccess         : in  std_logic                     := 'X';             -- debugaccess
			uav_outputenable       : in  std_logic                     := 'X';             -- outputenable
			uav_clken              : out std_logic;                                        -- clken
			av_clken               : in  std_logic                     := 'X';             -- clken
			uav_response           : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- response
			av_response            : out std_logic_vector(1 downto 0);                     -- response
			uav_writeresponsevalid : in  std_logic                     := 'X';             -- writeresponsevalid
			av_writeresponsevalid  : out std_logic                                         -- writeresponsevalid
		);
	end component PR_Test_Top_altera_merlin_master_translator_192_lykd4la_cmp;

	component PR_Test_Top_altera_merlin_slave_translator_191_x56fcki_cmp is
		generic (
			AV_ADDRESS_W                   : integer := 30;
			AV_DATA_W                      : integer := 32;
			UAV_DATA_W                     : integer := 32;
			AV_BURSTCOUNT_W                : integer := 4;
			AV_BYTEENABLE_W                : integer := 4;
			UAV_BYTEENABLE_W               : integer := 4;
			UAV_ADDRESS_W                  : integer := 32;
			UAV_BURSTCOUNT_W               : integer := 4;
			AV_READLATENCY                 : integer := 0;
			USE_READDATAVALID              : integer := 1;
			USE_WAITREQUEST                : integer := 1;
			USE_UAV_CLKEN                  : integer := 0;
			USE_READRESPONSE               : integer := 0;
			USE_WRITERESPONSE              : integer := 0;
			AV_SYMBOLS_PER_WORD            : integer := 4;
			AV_ADDRESS_SYMBOLS             : integer := 0;
			AV_BURSTCOUNT_SYMBOLS          : integer := 0;
			AV_CONSTANT_BURST_BEHAVIOR     : integer := 0;
			UAV_CONSTANT_BURST_BEHAVIOR    : integer := 0;
			AV_REQUIRE_UNALIGNED_ADDRESSES : integer := 0;
			CHIPSELECT_THROUGH_READLATENCY : integer := 0;
			AV_READ_WAIT_CYCLES            : integer := 0;
			AV_WRITE_WAIT_CYCLES           : integer := 0;
			AV_SETUP_WAIT_CYCLES           : integer := 0;
			AV_DATA_HOLD_CYCLES            : integer := 0;
			WAITREQUEST_ALLOWANCE          : integer := 0;
			SYNC_RESET                     : integer := 0
		);
		port (
			clk                    : in  std_logic                     := 'X';             -- clk
			reset                  : in  std_logic                     := 'X';             -- reset
			uav_address            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- address
			uav_burstcount         : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- burstcount
			uav_read               : in  std_logic                     := 'X';             -- read
			uav_write              : in  std_logic                     := 'X';             -- write
			uav_waitrequest        : out std_logic;                                        -- waitrequest
			uav_readdatavalid      : out std_logic;                                        -- readdatavalid
			uav_byteenable         : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			uav_readdata           : out std_logic_vector(31 downto 0);                    -- readdata
			uav_writedata          : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			uav_lock               : in  std_logic                     := 'X';             -- lock
			uav_debugaccess        : in  std_logic                     := 'X';             -- debugaccess
			av_address             : out std_logic_vector(3 downto 0);                     -- address
			av_write               : out std_logic;                                        -- write
			av_read                : out std_logic;                                        -- read
			av_readdata            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			av_writedata           : out std_logic_vector(31 downto 0);                    -- writedata
			av_waitrequest         : in  std_logic                     := 'X';             -- waitrequest
			av_begintransfer       : out std_logic;                                        -- begintransfer
			av_beginbursttransfer  : out std_logic;                                        -- beginbursttransfer
			av_burstcount          : out std_logic_vector(0 downto 0);                     -- burstcount
			av_byteenable          : out std_logic_vector(3 downto 0);                     -- byteenable
			av_readdatavalid       : in  std_logic                     := 'X';             -- readdatavalid
			av_writebyteenable     : out std_logic_vector(3 downto 0);                     -- writebyteenable
			av_lock                : out std_logic;                                        -- lock
			av_chipselect          : out std_logic;                                        -- chipselect
			av_clken               : out std_logic;                                        -- clken
			uav_clken              : in  std_logic                     := 'X';             -- clken
			av_debugaccess         : out std_logic;                                        -- debugaccess
			av_outputenable        : out std_logic;                                        -- outputenable
			uav_response           : out std_logic_vector(1 downto 0);                     -- response
			av_response            : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- response
			uav_writeresponsevalid : out std_logic;                                        -- writeresponsevalid
			av_writeresponsevalid  : in  std_logic                     := 'X'              -- writeresponsevalid
		);
	end component PR_Test_Top_altera_merlin_slave_translator_191_x56fcki_cmp;

	component PR_Test_Top_altera_merlin_master_agent_1922_fy3n5ti_cmp is
		generic (
			PKT_WUNIQUE               : integer := 125;
			PKT_DOMAIN_H              : integer := 124;
			PKT_DOMAIN_L              : integer := 123;
			PKT_SNOOP_H               : integer := 122;
			PKT_SNOOP_L               : integer := 119;
			PKT_BARRIER_H             : integer := 118;
			PKT_BARRIER_L             : integer := 117;
			PKT_ORI_BURST_SIZE_H      : integer := 116;
			PKT_ORI_BURST_SIZE_L      : integer := 114;
			PKT_RESPONSE_STATUS_H     : integer := 113;
			PKT_RESPONSE_STATUS_L     : integer := 112;
			PKT_QOS_H                 : integer := 111;
			PKT_QOS_L                 : integer := 108;
			PKT_DATA_SIDEBAND_H       : integer := 107;
			PKT_DATA_SIDEBAND_L       : integer := 100;
			PKT_ADDR_SIDEBAND_H       : integer := 99;
			PKT_ADDR_SIDEBAND_L       : integer := 95;
			PKT_BURST_TYPE_H          : integer := 94;
			PKT_BURST_TYPE_L          : integer := 93;
			PKT_CACHE_H               : integer := 92;
			PKT_CACHE_L               : integer := 89;
			PKT_THREAD_ID_H           : integer := 88;
			PKT_THREAD_ID_L           : integer := 87;
			PKT_BURST_SIZE_H          : integer := 86;
			PKT_BURST_SIZE_L          : integer := 84;
			PKT_TRANS_EXCLUSIVE       : integer := 83;
			PKT_TRANS_LOCK            : integer := 82;
			PKT_BEGIN_BURST           : integer := 81;
			PKT_PROTECTION_H          : integer := 80;
			PKT_PROTECTION_L          : integer := 80;
			PKT_BURSTWRAP_H           : integer := 79;
			PKT_BURSTWRAP_L           : integer := 77;
			PKT_BYTE_CNT_H            : integer := 76;
			PKT_BYTE_CNT_L            : integer := 74;
			PKT_ADDR_H                : integer := 73;
			PKT_ADDR_L                : integer := 42;
			PKT_TRANS_COMPRESSED_READ : integer := 41;
			PKT_TRANS_POSTED          : integer := 40;
			PKT_TRANS_WRITE           : integer := 39;
			PKT_TRANS_READ            : integer := 38;
			PKT_DATA_H                : integer := 37;
			PKT_DATA_L                : integer := 6;
			PKT_BYTEEN_H              : integer := 5;
			PKT_BYTEEN_L              : integer := 2;
			PKT_SRC_ID_H              : integer := 1;
			PKT_SRC_ID_L              : integer := 1;
			PKT_DEST_ID_H             : integer := 0;
			PKT_DEST_ID_L             : integer := 0;
			PKT_POISON_H              : integer := 126;
			PKT_POISON_L              : integer := 126;
			PKT_DATACHK_H             : integer := 127;
			PKT_DATACHK_L             : integer := 127;
			PKT_ADDRCHK_H             : integer := 128;
			PKT_ADDRCHK_L             : integer := 128;
			PKT_SAI_H                 : integer := 129;
			PKT_SAI_L                 : integer := 129;
			PKT_USER_DATA_H           : integer := 133;
			PKT_USER_DATA_L           : integer := 133;
			ST_DATA_W                 : integer := 126;
			ST_CHANNEL_W              : integer := 1;
			AV_BURSTCOUNT_W           : integer := 3;
			SUPPRESS_0_BYTEEN_RSP     : integer := 1;
			ID                        : integer := 1;
			BURSTWRAP_VALUE           : integer := 4;
			CACHE_VALUE               : integer := 0;
			SECURE_ACCESS_BIT         : integer := 1;
			USE_READRESPONSE          : integer := 0;
			USE_WRITERESPONSE         : integer := 0;
			DOMAIN_VALUE              : integer := 3;
			BARRIER_VALUE             : integer := 0;
			SNOOP_VALUE               : integer := 0;
			WUNIQUE_VALUE             : integer := 0;
			SYNC_RESET                : integer := 0;
			USE_PKT_DATACHK           : integer := 0;
			USE_PKT_ADDRCHK           : integer := 0;
			ROLE_BASED_USER           : integer := 0
		);
		port (
			clk                   : in  std_logic                      := 'X';             -- clk
			reset                 : in  std_logic                      := 'X';             -- reset
			av_address            : in  std_logic_vector(31 downto 0)  := (others => 'X'); -- address
			av_write              : in  std_logic                      := 'X';             -- write
			av_read               : in  std_logic                      := 'X';             -- read
			av_writedata          : in  std_logic_vector(31 downto 0)  := (others => 'X'); -- writedata
			av_readdata           : out std_logic_vector(31 downto 0);                     -- readdata
			av_waitrequest        : out std_logic;                                         -- waitrequest
			av_readdatavalid      : out std_logic;                                         -- readdatavalid
			av_byteenable         : in  std_logic_vector(3 downto 0)   := (others => 'X'); -- byteenable
			av_burstcount         : in  std_logic_vector(3 downto 0)   := (others => 'X'); -- burstcount
			av_debugaccess        : in  std_logic                      := 'X';             -- debugaccess
			av_lock               : in  std_logic                      := 'X';             -- lock
			cp_valid              : out std_logic;                                         -- valid
			cp_data               : out std_logic_vector(126 downto 0);                    -- data
			cp_startofpacket      : out std_logic;                                         -- startofpacket
			cp_endofpacket        : out std_logic;                                         -- endofpacket
			cp_ready              : in  std_logic                      := 'X';             -- ready
			rp_valid              : in  std_logic                      := 'X';             -- valid
			rp_data               : in  std_logic_vector(126 downto 0) := (others => 'X'); -- data
			rp_channel            : in  std_logic_vector(0 downto 0)   := (others => 'X'); -- channel
			rp_startofpacket      : in  std_logic                      := 'X';             -- startofpacket
			rp_endofpacket        : in  std_logic                      := 'X';             -- endofpacket
			rp_ready              : out std_logic;                                         -- ready
			av_response           : out std_logic_vector(1 downto 0);                      -- response
			av_writeresponsevalid : out std_logic                                          -- writeresponsevalid
		);
	end component PR_Test_Top_altera_merlin_master_agent_1922_fy3n5ti_cmp;

	component PR_Test_Top_altera_merlin_slave_agent_1921_b6r3djy_cmp is
		generic (
			PKT_ORI_BURST_SIZE_H      : integer := 90;
			PKT_ORI_BURST_SIZE_L      : integer := 88;
			PKT_RESPONSE_STATUS_H     : integer := 87;
			PKT_RESPONSE_STATUS_L     : integer := 86;
			PKT_BURST_SIZE_H          : integer := 85;
			PKT_BURST_SIZE_L          : integer := 83;
			PKT_TRANS_LOCK            : integer := 82;
			PKT_BEGIN_BURST           : integer := 81;
			PKT_PROTECTION_H          : integer := 80;
			PKT_PROTECTION_L          : integer := 80;
			PKT_BURSTWRAP_H           : integer := 79;
			PKT_BURSTWRAP_L           : integer := 77;
			PKT_BYTE_CNT_H            : integer := 76;
			PKT_BYTE_CNT_L            : integer := 74;
			PKT_ADDR_H                : integer := 73;
			PKT_ADDR_L                : integer := 42;
			PKT_TRANS_COMPRESSED_READ : integer := 41;
			PKT_TRANS_POSTED          : integer := 40;
			PKT_TRANS_WRITE           : integer := 39;
			PKT_TRANS_READ            : integer := 38;
			PKT_DATA_H                : integer := 37;
			PKT_DATA_L                : integer := 6;
			PKT_BYTEEN_H              : integer := 5;
			PKT_BYTEEN_L              : integer := 2;
			PKT_SRC_ID_H              : integer := 1;
			PKT_SRC_ID_L              : integer := 1;
			PKT_DEST_ID_H             : integer := 0;
			PKT_DEST_ID_L             : integer := 0;
			PKT_POISON_H              : integer := 92;
			PKT_POISON_L              : integer := 92;
			PKT_DATACHK_H             : integer := 97;
			PKT_DATACHK_L             : integer := 94;
			PKT_SAI_H                 : integer := 98;
			PKT_SAI_L                 : integer := 98;
			PKT_ADDRCHK_H             : integer := 99;
			PKT_ADDRCHK_L             : integer := 99;
			PKT_USER_DATA_H           : integer := 103;
			PKT_USER_DATA_L           : integer := 103;
			PKT_SYMBOL_W              : integer := 8;
			ST_CHANNEL_W              : integer := 8;
			ST_DATA_W                 : integer := 98;
			AVS_BURSTCOUNT_W          : integer := 4;
			SUPPRESS_0_BYTEEN_CMD     : integer := 1;
			USE_MEMORY_BLOCKS         : integer := 0;
			PREVENT_FIFO_OVERFLOW     : integer := 0;
			USE_READRESPONSE          : integer := 0;
			USE_WRITERESPONSE         : integer := 0;
			ECC_ENABLE                : integer := 0;
			SYNC_RESET                : integer := 0;
			USE_PKT_DATACHK           : integer := 0;
			ROLE_BASED_USER           : integer := 0
		);
		port (
			clk                     : in  std_logic                      := 'X';             -- clk
			reset                   : in  std_logic                      := 'X';             -- reset
			m0_address              : out std_logic_vector(31 downto 0);                     -- address
			m0_burstcount           : out std_logic_vector(2 downto 0);                      -- burstcount
			m0_byteenable           : out std_logic_vector(3 downto 0);                      -- byteenable
			m0_debugaccess          : out std_logic;                                         -- debugaccess
			m0_lock                 : out std_logic;                                         -- lock
			m0_readdata             : in  std_logic_vector(31 downto 0)  := (others => 'X'); -- readdata
			m0_readdatavalid        : in  std_logic                      := 'X';             -- readdatavalid
			m0_read                 : out std_logic;                                         -- read
			m0_waitrequest          : in  std_logic                      := 'X';             -- waitrequest
			m0_writedata            : out std_logic_vector(31 downto 0);                     -- writedata
			m0_write                : out std_logic;                                         -- write
			rp_endofpacket          : out std_logic;                                         -- endofpacket
			rp_ready                : in  std_logic                      := 'X';             -- ready
			rp_valid                : out std_logic;                                         -- valid
			rp_data                 : out std_logic_vector(126 downto 0);                    -- data
			rp_startofpacket        : out std_logic;                                         -- startofpacket
			cp_ready                : out std_logic;                                         -- ready
			cp_valid                : in  std_logic                      := 'X';             -- valid
			cp_data                 : in  std_logic_vector(126 downto 0) := (others => 'X'); -- data
			cp_startofpacket        : in  std_logic                      := 'X';             -- startofpacket
			cp_endofpacket          : in  std_logic                      := 'X';             -- endofpacket
			cp_channel              : in  std_logic_vector(0 downto 0)   := (others => 'X'); -- channel
			rf_sink_ready           : out std_logic;                                         -- ready
			rf_sink_valid           : in  std_logic                      := 'X';             -- valid
			rf_sink_startofpacket   : in  std_logic                      := 'X';             -- startofpacket
			rf_sink_endofpacket     : in  std_logic                      := 'X';             -- endofpacket
			rf_sink_data            : in  std_logic_vector(127 downto 0) := (others => 'X'); -- data
			rf_source_ready         : in  std_logic                      := 'X';             -- ready
			rf_source_valid         : out std_logic;                                         -- valid
			rf_source_startofpacket : out std_logic;                                         -- startofpacket
			rf_source_endofpacket   : out std_logic;                                         -- endofpacket
			rf_source_data          : out std_logic_vector(127 downto 0);                    -- data
			rdata_fifo_sink_ready   : out std_logic;                                         -- ready
			rdata_fifo_sink_valid   : in  std_logic                      := 'X';             -- valid
			rdata_fifo_sink_data    : in  std_logic_vector(33 downto 0)  := (others => 'X'); -- data
			rdata_fifo_src_ready    : in  std_logic                      := 'X';             -- ready
			rdata_fifo_src_valid    : out std_logic;                                         -- valid
			rdata_fifo_src_data     : out std_logic_vector(33 downto 0);                     -- data
			m0_response             : in  std_logic_vector(1 downto 0)   := (others => 'X'); -- response
			m0_writeresponsevalid   : in  std_logic                      := 'X';             -- writeresponsevalid
			rdata_fifo_sink_error   : in  std_logic                      := 'X'              -- error
		);
	end component PR_Test_Top_altera_merlin_slave_agent_1921_b6r3djy_cmp;

	component PR_Test_Top_altera_avalon_sc_fifo_1932_5j7ufsq_cmp is
		generic (
			SYMBOLS_PER_BEAT    : integer := 1;
			BITS_PER_SYMBOL     : integer := 8;
			FIFO_DEPTH          : integer := 16;
			CHANNEL_WIDTH       : integer := 0;
			ERROR_WIDTH         : integer := 0;
			USE_PACKETS         : integer := 0;
			USE_FILL_LEVEL      : integer := 0;
			EMPTY_LATENCY       : integer := 3;
			USE_MEMORY_BLOCKS   : integer := 1;
			USE_STORE_FORWARD   : integer := 0;
			USE_ALMOST_FULL_IF  : integer := 0;
			USE_ALMOST_EMPTY_IF : integer := 0;
			EMPTY_WIDTH         : integer := 1;
			MEM_TYPE            : string  := "M20K";
			SYNC_RESET          : integer := 0
		);
		port (
			clk               : in  std_logic                      := 'X';             -- clk
			reset             : in  std_logic                      := 'X';             -- reset
			in_data           : in  std_logic_vector(127 downto 0) := (others => 'X'); -- data
			in_valid          : in  std_logic                      := 'X';             -- valid
			in_ready          : out std_logic;                                         -- ready
			in_startofpacket  : in  std_logic                      := 'X';             -- startofpacket
			in_endofpacket    : in  std_logic                      := 'X';             -- endofpacket
			out_data          : out std_logic_vector(127 downto 0);                    -- data
			out_valid         : out std_logic;                                         -- valid
			out_ready         : in  std_logic                      := 'X';             -- ready
			out_startofpacket : out std_logic;                                         -- startofpacket
			out_endofpacket   : out std_logic;                                         -- endofpacket
			csr_address       : in  std_logic_vector(1 downto 0)   := (others => 'X'); -- address
			csr_read          : in  std_logic                      := 'X';             -- read
			csr_write         : in  std_logic                      := 'X';             -- write
			csr_readdata      : out std_logic_vector(31 downto 0);                     -- readdata
			csr_writedata     : in  std_logic_vector(31 downto 0)  := (others => 'X'); -- writedata
			almost_full_data  : out std_logic;                                         -- data
			almost_empty_data : out std_logic;                                         -- data
			in_empty          : in  std_logic_vector(0 downto 0)   := (others => 'X'); -- empty
			out_empty         : out std_logic_vector(0 downto 0);                      -- empty
			in_error          : in  std_logic_vector(0 downto 0)   := (others => 'X'); -- error
			out_error         : out std_logic_vector(0 downto 0);                      -- error
			in_channel        : in  std_logic_vector(0 downto 0)   := (others => 'X'); -- channel
			out_channel       : out std_logic_vector(0 downto 0)                       -- channel
		);
	end component PR_Test_Top_altera_avalon_sc_fifo_1932_5j7ufsq_cmp;

	component PR_Test_Top_altera_merlin_router_1921_pfltgpa_cmp is
		port (
			sink_ready         : out std_logic;                                         -- ready
			sink_valid         : in  std_logic                      := 'X';             -- valid
			sink_data          : in  std_logic_vector(126 downto 0) := (others => 'X'); -- data
			sink_startofpacket : in  std_logic                      := 'X';             -- startofpacket
			sink_endofpacket   : in  std_logic                      := 'X';             -- endofpacket
			clk                : in  std_logic                      := 'X';             -- clk
			reset              : in  std_logic                      := 'X';             -- reset
			src_ready          : in  std_logic                      := 'X';             -- ready
			src_valid          : out std_logic;                                         -- valid
			src_data           : out std_logic_vector(126 downto 0);                    -- data
			src_channel        : out std_logic_vector(0 downto 0);                      -- channel
			src_startofpacket  : out std_logic;                                         -- startofpacket
			src_endofpacket    : out std_logic                                          -- endofpacket
		);
	end component PR_Test_Top_altera_merlin_router_1921_pfltgpa_cmp;

	component PR_Test_Top_altera_merlin_router_1921_e4osxtq_cmp is
		port (
			sink_ready         : out std_logic;                                         -- ready
			sink_valid         : in  std_logic                      := 'X';             -- valid
			sink_data          : in  std_logic_vector(126 downto 0) := (others => 'X'); -- data
			sink_startofpacket : in  std_logic                      := 'X';             -- startofpacket
			sink_endofpacket   : in  std_logic                      := 'X';             -- endofpacket
			clk                : in  std_logic                      := 'X';             -- clk
			reset              : in  std_logic                      := 'X';             -- reset
			src_ready          : in  std_logic                      := 'X';             -- ready
			src_valid          : out std_logic;                                         -- valid
			src_data           : out std_logic_vector(126 downto 0);                    -- data
			src_channel        : out std_logic_vector(0 downto 0);                      -- channel
			src_startofpacket  : out std_logic;                                         -- startofpacket
			src_endofpacket    : out std_logic                                          -- endofpacket
		);
	end component PR_Test_Top_altera_merlin_router_1921_e4osxtq_cmp;

	component PR_Test_Top_altera_merlin_burst_adapter_1932_4owamsy_cmp is
		generic (
			PKT_ADDR_H                : integer := 79;
			PKT_ADDR_L                : integer := 48;
			PKT_BEGIN_BURST           : integer := 81;
			PKT_BYTE_CNT_H            : integer := 5;
			PKT_BYTE_CNT_L            : integer := 0;
			PKT_BYTEEN_H              : integer := 83;
			PKT_BYTEEN_L              : integer := 80;
			PKT_BURST_SIZE_H          : integer := 86;
			PKT_BURST_SIZE_L          : integer := 84;
			PKT_BURST_TYPE_H          : integer := 88;
			PKT_BURST_TYPE_L          : integer := 87;
			PKT_BURSTWRAP_H           : integer := 11;
			PKT_BURSTWRAP_L           : integer := 6;
			PKT_SAI_H                 : integer := 89;
			PKT_SAI_L                 : integer := 89;
			ROLE_BASED_USER           : integer := 0;
			PKT_TRANS_COMPRESSED_READ : integer := 14;
			PKT_TRANS_WRITE           : integer := 13;
			PKT_TRANS_READ            : integer := 12;
			OUT_NARROW_SIZE           : integer := 0;
			IN_NARROW_SIZE            : integer := 0;
			OUT_FIXED                 : integer := 0;
			OUT_COMPLETE_WRAP         : integer := 0;
			PKT_EOP_OOO               : integer := 89;
			PKT_SOP_OOO               : integer := 90;
			ENABLE_OOO                : integer := 0;
			ST_DATA_W                 : integer := 89;
			ST_CHANNEL_W              : integer := 8;
			OUT_BYTE_CNT_H            : integer := 5;
			OUT_BURSTWRAP_H           : integer := 11;
			COMPRESSED_READ_SUPPORT   : integer := 1;
			BYTEENABLE_SYNTHESIS      : integer := 0;
			PIPE_INPUTS               : integer := 0;
			NO_WRAP_SUPPORT           : integer := 0;
			INCOMPLETE_WRAP_SUPPORT   : integer := 1;
			BURSTWRAP_CONST_MASK      : integer := 0;
			BURSTWRAP_CONST_VALUE     : integer := 2147483647;
			ADAPTER_VERSION           : string  := "13.1";
			SYNC_RESET                : integer := 0
		);
		port (
			clk                   : in  std_logic                      := 'X';             -- clk
			reset                 : in  std_logic                      := 'X';             -- reset
			sink0_valid           : in  std_logic                      := 'X';             -- valid
			sink0_data            : in  std_logic_vector(126 downto 0) := (others => 'X'); -- data
			sink0_channel         : in  std_logic_vector(0 downto 0)   := (others => 'X'); -- channel
			sink0_startofpacket   : in  std_logic                      := 'X';             -- startofpacket
			sink0_endofpacket     : in  std_logic                      := 'X';             -- endofpacket
			sink0_ready           : out std_logic;                                         -- ready
			source0_valid         : out std_logic;                                         -- valid
			source0_data          : out std_logic_vector(126 downto 0);                    -- data
			source0_channel       : out std_logic_vector(0 downto 0);                      -- channel
			source0_startofpacket : out std_logic;                                         -- startofpacket
			source0_endofpacket   : out std_logic;                                         -- endofpacket
			source0_ready         : in  std_logic                      := 'X'              -- ready
		);
	end component PR_Test_Top_altera_merlin_burst_adapter_1932_4owamsy_cmp;

	component PR_Test_Top_altera_merlin_demultiplexer_1921_4bpriii_cmp is
		port (
			clk                : in  std_logic                      := 'X';             -- clk
			reset              : in  std_logic                      := 'X';             -- reset
			sink_ready         : out std_logic;                                         -- ready
			sink_channel       : in  std_logic_vector(0 downto 0)   := (others => 'X'); -- channel
			sink_data          : in  std_logic_vector(126 downto 0) := (others => 'X'); -- data
			sink_startofpacket : in  std_logic                      := 'X';             -- startofpacket
			sink_endofpacket   : in  std_logic                      := 'X';             -- endofpacket
			sink_valid         : in  std_logic_vector(0 downto 0)   := (others => 'X'); -- valid
			src0_ready         : in  std_logic                      := 'X';             -- ready
			src0_valid         : out std_logic;                                         -- valid
			src0_data          : out std_logic_vector(126 downto 0);                    -- data
			src0_channel       : out std_logic_vector(0 downto 0);                      -- channel
			src0_startofpacket : out std_logic;                                         -- startofpacket
			src0_endofpacket   : out std_logic                                          -- endofpacket
		);
	end component PR_Test_Top_altera_merlin_demultiplexer_1921_4bpriii_cmp;

	component PR_Test_Top_altera_merlin_multiplexer_1922_huaylbq_cmp is
		port (
			clk                 : in  std_logic                      := 'X';             -- clk
			reset               : in  std_logic                      := 'X';             -- reset
			src_ready           : in  std_logic                      := 'X';             -- ready
			src_valid           : out std_logic;                                         -- valid
			src_data            : out std_logic_vector(126 downto 0);                    -- data
			src_channel         : out std_logic_vector(0 downto 0);                      -- channel
			src_startofpacket   : out std_logic;                                         -- startofpacket
			src_endofpacket     : out std_logic;                                         -- endofpacket
			sink0_ready         : out std_logic;                                         -- ready
			sink0_valid         : in  std_logic                      := 'X';             -- valid
			sink0_channel       : in  std_logic_vector(0 downto 0)   := (others => 'X'); -- channel
			sink0_data          : in  std_logic_vector(126 downto 0) := (others => 'X'); -- data
			sink0_startofpacket : in  std_logic                      := 'X';             -- startofpacket
			sink0_endofpacket   : in  std_logic                      := 'X'              -- endofpacket
		);
	end component PR_Test_Top_altera_merlin_multiplexer_1922_huaylbq_cmp;

	component PR_Test_Top_altera_merlin_multiplexer_1922_cterxoq_cmp is
		port (
			clk                 : in  std_logic                      := 'X';             -- clk
			reset               : in  std_logic                      := 'X';             -- reset
			src_ready           : in  std_logic                      := 'X';             -- ready
			src_valid           : out std_logic;                                         -- valid
			src_data            : out std_logic_vector(126 downto 0);                    -- data
			src_channel         : out std_logic_vector(0 downto 0);                      -- channel
			src_startofpacket   : out std_logic;                                         -- startofpacket
			src_endofpacket     : out std_logic;                                         -- endofpacket
			sink0_ready         : out std_logic;                                         -- ready
			sink0_valid         : in  std_logic                      := 'X';             -- valid
			sink0_channel       : in  std_logic_vector(0 downto 0)   := (others => 'X'); -- channel
			sink0_data          : in  std_logic_vector(126 downto 0) := (others => 'X'); -- data
			sink0_startofpacket : in  std_logic                      := 'X';             -- startofpacket
			sink0_endofpacket   : in  std_logic                      := 'X'              -- endofpacket
		);
	end component PR_Test_Top_altera_merlin_multiplexer_1922_cterxoq_cmp;

	signal msgdma_pr_mm_write_translator_avalon_universal_master_0_waitrequest   : std_logic;                      -- msgdma_pr_mm_write_agent:av_waitrequest -> msgdma_pr_mm_write_translator:uav_waitrequest
	signal msgdma_pr_mm_write_translator_avalon_universal_master_0_readdata      : std_logic_vector(31 downto 0);  -- msgdma_pr_mm_write_agent:av_readdata -> msgdma_pr_mm_write_translator:uav_readdata
	signal msgdma_pr_mm_write_translator_avalon_universal_master_0_debugaccess   : std_logic;                      -- msgdma_pr_mm_write_translator:uav_debugaccess -> msgdma_pr_mm_write_agent:av_debugaccess
	signal msgdma_pr_mm_write_translator_avalon_universal_master_0_address       : std_logic_vector(31 downto 0);  -- msgdma_pr_mm_write_translator:uav_address -> msgdma_pr_mm_write_agent:av_address
	signal msgdma_pr_mm_write_translator_avalon_universal_master_0_read          : std_logic;                      -- msgdma_pr_mm_write_translator:uav_read -> msgdma_pr_mm_write_agent:av_read
	signal msgdma_pr_mm_write_translator_avalon_universal_master_0_byteenable    : std_logic_vector(3 downto 0);   -- msgdma_pr_mm_write_translator:uav_byteenable -> msgdma_pr_mm_write_agent:av_byteenable
	signal msgdma_pr_mm_write_translator_avalon_universal_master_0_readdatavalid : std_logic;                      -- msgdma_pr_mm_write_agent:av_readdatavalid -> msgdma_pr_mm_write_translator:uav_readdatavalid
	signal msgdma_pr_mm_write_translator_avalon_universal_master_0_lock          : std_logic;                      -- msgdma_pr_mm_write_translator:uav_lock -> msgdma_pr_mm_write_agent:av_lock
	signal msgdma_pr_mm_write_translator_avalon_universal_master_0_write         : std_logic;                      -- msgdma_pr_mm_write_translator:uav_write -> msgdma_pr_mm_write_agent:av_write
	signal msgdma_pr_mm_write_translator_avalon_universal_master_0_writedata     : std_logic_vector(31 downto 0);  -- msgdma_pr_mm_write_translator:uav_writedata -> msgdma_pr_mm_write_agent:av_writedata
	signal msgdma_pr_mm_write_translator_avalon_universal_master_0_burstcount    : std_logic_vector(3 downto 0);   -- msgdma_pr_mm_write_translator:uav_burstcount -> msgdma_pr_mm_write_agent:av_burstcount
	signal rsp_mux_src_valid                                                     : std_logic;                      -- rsp_mux:src_valid -> msgdma_pr_mm_write_agent:rp_valid
	signal rsp_mux_src_data                                                      : std_logic_vector(126 downto 0); -- rsp_mux:src_data -> msgdma_pr_mm_write_agent:rp_data
	signal rsp_mux_src_ready                                                     : std_logic;                      -- msgdma_pr_mm_write_agent:rp_ready -> rsp_mux:src_ready
	signal rsp_mux_src_channel                                                   : std_logic_vector(0 downto 0);   -- rsp_mux:src_channel -> msgdma_pr_mm_write_agent:rp_channel
	signal rsp_mux_src_startofpacket                                             : std_logic;                      -- rsp_mux:src_startofpacket -> msgdma_pr_mm_write_agent:rp_startofpacket
	signal rsp_mux_src_endofpacket                                               : std_logic;                      -- rsp_mux:src_endofpacket -> msgdma_pr_mm_write_agent:rp_endofpacket
	signal pr_controller_avmm_slave_agent_m0_readdata                            : std_logic_vector(31 downto 0);  -- pr_controller_avmm_slave_translator:uav_readdata -> pr_controller_avmm_slave_agent:m0_readdata
	signal pr_controller_avmm_slave_agent_m0_waitrequest                         : std_logic;                      -- pr_controller_avmm_slave_translator:uav_waitrequest -> pr_controller_avmm_slave_agent:m0_waitrequest
	signal pr_controller_avmm_slave_agent_m0_debugaccess                         : std_logic;                      -- pr_controller_avmm_slave_agent:m0_debugaccess -> pr_controller_avmm_slave_translator:uav_debugaccess
	signal pr_controller_avmm_slave_agent_m0_address                             : std_logic_vector(31 downto 0);  -- pr_controller_avmm_slave_agent:m0_address -> pr_controller_avmm_slave_translator:uav_address
	signal pr_controller_avmm_slave_agent_m0_byteenable                          : std_logic_vector(3 downto 0);   -- pr_controller_avmm_slave_agent:m0_byteenable -> pr_controller_avmm_slave_translator:uav_byteenable
	signal pr_controller_avmm_slave_agent_m0_read                                : std_logic;                      -- pr_controller_avmm_slave_agent:m0_read -> pr_controller_avmm_slave_translator:uav_read
	signal pr_controller_avmm_slave_agent_m0_readdatavalid                       : std_logic;                      -- pr_controller_avmm_slave_translator:uav_readdatavalid -> pr_controller_avmm_slave_agent:m0_readdatavalid
	signal pr_controller_avmm_slave_agent_m0_lock                                : std_logic;                      -- pr_controller_avmm_slave_agent:m0_lock -> pr_controller_avmm_slave_translator:uav_lock
	signal pr_controller_avmm_slave_agent_m0_writedata                           : std_logic_vector(31 downto 0);  -- pr_controller_avmm_slave_agent:m0_writedata -> pr_controller_avmm_slave_translator:uav_writedata
	signal pr_controller_avmm_slave_agent_m0_write                               : std_logic;                      -- pr_controller_avmm_slave_agent:m0_write -> pr_controller_avmm_slave_translator:uav_write
	signal pr_controller_avmm_slave_agent_m0_burstcount                          : std_logic_vector(2 downto 0);   -- pr_controller_avmm_slave_agent:m0_burstcount -> pr_controller_avmm_slave_translator:uav_burstcount
	signal pr_controller_avmm_slave_agent_rf_source_valid                        : std_logic;                      -- pr_controller_avmm_slave_agent:rf_source_valid -> pr_controller_avmm_slave_agent_rsp_fifo:in_valid
	signal pr_controller_avmm_slave_agent_rf_source_data                         : std_logic_vector(127 downto 0); -- pr_controller_avmm_slave_agent:rf_source_data -> pr_controller_avmm_slave_agent_rsp_fifo:in_data
	signal pr_controller_avmm_slave_agent_rf_source_ready                        : std_logic;                      -- pr_controller_avmm_slave_agent_rsp_fifo:in_ready -> pr_controller_avmm_slave_agent:rf_source_ready
	signal pr_controller_avmm_slave_agent_rf_source_startofpacket                : std_logic;                      -- pr_controller_avmm_slave_agent:rf_source_startofpacket -> pr_controller_avmm_slave_agent_rsp_fifo:in_startofpacket
	signal pr_controller_avmm_slave_agent_rf_source_endofpacket                  : std_logic;                      -- pr_controller_avmm_slave_agent:rf_source_endofpacket -> pr_controller_avmm_slave_agent_rsp_fifo:in_endofpacket
	signal pr_controller_avmm_slave_agent_rsp_fifo_out_valid                     : std_logic;                      -- pr_controller_avmm_slave_agent_rsp_fifo:out_valid -> pr_controller_avmm_slave_agent:rf_sink_valid
	signal pr_controller_avmm_slave_agent_rsp_fifo_out_data                      : std_logic_vector(127 downto 0); -- pr_controller_avmm_slave_agent_rsp_fifo:out_data -> pr_controller_avmm_slave_agent:rf_sink_data
	signal pr_controller_avmm_slave_agent_rsp_fifo_out_ready                     : std_logic;                      -- pr_controller_avmm_slave_agent:rf_sink_ready -> pr_controller_avmm_slave_agent_rsp_fifo:out_ready
	signal pr_controller_avmm_slave_agent_rsp_fifo_out_startofpacket             : std_logic;                      -- pr_controller_avmm_slave_agent_rsp_fifo:out_startofpacket -> pr_controller_avmm_slave_agent:rf_sink_startofpacket
	signal pr_controller_avmm_slave_agent_rsp_fifo_out_endofpacket               : std_logic;                      -- pr_controller_avmm_slave_agent_rsp_fifo:out_endofpacket -> pr_controller_avmm_slave_agent:rf_sink_endofpacket
	signal pr_controller_avmm_slave_agent_rdata_fifo_src_valid                   : std_logic;                      -- pr_controller_avmm_slave_agent:rdata_fifo_src_valid -> pr_controller_avmm_slave_agent:rdata_fifo_sink_valid
	signal pr_controller_avmm_slave_agent_rdata_fifo_src_data                    : std_logic_vector(33 downto 0);  -- pr_controller_avmm_slave_agent:rdata_fifo_src_data -> pr_controller_avmm_slave_agent:rdata_fifo_sink_data
	signal pr_controller_avmm_slave_agent_rdata_fifo_src_ready                   : std_logic;                      -- pr_controller_avmm_slave_agent:rdata_fifo_sink_ready -> pr_controller_avmm_slave_agent:rdata_fifo_src_ready
	signal msgdma_pr_mm_write_agent_cp_valid                                     : std_logic;                      -- msgdma_pr_mm_write_agent:cp_valid -> router:sink_valid
	signal msgdma_pr_mm_write_agent_cp_data                                      : std_logic_vector(126 downto 0); -- msgdma_pr_mm_write_agent:cp_data -> router:sink_data
	signal msgdma_pr_mm_write_agent_cp_ready                                     : std_logic;                      -- router:sink_ready -> msgdma_pr_mm_write_agent:cp_ready
	signal msgdma_pr_mm_write_agent_cp_startofpacket                             : std_logic;                      -- msgdma_pr_mm_write_agent:cp_startofpacket -> router:sink_startofpacket
	signal msgdma_pr_mm_write_agent_cp_endofpacket                               : std_logic;                      -- msgdma_pr_mm_write_agent:cp_endofpacket -> router:sink_endofpacket
	signal router_src_valid                                                      : std_logic;                      -- router:src_valid -> cmd_demux:sink_valid
	signal router_src_data                                                       : std_logic_vector(126 downto 0); -- router:src_data -> cmd_demux:sink_data
	signal router_src_ready                                                      : std_logic;                      -- cmd_demux:sink_ready -> router:src_ready
	signal router_src_channel                                                    : std_logic_vector(0 downto 0);   -- router:src_channel -> cmd_demux:sink_channel
	signal router_src_startofpacket                                              : std_logic;                      -- router:src_startofpacket -> cmd_demux:sink_startofpacket
	signal router_src_endofpacket                                                : std_logic;                      -- router:src_endofpacket -> cmd_demux:sink_endofpacket
	signal pr_controller_avmm_slave_agent_rp_valid                               : std_logic;                      -- pr_controller_avmm_slave_agent:rp_valid -> router_001:sink_valid
	signal pr_controller_avmm_slave_agent_rp_data                                : std_logic_vector(126 downto 0); -- pr_controller_avmm_slave_agent:rp_data -> router_001:sink_data
	signal pr_controller_avmm_slave_agent_rp_ready                               : std_logic;                      -- router_001:sink_ready -> pr_controller_avmm_slave_agent:rp_ready
	signal pr_controller_avmm_slave_agent_rp_startofpacket                       : std_logic;                      -- pr_controller_avmm_slave_agent:rp_startofpacket -> router_001:sink_startofpacket
	signal pr_controller_avmm_slave_agent_rp_endofpacket                         : std_logic;                      -- pr_controller_avmm_slave_agent:rp_endofpacket -> router_001:sink_endofpacket
	signal router_001_src_valid                                                  : std_logic;                      -- router_001:src_valid -> rsp_demux:sink_valid
	signal router_001_src_data                                                   : std_logic_vector(126 downto 0); -- router_001:src_data -> rsp_demux:sink_data
	signal router_001_src_ready                                                  : std_logic;                      -- rsp_demux:sink_ready -> router_001:src_ready
	signal router_001_src_channel                                                : std_logic_vector(0 downto 0);   -- router_001:src_channel -> rsp_demux:sink_channel
	signal router_001_src_startofpacket                                          : std_logic;                      -- router_001:src_startofpacket -> rsp_demux:sink_startofpacket
	signal router_001_src_endofpacket                                            : std_logic;                      -- router_001:src_endofpacket -> rsp_demux:sink_endofpacket
	signal cmd_mux_src_valid                                                     : std_logic;                      -- cmd_mux:src_valid -> pr_controller_avmm_slave_burst_adapter:sink0_valid
	signal cmd_mux_src_data                                                      : std_logic_vector(126 downto 0); -- cmd_mux:src_data -> pr_controller_avmm_slave_burst_adapter:sink0_data
	signal cmd_mux_src_ready                                                     : std_logic;                      -- pr_controller_avmm_slave_burst_adapter:sink0_ready -> cmd_mux:src_ready
	signal cmd_mux_src_channel                                                   : std_logic_vector(0 downto 0);   -- cmd_mux:src_channel -> pr_controller_avmm_slave_burst_adapter:sink0_channel
	signal cmd_mux_src_startofpacket                                             : std_logic;                      -- cmd_mux:src_startofpacket -> pr_controller_avmm_slave_burst_adapter:sink0_startofpacket
	signal cmd_mux_src_endofpacket                                               : std_logic;                      -- cmd_mux:src_endofpacket -> pr_controller_avmm_slave_burst_adapter:sink0_endofpacket
	signal pr_controller_avmm_slave_burst_adapter_source0_valid                  : std_logic;                      -- pr_controller_avmm_slave_burst_adapter:source0_valid -> pr_controller_avmm_slave_agent:cp_valid
	signal pr_controller_avmm_slave_burst_adapter_source0_data                   : std_logic_vector(126 downto 0); -- pr_controller_avmm_slave_burst_adapter:source0_data -> pr_controller_avmm_slave_agent:cp_data
	signal pr_controller_avmm_slave_burst_adapter_source0_ready                  : std_logic;                      -- pr_controller_avmm_slave_agent:cp_ready -> pr_controller_avmm_slave_burst_adapter:source0_ready
	signal pr_controller_avmm_slave_burst_adapter_source0_channel                : std_logic_vector(0 downto 0);   -- pr_controller_avmm_slave_burst_adapter:source0_channel -> pr_controller_avmm_slave_agent:cp_channel
	signal pr_controller_avmm_slave_burst_adapter_source0_startofpacket          : std_logic;                      -- pr_controller_avmm_slave_burst_adapter:source0_startofpacket -> pr_controller_avmm_slave_agent:cp_startofpacket
	signal pr_controller_avmm_slave_burst_adapter_source0_endofpacket            : std_logic;                      -- pr_controller_avmm_slave_burst_adapter:source0_endofpacket -> pr_controller_avmm_slave_agent:cp_endofpacket
	signal cmd_demux_src0_valid                                                  : std_logic;                      -- cmd_demux:src0_valid -> cmd_mux:sink0_valid
	signal cmd_demux_src0_data                                                   : std_logic_vector(126 downto 0); -- cmd_demux:src0_data -> cmd_mux:sink0_data
	signal cmd_demux_src0_ready                                                  : std_logic;                      -- cmd_mux:sink0_ready -> cmd_demux:src0_ready
	signal cmd_demux_src0_channel                                                : std_logic_vector(0 downto 0);   -- cmd_demux:src0_channel -> cmd_mux:sink0_channel
	signal cmd_demux_src0_startofpacket                                          : std_logic;                      -- cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	signal cmd_demux_src0_endofpacket                                            : std_logic;                      -- cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	signal rsp_demux_src0_valid                                                  : std_logic;                      -- rsp_demux:src0_valid -> rsp_mux:sink0_valid
	signal rsp_demux_src0_data                                                   : std_logic_vector(126 downto 0); -- rsp_demux:src0_data -> rsp_mux:sink0_data
	signal rsp_demux_src0_ready                                                  : std_logic;                      -- rsp_mux:sink0_ready -> rsp_demux:src0_ready
	signal rsp_demux_src0_channel                                                : std_logic_vector(0 downto 0);   -- rsp_demux:src0_channel -> rsp_mux:sink0_channel
	signal rsp_demux_src0_startofpacket                                          : std_logic;                      -- rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	signal rsp_demux_src0_endofpacket                                            : std_logic;                      -- rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket

	for msgdma_pr_mm_write_translator : PR_Test_Top_altera_merlin_master_translator_192_lykd4la_cmp
		use entity altera_merlin_master_translator_192.PR_Test_Top_altera_merlin_master_translator_192_lykd4la;
	for pr_controller_avmm_slave_translator : PR_Test_Top_altera_merlin_slave_translator_191_x56fcki_cmp
		use entity altera_merlin_slave_translator_191.PR_Test_Top_altera_merlin_slave_translator_191_x56fcki;
	for msgdma_pr_mm_write_agent : PR_Test_Top_altera_merlin_master_agent_1922_fy3n5ti_cmp
		use entity altera_merlin_master_agent_1922.PR_Test_Top_altera_merlin_master_agent_1922_fy3n5ti;
	for pr_controller_avmm_slave_agent : PR_Test_Top_altera_merlin_slave_agent_1921_b6r3djy_cmp
		use entity altera_merlin_slave_agent_1921.PR_Test_Top_altera_merlin_slave_agent_1921_b6r3djy;
	for pr_controller_avmm_slave_agent_rsp_fifo : PR_Test_Top_altera_avalon_sc_fifo_1932_5j7ufsq_cmp
		use entity altera_avalon_sc_fifo_1932.PR_Test_Top_altera_avalon_sc_fifo_1932_5j7ufsq;
	for router : PR_Test_Top_altera_merlin_router_1921_pfltgpa_cmp
		use entity altera_merlin_router_1921.PR_Test_Top_altera_merlin_router_1921_pfltgpa;
	for router_001 : PR_Test_Top_altera_merlin_router_1921_e4osxtq_cmp
		use entity altera_merlin_router_1921.PR_Test_Top_altera_merlin_router_1921_e4osxtq;
	for pr_controller_avmm_slave_burst_adapter : PR_Test_Top_altera_merlin_burst_adapter_1932_4owamsy_cmp
		use entity altera_merlin_burst_adapter_1932.PR_Test_Top_altera_merlin_burst_adapter_1932_4owamsy;
	for cmd_demux : PR_Test_Top_altera_merlin_demultiplexer_1921_4bpriii_cmp
		use entity altera_merlin_demultiplexer_1921.PR_Test_Top_altera_merlin_demultiplexer_1921_4bpriii;
	for rsp_demux : PR_Test_Top_altera_merlin_demultiplexer_1921_4bpriii_cmp
		use entity altera_merlin_demultiplexer_1921.PR_Test_Top_altera_merlin_demultiplexer_1921_4bpriii;
	for cmd_mux : PR_Test_Top_altera_merlin_multiplexer_1922_huaylbq_cmp
		use entity altera_merlin_multiplexer_1922.PR_Test_Top_altera_merlin_multiplexer_1922_huaylbq;
	for rsp_mux : PR_Test_Top_altera_merlin_multiplexer_1922_cterxoq_cmp
		use entity altera_merlin_multiplexer_1922.PR_Test_Top_altera_merlin_multiplexer_1922_cterxoq;
begin

	msgdma_pr_mm_write_translator : component PR_Test_Top_altera_merlin_master_translator_192_lykd4la_cmp
		generic map (
			AV_ADDRESS_W                => 32,
			AV_DATA_W                   => 32,
			AV_BURSTCOUNT_W             => 2,
			AV_BYTEENABLE_W             => 4,
			UAV_ADDRESS_W               => 32,
			UAV_BURSTCOUNT_W            => 4,
			USE_READ                    => 0,
			USE_WRITE                   => 1,
			USE_BEGINBURSTTRANSFER      => 0,
			USE_BEGINTRANSFER           => 0,
			USE_CHIPSELECT              => 0,
			USE_BURSTCOUNT              => 1,
			USE_READDATAVALID           => 0,
			USE_WAITREQUEST             => 1,
			USE_READRESPONSE            => 0,
			USE_WRITERESPONSE           => 0,
			AV_SYMBOLS_PER_WORD         => 4,
			AV_ADDRESS_SYMBOLS          => 1,
			AV_BURSTCOUNT_SYMBOLS       => 0,
			AV_CONSTANT_BURST_BEHAVIOR  => 1,
			UAV_CONSTANT_BURST_BEHAVIOR => 0,
			AV_LINEWRAPBURSTS           => 0,
			AV_REGISTERINCOMINGSIGNALS  => 0,
			SYNC_RESET                  => 0,
			WAITREQUEST_ALLOWANCE       => 0,
			USE_OUTPUTENABLE            => 0
		)
		port map (
			clk                    => clock_in_out_clk_clk,                                                  --                       clk.clk
			reset                  => pr_controller_nreset_reset_bridge_in_reset_reset,                      --                     reset.reset
			uav_address            => msgdma_pr_mm_write_translator_avalon_universal_master_0_address,       -- avalon_universal_master_0.address
			uav_burstcount         => msgdma_pr_mm_write_translator_avalon_universal_master_0_burstcount,    --                          .burstcount
			uav_read               => msgdma_pr_mm_write_translator_avalon_universal_master_0_read,          --                          .read
			uav_write              => msgdma_pr_mm_write_translator_avalon_universal_master_0_write,         --                          .write
			uav_waitrequest        => msgdma_pr_mm_write_translator_avalon_universal_master_0_waitrequest,   --                          .waitrequest
			uav_readdatavalid      => msgdma_pr_mm_write_translator_avalon_universal_master_0_readdatavalid, --                          .readdatavalid
			uav_byteenable         => msgdma_pr_mm_write_translator_avalon_universal_master_0_byteenable,    --                          .byteenable
			uav_readdata           => msgdma_pr_mm_write_translator_avalon_universal_master_0_readdata,      --                          .readdata
			uav_writedata          => msgdma_pr_mm_write_translator_avalon_universal_master_0_writedata,     --                          .writedata
			uav_lock               => msgdma_pr_mm_write_translator_avalon_universal_master_0_lock,          --                          .lock
			uav_debugaccess        => msgdma_pr_mm_write_translator_avalon_universal_master_0_debugaccess,   --                          .debugaccess
			av_address             => msgdma_pr_mm_write_address,                                            --      avalon_anti_master_0.address
			av_waitrequest         => msgdma_pr_mm_write_waitrequest,                                        --                          .waitrequest
			av_burstcount          => msgdma_pr_mm_write_burstcount,                                         --                          .burstcount
			av_byteenable          => msgdma_pr_mm_write_byteenable,                                         --                          .byteenable
			av_write               => msgdma_pr_mm_write_write,                                              --                          .write
			av_writedata           => msgdma_pr_mm_write_writedata,                                          --                          .writedata
			av_beginbursttransfer  => '0',                                                                   --               (terminated)
			av_begintransfer       => '0',                                                                   --               (terminated)
			av_chipselect          => '0',                                                                   --               (terminated)
			av_read                => '0',                                                                   --               (terminated)
			av_readdata            => open,                                                                  --               (terminated)
			av_readdatavalid       => open,                                                                  --               (terminated)
			av_lock                => '0',                                                                   --               (terminated)
			av_debugaccess         => '0',                                                                   --               (terminated)
			uav_outputenable       => '0',                                                                   --               (terminated)
			uav_clken              => open,                                                                  --               (terminated)
			av_clken               => '1',                                                                   --               (terminated)
			uav_response           => "00",                                                                  --               (terminated)
			av_response            => open,                                                                  --               (terminated)
			uav_writeresponsevalid => '0',                                                                   --               (terminated)
			av_writeresponsevalid  => open                                                                   --               (terminated)
		);

	pr_controller_avmm_slave_translator : component PR_Test_Top_altera_merlin_slave_translator_191_x56fcki_cmp
		generic map (
			AV_ADDRESS_W                   => 4,
			AV_DATA_W                      => 32,
			UAV_DATA_W                     => 32,
			AV_BURSTCOUNT_W                => 1,
			AV_BYTEENABLE_W                => 4,
			UAV_BYTEENABLE_W               => 4,
			UAV_ADDRESS_W                  => 32,
			UAV_BURSTCOUNT_W               => 3,
			AV_READLATENCY                 => 0,
			USE_READDATAVALID              => 0,
			USE_WAITREQUEST                => 1,
			USE_UAV_CLKEN                  => 0,
			USE_READRESPONSE               => 0,
			USE_WRITERESPONSE              => 0,
			AV_SYMBOLS_PER_WORD            => 4,
			AV_ADDRESS_SYMBOLS             => 0,
			AV_BURSTCOUNT_SYMBOLS          => 0,
			AV_CONSTANT_BURST_BEHAVIOR     => 0,
			UAV_CONSTANT_BURST_BEHAVIOR    => 0,
			AV_REQUIRE_UNALIGNED_ADDRESSES => 0,
			CHIPSELECT_THROUGH_READLATENCY => 0,
			AV_READ_WAIT_CYCLES            => 0,
			AV_WRITE_WAIT_CYCLES           => 0,
			AV_SETUP_WAIT_CYCLES           => 0,
			AV_DATA_HOLD_CYCLES            => 0,
			WAITREQUEST_ALLOWANCE          => 0,
			SYNC_RESET                     => 0
		)
		port map (
			clk                    => clock_in_out_clk_clk,                             --                      clk.clk
			reset                  => pr_controller_nreset_reset_bridge_in_reset_reset, --                    reset.reset
			uav_address            => pr_controller_avmm_slave_agent_m0_address,        -- avalon_universal_slave_0.address
			uav_burstcount         => pr_controller_avmm_slave_agent_m0_burstcount,     --                         .burstcount
			uav_read               => pr_controller_avmm_slave_agent_m0_read,           --                         .read
			uav_write              => pr_controller_avmm_slave_agent_m0_write,          --                         .write
			uav_waitrequest        => pr_controller_avmm_slave_agent_m0_waitrequest,    --                         .waitrequest
			uav_readdatavalid      => pr_controller_avmm_slave_agent_m0_readdatavalid,  --                         .readdatavalid
			uav_byteenable         => pr_controller_avmm_slave_agent_m0_byteenable,     --                         .byteenable
			uav_readdata           => pr_controller_avmm_slave_agent_m0_readdata,       --                         .readdata
			uav_writedata          => pr_controller_avmm_slave_agent_m0_writedata,      --                         .writedata
			uav_lock               => pr_controller_avmm_slave_agent_m0_lock,           --                         .lock
			uav_debugaccess        => pr_controller_avmm_slave_agent_m0_debugaccess,    --                         .debugaccess
			av_address             => pr_controller_avmm_slave_address,                 --      avalon_anti_slave_0.address
			av_write               => pr_controller_avmm_slave_write,                   --                         .write
			av_read                => pr_controller_avmm_slave_read,                    --                         .read
			av_readdata            => pr_controller_avmm_slave_readdata,                --                         .readdata
			av_writedata           => pr_controller_avmm_slave_writedata,               --                         .writedata
			av_waitrequest         => pr_controller_avmm_slave_waitrequest,             --                         .waitrequest
			av_begintransfer       => open,                                             --              (terminated)
			av_beginbursttransfer  => open,                                             --              (terminated)
			av_burstcount          => open,                                             --              (terminated)
			av_byteenable          => open,                                             --              (terminated)
			av_readdatavalid       => '0',                                              --              (terminated)
			av_writebyteenable     => open,                                             --              (terminated)
			av_lock                => open,                                             --              (terminated)
			av_chipselect          => open,                                             --              (terminated)
			av_clken               => open,                                             --              (terminated)
			uav_clken              => '0',                                              --              (terminated)
			av_debugaccess         => open,                                             --              (terminated)
			av_outputenable        => open,                                             --              (terminated)
			uav_response           => open,                                             --              (terminated)
			av_response            => "00",                                             --              (terminated)
			uav_writeresponsevalid => open,                                             --              (terminated)
			av_writeresponsevalid  => '0'                                               --              (terminated)
		);

	msgdma_pr_mm_write_agent : component PR_Test_Top_altera_merlin_master_agent_1922_fy3n5ti_cmp
		generic map (
			PKT_WUNIQUE               => 111,
			PKT_DOMAIN_H              => 110,
			PKT_DOMAIN_L              => 109,
			PKT_SNOOP_H               => 108,
			PKT_SNOOP_L               => 105,
			PKT_BARRIER_H             => 104,
			PKT_BARRIER_L             => 103,
			PKT_ORI_BURST_SIZE_H      => 102,
			PKT_ORI_BURST_SIZE_L      => 100,
			PKT_RESPONSE_STATUS_H     => 99,
			PKT_RESPONSE_STATUS_L     => 98,
			PKT_QOS_H                 => 87,
			PKT_QOS_L                 => 87,
			PKT_DATA_SIDEBAND_H       => 85,
			PKT_DATA_SIDEBAND_L       => 85,
			PKT_ADDR_SIDEBAND_H       => 84,
			PKT_ADDR_SIDEBAND_L       => 84,
			PKT_BURST_TYPE_H          => 83,
			PKT_BURST_TYPE_L          => 82,
			PKT_CACHE_H               => 97,
			PKT_CACHE_L               => 94,
			PKT_THREAD_ID_H           => 90,
			PKT_THREAD_ID_L           => 90,
			PKT_BURST_SIZE_H          => 81,
			PKT_BURST_SIZE_L          => 79,
			PKT_TRANS_EXCLUSIVE       => 73,
			PKT_TRANS_LOCK            => 72,
			PKT_BEGIN_BURST           => 86,
			PKT_PROTECTION_H          => 93,
			PKT_PROTECTION_L          => 91,
			PKT_BURSTWRAP_H           => 78,
			PKT_BURSTWRAP_L           => 78,
			PKT_BYTE_CNT_H            => 77,
			PKT_BYTE_CNT_L            => 74,
			PKT_ADDR_H                => 67,
			PKT_ADDR_L                => 36,
			PKT_TRANS_COMPRESSED_READ => 68,
			PKT_TRANS_POSTED          => 69,
			PKT_TRANS_WRITE           => 70,
			PKT_TRANS_READ            => 71,
			PKT_DATA_H                => 31,
			PKT_DATA_L                => 0,
			PKT_BYTEEN_H              => 35,
			PKT_BYTEEN_L              => 32,
			PKT_SRC_ID_H              => 88,
			PKT_SRC_ID_L              => 88,
			PKT_DEST_ID_H             => 89,
			PKT_DEST_ID_L             => 89,
			PKT_POISON_H              => 112,
			PKT_POISON_L              => 112,
			PKT_DATACHK_H             => 113,
			PKT_DATACHK_L             => 113,
			PKT_ADDRCHK_H             => 116,
			PKT_ADDRCHK_L             => 115,
			PKT_SAI_H                 => 117,
			PKT_SAI_L                 => 117,
			PKT_USER_DATA_H           => 114,
			PKT_USER_DATA_L           => 114,
			ST_DATA_W                 => 127,
			ST_CHANNEL_W              => 1,
			AV_BURSTCOUNT_W           => 4,
			SUPPRESS_0_BYTEEN_RSP     => 0,
			ID                        => 0,
			BURSTWRAP_VALUE           => 1,
			CACHE_VALUE               => 0,
			SECURE_ACCESS_BIT         => 1,
			USE_READRESPONSE          => 0,
			USE_WRITERESPONSE         => 0,
			DOMAIN_VALUE              => 3,
			BARRIER_VALUE             => 0,
			SNOOP_VALUE               => 0,
			WUNIQUE_VALUE             => 0,
			SYNC_RESET                => 0,
			USE_PKT_DATACHK           => 0,
			USE_PKT_ADDRCHK           => 0,
			ROLE_BASED_USER           => 0
		)
		port map (
			clk                   => clock_in_out_clk_clk,                                                  --       clk.clk
			reset                 => pr_controller_nreset_reset_bridge_in_reset_reset,                      -- clk_reset.reset
			av_address            => msgdma_pr_mm_write_translator_avalon_universal_master_0_address,       --        av.address
			av_write              => msgdma_pr_mm_write_translator_avalon_universal_master_0_write,         --          .write
			av_read               => msgdma_pr_mm_write_translator_avalon_universal_master_0_read,          --          .read
			av_writedata          => msgdma_pr_mm_write_translator_avalon_universal_master_0_writedata,     --          .writedata
			av_readdata           => msgdma_pr_mm_write_translator_avalon_universal_master_0_readdata,      --          .readdata
			av_waitrequest        => msgdma_pr_mm_write_translator_avalon_universal_master_0_waitrequest,   --          .waitrequest
			av_readdatavalid      => msgdma_pr_mm_write_translator_avalon_universal_master_0_readdatavalid, --          .readdatavalid
			av_byteenable         => msgdma_pr_mm_write_translator_avalon_universal_master_0_byteenable,    --          .byteenable
			av_burstcount         => msgdma_pr_mm_write_translator_avalon_universal_master_0_burstcount,    --          .burstcount
			av_debugaccess        => msgdma_pr_mm_write_translator_avalon_universal_master_0_debugaccess,   --          .debugaccess
			av_lock               => msgdma_pr_mm_write_translator_avalon_universal_master_0_lock,          --          .lock
			cp_valid              => msgdma_pr_mm_write_agent_cp_valid,                                     --        cp.valid
			cp_data               => msgdma_pr_mm_write_agent_cp_data,                                      --          .data
			cp_startofpacket      => msgdma_pr_mm_write_agent_cp_startofpacket,                             --          .startofpacket
			cp_endofpacket        => msgdma_pr_mm_write_agent_cp_endofpacket,                               --          .endofpacket
			cp_ready              => msgdma_pr_mm_write_agent_cp_ready,                                     --          .ready
			rp_valid              => rsp_mux_src_valid,                                                     --        rp.valid
			rp_data               => rsp_mux_src_data,                                                      --          .data
			rp_channel            => rsp_mux_src_channel,                                                   --          .channel
			rp_startofpacket      => rsp_mux_src_startofpacket,                                             --          .startofpacket
			rp_endofpacket        => rsp_mux_src_endofpacket,                                               --          .endofpacket
			rp_ready              => rsp_mux_src_ready,                                                     --          .ready
			av_response           => open,                                                                  -- (terminated)
			av_writeresponsevalid => open                                                                   -- (terminated)
		);

	pr_controller_avmm_slave_agent : component PR_Test_Top_altera_merlin_slave_agent_1921_b6r3djy_cmp
		generic map (
			PKT_ORI_BURST_SIZE_H      => 102,
			PKT_ORI_BURST_SIZE_L      => 100,
			PKT_RESPONSE_STATUS_H     => 99,
			PKT_RESPONSE_STATUS_L     => 98,
			PKT_BURST_SIZE_H          => 81,
			PKT_BURST_SIZE_L          => 79,
			PKT_TRANS_LOCK            => 72,
			PKT_BEGIN_BURST           => 86,
			PKT_PROTECTION_H          => 93,
			PKT_PROTECTION_L          => 91,
			PKT_BURSTWRAP_H           => 78,
			PKT_BURSTWRAP_L           => 78,
			PKT_BYTE_CNT_H            => 77,
			PKT_BYTE_CNT_L            => 74,
			PKT_ADDR_H                => 67,
			PKT_ADDR_L                => 36,
			PKT_TRANS_COMPRESSED_READ => 68,
			PKT_TRANS_POSTED          => 69,
			PKT_TRANS_WRITE           => 70,
			PKT_TRANS_READ            => 71,
			PKT_DATA_H                => 31,
			PKT_DATA_L                => 0,
			PKT_BYTEEN_H              => 35,
			PKT_BYTEEN_L              => 32,
			PKT_SRC_ID_H              => 88,
			PKT_SRC_ID_L              => 88,
			PKT_DEST_ID_H             => 89,
			PKT_DEST_ID_L             => 89,
			PKT_POISON_H              => 112,
			PKT_POISON_L              => 112,
			PKT_DATACHK_H             => 113,
			PKT_DATACHK_L             => 113,
			PKT_SAI_H                 => 117,
			PKT_SAI_L                 => 117,
			PKT_ADDRCHK_H             => 116,
			PKT_ADDRCHK_L             => 115,
			PKT_USER_DATA_H           => 114,
			PKT_USER_DATA_L           => 114,
			PKT_SYMBOL_W              => 8,
			ST_CHANNEL_W              => 1,
			ST_DATA_W                 => 127,
			AVS_BURSTCOUNT_W          => 3,
			SUPPRESS_0_BYTEEN_CMD     => 0,
			USE_MEMORY_BLOCKS         => 0,
			PREVENT_FIFO_OVERFLOW     => 1,
			USE_READRESPONSE          => 0,
			USE_WRITERESPONSE         => 0,
			ECC_ENABLE                => 0,
			SYNC_RESET                => 0,
			USE_PKT_DATACHK           => 0,
			ROLE_BASED_USER           => 0
		)
		port map (
			clk                     => clock_in_out_clk_clk,                                         --             clk.clk
			reset                   => pr_controller_nreset_reset_bridge_in_reset_reset,             --       clk_reset.reset
			m0_address              => pr_controller_avmm_slave_agent_m0_address,                    --              m0.address
			m0_burstcount           => pr_controller_avmm_slave_agent_m0_burstcount,                 --                .burstcount
			m0_byteenable           => pr_controller_avmm_slave_agent_m0_byteenable,                 --                .byteenable
			m0_debugaccess          => pr_controller_avmm_slave_agent_m0_debugaccess,                --                .debugaccess
			m0_lock                 => pr_controller_avmm_slave_agent_m0_lock,                       --                .lock
			m0_readdata             => pr_controller_avmm_slave_agent_m0_readdata,                   --                .readdata
			m0_readdatavalid        => pr_controller_avmm_slave_agent_m0_readdatavalid,              --                .readdatavalid
			m0_read                 => pr_controller_avmm_slave_agent_m0_read,                       --                .read
			m0_waitrequest          => pr_controller_avmm_slave_agent_m0_waitrequest,                --                .waitrequest
			m0_writedata            => pr_controller_avmm_slave_agent_m0_writedata,                  --                .writedata
			m0_write                => pr_controller_avmm_slave_agent_m0_write,                      --                .write
			rp_endofpacket          => pr_controller_avmm_slave_agent_rp_endofpacket,                --              rp.endofpacket
			rp_ready                => pr_controller_avmm_slave_agent_rp_ready,                      --                .ready
			rp_valid                => pr_controller_avmm_slave_agent_rp_valid,                      --                .valid
			rp_data                 => pr_controller_avmm_slave_agent_rp_data,                       --                .data
			rp_startofpacket        => pr_controller_avmm_slave_agent_rp_startofpacket,              --                .startofpacket
			cp_ready                => pr_controller_avmm_slave_burst_adapter_source0_ready,         --              cp.ready
			cp_valid                => pr_controller_avmm_slave_burst_adapter_source0_valid,         --                .valid
			cp_data                 => pr_controller_avmm_slave_burst_adapter_source0_data,          --                .data
			cp_startofpacket        => pr_controller_avmm_slave_burst_adapter_source0_startofpacket, --                .startofpacket
			cp_endofpacket          => pr_controller_avmm_slave_burst_adapter_source0_endofpacket,   --                .endofpacket
			cp_channel              => pr_controller_avmm_slave_burst_adapter_source0_channel,       --                .channel
			rf_sink_ready           => pr_controller_avmm_slave_agent_rsp_fifo_out_ready,            --         rf_sink.ready
			rf_sink_valid           => pr_controller_avmm_slave_agent_rsp_fifo_out_valid,            --                .valid
			rf_sink_startofpacket   => pr_controller_avmm_slave_agent_rsp_fifo_out_startofpacket,    --                .startofpacket
			rf_sink_endofpacket     => pr_controller_avmm_slave_agent_rsp_fifo_out_endofpacket,      --                .endofpacket
			rf_sink_data            => pr_controller_avmm_slave_agent_rsp_fifo_out_data,             --                .data
			rf_source_ready         => pr_controller_avmm_slave_agent_rf_source_ready,               --       rf_source.ready
			rf_source_valid         => pr_controller_avmm_slave_agent_rf_source_valid,               --                .valid
			rf_source_startofpacket => pr_controller_avmm_slave_agent_rf_source_startofpacket,       --                .startofpacket
			rf_source_endofpacket   => pr_controller_avmm_slave_agent_rf_source_endofpacket,         --                .endofpacket
			rf_source_data          => pr_controller_avmm_slave_agent_rf_source_data,                --                .data
			rdata_fifo_sink_ready   => pr_controller_avmm_slave_agent_rdata_fifo_src_ready,          -- rdata_fifo_sink.ready
			rdata_fifo_sink_valid   => pr_controller_avmm_slave_agent_rdata_fifo_src_valid,          --                .valid
			rdata_fifo_sink_data    => pr_controller_avmm_slave_agent_rdata_fifo_src_data,           --                .data
			rdata_fifo_src_ready    => pr_controller_avmm_slave_agent_rdata_fifo_src_ready,          --  rdata_fifo_src.ready
			rdata_fifo_src_valid    => pr_controller_avmm_slave_agent_rdata_fifo_src_valid,          --                .valid
			rdata_fifo_src_data     => pr_controller_avmm_slave_agent_rdata_fifo_src_data,           --                .data
			m0_response             => "00",                                                         --     (terminated)
			m0_writeresponsevalid   => '0',                                                          --     (terminated)
			rdata_fifo_sink_error   => '0'                                                           --     (terminated)
		);

	pr_controller_avmm_slave_agent_rsp_fifo : component PR_Test_Top_altera_avalon_sc_fifo_1932_5j7ufsq_cmp
		generic map (
			SYMBOLS_PER_BEAT    => 1,
			BITS_PER_SYMBOL     => 128,
			FIFO_DEPTH          => 2,
			CHANNEL_WIDTH       => 0,
			ERROR_WIDTH         => 0,
			USE_PACKETS         => 1,
			USE_FILL_LEVEL      => 0,
			EMPTY_LATENCY       => 1,
			USE_MEMORY_BLOCKS   => 0,
			USE_STORE_FORWARD   => 0,
			USE_ALMOST_FULL_IF  => 0,
			USE_ALMOST_EMPTY_IF => 0,
			EMPTY_WIDTH         => 1,
			MEM_TYPE            => "M20K",
			SYNC_RESET          => 0
		)
		port map (
			clk               => clock_in_out_clk_clk,                                      --       clk.clk
			reset             => pr_controller_nreset_reset_bridge_in_reset_reset,          -- clk_reset.reset
			in_data           => pr_controller_avmm_slave_agent_rf_source_data,             --        in.data
			in_valid          => pr_controller_avmm_slave_agent_rf_source_valid,            --          .valid
			in_ready          => pr_controller_avmm_slave_agent_rf_source_ready,            --          .ready
			in_startofpacket  => pr_controller_avmm_slave_agent_rf_source_startofpacket,    --          .startofpacket
			in_endofpacket    => pr_controller_avmm_slave_agent_rf_source_endofpacket,      --          .endofpacket
			out_data          => pr_controller_avmm_slave_agent_rsp_fifo_out_data,          --       out.data
			out_valid         => pr_controller_avmm_slave_agent_rsp_fifo_out_valid,         --          .valid
			out_ready         => pr_controller_avmm_slave_agent_rsp_fifo_out_ready,         --          .ready
			out_startofpacket => pr_controller_avmm_slave_agent_rsp_fifo_out_startofpacket, --          .startofpacket
			out_endofpacket   => pr_controller_avmm_slave_agent_rsp_fifo_out_endofpacket,   --          .endofpacket
			csr_address       => "00",                                                      -- (terminated)
			csr_read          => '0',                                                       -- (terminated)
			csr_write         => '0',                                                       -- (terminated)
			csr_readdata      => open,                                                      -- (terminated)
			csr_writedata     => "00000000000000000000000000000000",                        -- (terminated)
			almost_full_data  => open,                                                      -- (terminated)
			almost_empty_data => open,                                                      -- (terminated)
			in_empty          => "0",                                                       -- (terminated)
			out_empty         => open,                                                      -- (terminated)
			in_error          => "0",                                                       -- (terminated)
			out_error         => open,                                                      -- (terminated)
			in_channel        => "0",                                                       -- (terminated)
			out_channel       => open                                                       -- (terminated)
		);

	router : component PR_Test_Top_altera_merlin_router_1921_pfltgpa_cmp
		port map (
			sink_ready         => msgdma_pr_mm_write_agent_cp_ready,                --      sink.ready
			sink_valid         => msgdma_pr_mm_write_agent_cp_valid,                --          .valid
			sink_data          => msgdma_pr_mm_write_agent_cp_data,                 --          .data
			sink_startofpacket => msgdma_pr_mm_write_agent_cp_startofpacket,        --          .startofpacket
			sink_endofpacket   => msgdma_pr_mm_write_agent_cp_endofpacket,          --          .endofpacket
			clk                => clock_in_out_clk_clk,                             --       clk.clk
			reset              => pr_controller_nreset_reset_bridge_in_reset_reset, -- clk_reset.reset
			src_ready          => router_src_ready,                                 --       src.ready
			src_valid          => router_src_valid,                                 --          .valid
			src_data           => router_src_data,                                  --          .data
			src_channel        => router_src_channel,                               --          .channel
			src_startofpacket  => router_src_startofpacket,                         --          .startofpacket
			src_endofpacket    => router_src_endofpacket                            --          .endofpacket
		);

	router_001 : component PR_Test_Top_altera_merlin_router_1921_e4osxtq_cmp
		port map (
			sink_ready         => pr_controller_avmm_slave_agent_rp_ready,          --      sink.ready
			sink_valid         => pr_controller_avmm_slave_agent_rp_valid,          --          .valid
			sink_data          => pr_controller_avmm_slave_agent_rp_data,           --          .data
			sink_startofpacket => pr_controller_avmm_slave_agent_rp_startofpacket,  --          .startofpacket
			sink_endofpacket   => pr_controller_avmm_slave_agent_rp_endofpacket,    --          .endofpacket
			clk                => clock_in_out_clk_clk,                             --       clk.clk
			reset              => pr_controller_nreset_reset_bridge_in_reset_reset, -- clk_reset.reset
			src_ready          => router_001_src_ready,                             --       src.ready
			src_valid          => router_001_src_valid,                             --          .valid
			src_data           => router_001_src_data,                              --          .data
			src_channel        => router_001_src_channel,                           --          .channel
			src_startofpacket  => router_001_src_startofpacket,                     --          .startofpacket
			src_endofpacket    => router_001_src_endofpacket                        --          .endofpacket
		);

	pr_controller_avmm_slave_burst_adapter : component PR_Test_Top_altera_merlin_burst_adapter_1932_4owamsy_cmp
		generic map (
			PKT_ADDR_H                => 67,
			PKT_ADDR_L                => 36,
			PKT_BEGIN_BURST           => 86,
			PKT_BYTE_CNT_H            => 77,
			PKT_BYTE_CNT_L            => 74,
			PKT_BYTEEN_H              => 35,
			PKT_BYTEEN_L              => 32,
			PKT_BURST_SIZE_H          => 81,
			PKT_BURST_SIZE_L          => 79,
			PKT_BURST_TYPE_H          => 83,
			PKT_BURST_TYPE_L          => 82,
			PKT_BURSTWRAP_H           => 78,
			PKT_BURSTWRAP_L           => 78,
			PKT_SAI_H                 => 89,
			PKT_SAI_L                 => 89,
			ROLE_BASED_USER           => 0,
			PKT_TRANS_COMPRESSED_READ => 68,
			PKT_TRANS_WRITE           => 70,
			PKT_TRANS_READ            => 71,
			OUT_NARROW_SIZE           => 0,
			IN_NARROW_SIZE            => 0,
			OUT_FIXED                 => 0,
			OUT_COMPLETE_WRAP         => 0,
			PKT_EOP_OOO               => 89,
			PKT_SOP_OOO               => 90,
			ENABLE_OOO                => 0,
			ST_DATA_W                 => 127,
			ST_CHANNEL_W              => 1,
			OUT_BYTE_CNT_H            => 76,
			OUT_BURSTWRAP_H           => 78,
			COMPRESSED_READ_SUPPORT   => 1,
			BYTEENABLE_SYNTHESIS      => 1,
			PIPE_INPUTS               => 0,
			NO_WRAP_SUPPORT           => 0,
			INCOMPLETE_WRAP_SUPPORT   => 0,
			BURSTWRAP_CONST_MASK      => 1,
			BURSTWRAP_CONST_VALUE     => 1,
			ADAPTER_VERSION           => "13.1",
			SYNC_RESET                => 0
		)
		port map (
			clk                   => clock_in_out_clk_clk,                                         --       cr0.clk
			reset                 => pr_controller_nreset_reset_bridge_in_reset_reset,             -- cr0_reset.reset
			sink0_valid           => cmd_mux_src_valid,                                            --     sink0.valid
			sink0_data            => cmd_mux_src_data,                                             --          .data
			sink0_channel         => cmd_mux_src_channel,                                          --          .channel
			sink0_startofpacket   => cmd_mux_src_startofpacket,                                    --          .startofpacket
			sink0_endofpacket     => cmd_mux_src_endofpacket,                                      --          .endofpacket
			sink0_ready           => cmd_mux_src_ready,                                            --          .ready
			source0_valid         => pr_controller_avmm_slave_burst_adapter_source0_valid,         --   source0.valid
			source0_data          => pr_controller_avmm_slave_burst_adapter_source0_data,          --          .data
			source0_channel       => pr_controller_avmm_slave_burst_adapter_source0_channel,       --          .channel
			source0_startofpacket => pr_controller_avmm_slave_burst_adapter_source0_startofpacket, --          .startofpacket
			source0_endofpacket   => pr_controller_avmm_slave_burst_adapter_source0_endofpacket,   --          .endofpacket
			source0_ready         => pr_controller_avmm_slave_burst_adapter_source0_ready          --          .ready
		);

	cmd_demux : component PR_Test_Top_altera_merlin_demultiplexer_1921_4bpriii_cmp
		port map (
			clk                => clock_in_out_clk_clk,                             --       clk.clk
			reset              => pr_controller_nreset_reset_bridge_in_reset_reset, -- clk_reset.reset
			sink_ready         => router_src_ready,                                 --      sink.ready
			sink_channel       => router_src_channel,                               --          .channel
			sink_data          => router_src_data,                                  --          .data
			sink_startofpacket => router_src_startofpacket,                         --          .startofpacket
			sink_endofpacket   => router_src_endofpacket,                           --          .endofpacket
			sink_valid(0)      => router_src_valid,                                 --          .valid
			src0_ready         => cmd_demux_src0_ready,                             --      src0.ready
			src0_valid         => cmd_demux_src0_valid,                             --          .valid
			src0_data          => cmd_demux_src0_data,                              --          .data
			src0_channel       => cmd_demux_src0_channel,                           --          .channel
			src0_startofpacket => cmd_demux_src0_startofpacket,                     --          .startofpacket
			src0_endofpacket   => cmd_demux_src0_endofpacket                        --          .endofpacket
		);

	cmd_mux : component PR_Test_Top_altera_merlin_multiplexer_1922_huaylbq_cmp
		port map (
			clk                 => clock_in_out_clk_clk,                             --       clk.clk
			reset               => pr_controller_nreset_reset_bridge_in_reset_reset, -- clk_reset.reset
			src_ready           => cmd_mux_src_ready,                                --       src.ready
			src_valid           => cmd_mux_src_valid,                                --          .valid
			src_data            => cmd_mux_src_data,                                 --          .data
			src_channel         => cmd_mux_src_channel,                              --          .channel
			src_startofpacket   => cmd_mux_src_startofpacket,                        --          .startofpacket
			src_endofpacket     => cmd_mux_src_endofpacket,                          --          .endofpacket
			sink0_ready         => cmd_demux_src0_ready,                             --     sink0.ready
			sink0_valid         => cmd_demux_src0_valid,                             --          .valid
			sink0_channel       => cmd_demux_src0_channel,                           --          .channel
			sink0_data          => cmd_demux_src0_data,                              --          .data
			sink0_startofpacket => cmd_demux_src0_startofpacket,                     --          .startofpacket
			sink0_endofpacket   => cmd_demux_src0_endofpacket                        --          .endofpacket
		);

	rsp_demux : component PR_Test_Top_altera_merlin_demultiplexer_1921_4bpriii_cmp
		port map (
			clk                => clock_in_out_clk_clk,                             --       clk.clk
			reset              => pr_controller_nreset_reset_bridge_in_reset_reset, -- clk_reset.reset
			sink_ready         => router_001_src_ready,                             --      sink.ready
			sink_channel       => router_001_src_channel,                           --          .channel
			sink_data          => router_001_src_data,                              --          .data
			sink_startofpacket => router_001_src_startofpacket,                     --          .startofpacket
			sink_endofpacket   => router_001_src_endofpacket,                       --          .endofpacket
			sink_valid(0)      => router_001_src_valid,                             --          .valid
			src0_ready         => rsp_demux_src0_ready,                             --      src0.ready
			src0_valid         => rsp_demux_src0_valid,                             --          .valid
			src0_data          => rsp_demux_src0_data,                              --          .data
			src0_channel       => rsp_demux_src0_channel,                           --          .channel
			src0_startofpacket => rsp_demux_src0_startofpacket,                     --          .startofpacket
			src0_endofpacket   => rsp_demux_src0_endofpacket                        --          .endofpacket
		);

	rsp_mux : component PR_Test_Top_altera_merlin_multiplexer_1922_cterxoq_cmp
		port map (
			clk                 => clock_in_out_clk_clk,                             --       clk.clk
			reset               => pr_controller_nreset_reset_bridge_in_reset_reset, -- clk_reset.reset
			src_ready           => rsp_mux_src_ready,                                --       src.ready
			src_valid           => rsp_mux_src_valid,                                --          .valid
			src_data            => rsp_mux_src_data,                                 --          .data
			src_channel         => rsp_mux_src_channel,                              --          .channel
			src_startofpacket   => rsp_mux_src_startofpacket,                        --          .startofpacket
			src_endofpacket     => rsp_mux_src_endofpacket,                          --          .endofpacket
			sink0_ready         => rsp_demux_src0_ready,                             --     sink0.ready
			sink0_valid         => rsp_demux_src0_valid,                             --          .valid
			sink0_channel       => rsp_demux_src0_channel,                           --          .channel
			sink0_data          => rsp_demux_src0_data,                              --          .data
			sink0_startofpacket => rsp_demux_src0_startofpacket,                     --          .startofpacket
			sink0_endofpacket   => rsp_demux_src0_endofpacket                        --          .endofpacket
		);

end architecture rtl; -- of PR_Test_Top_altera_mm_interconnect_1920_lu2bh2a
