-- pr_test_top_altera_mm_interconnect_1920_ho7sqxa_intel_niosv_g_0_data_manager_translator.vhd

-- This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 24.1 115

library IEEE;
library altera_merlin_axi_translator_1950;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pr_test_top_altera_mm_interconnect_1920_ho7sqxa_intel_niosv_g_0_data_manager_translator is
	generic (
		USE_S0_AWID                       : integer := 0;
		USE_S0_AWREGION                   : integer := 0;
		USE_M0_AWREGION                   : integer := 1;
		USE_S0_AWLEN                      : integer := 1;
		USE_S0_AWSIZE                     : integer := 1;
		USE_S0_AWBURST                    : integer := 0;
		USE_S0_AWLOCK                     : integer := 0;
		USE_M0_AWLOCK                     : integer := 1;
		USE_S0_AWCACHE                    : integer := 0;
		USE_M0_AWCACHE                    : integer := 1;
		USE_M0_AWPROT                     : integer := 1;
		USE_S0_AWQOS                      : integer := 0;
		USE_M0_AWQOS                      : integer := 1;
		USE_S0_WSTRB                      : integer := 1;
		USE_M0_WLAST                      : integer := 1;
		USE_S0_BID                        : integer := 0;
		USE_S0_BRESP                      : integer := 1;
		USE_M0_BRESP                      : integer := 1;
		USE_S0_ARID                       : integer := 0;
		USE_S0_ARREGION                   : integer := 0;
		USE_M0_ARREGION                   : integer := 1;
		USE_S0_ARLEN                      : integer := 1;
		USE_S0_ARSIZE                     : integer := 1;
		USE_S0_ARBURST                    : integer := 0;
		USE_S0_ARLOCK                     : integer := 0;
		USE_M0_ARLOCK                     : integer := 1;
		USE_M0_ARCACHE                    : integer := 1;
		USE_M0_ARQOS                      : integer := 1;
		USE_M0_ARPROT                     : integer := 1;
		USE_S0_ARCACHE                    : integer := 0;
		USE_S0_ARQOS                      : integer := 0;
		USE_S0_RID                        : integer := 0;
		USE_S0_RRESP                      : integer := 1;
		USE_M0_RRESP                      : integer := 1;
		USE_S0_RLAST                      : integer := 1;
		M0_ID_WIDTH                       : integer := 1;
		DATA_WIDTH                        : integer := 32;
		M0_SAI_WIDTH                      : integer := 4;
		S0_SAI_WIDTH                      : integer := 4;
		USER_DATA_WIDTH                   : integer := 4;
		M0_USER_ADDRCHK_WIDTH             : integer := 4;
		S0_USER_ADDRCHK_WIDTH             : integer := 4;
		S0_ID_WIDTH                       : integer := 1;
		M0_ADDR_WIDTH                     : integer := 32;
		S0_WRITE_ADDR_USER_WIDTH          : integer := 1;
		S0_READ_ADDR_USER_WIDTH           : integer := 1;
		M0_WRITE_ADDR_USER_WIDTH          : integer := 1;
		M0_READ_ADDR_USER_WIDTH           : integer := 1;
		S0_WRITE_DATA_USER_WIDTH          : integer := 1;
		S0_WRITE_RESPONSE_DATA_USER_WIDTH : integer := 1;
		S0_READ_DATA_USER_WIDTH           : integer := 1;
		M0_WRITE_DATA_USER_WIDTH          : integer := 1;
		M0_WRITE_RESPONSE_DATA_USER_WIDTH : integer := 1;
		M0_READ_DATA_USER_WIDTH           : integer := 1;
		S0_ADDR_WIDTH                     : integer := 32;
		USE_S0_AWUSER                     : integer := 0;
		USE_S0_ARUSER                     : integer := 0;
		USE_S0_WUSER                      : integer := 0;
		USE_S0_RUSER                      : integer := 0;
		USE_S0_BUSER                      : integer := 0;
		USE_M0_AWUSER                     : integer := 1;
		USE_M0_ARUSER                     : integer := 1;
		USE_M0_WUSER                      : integer := 1;
		USE_M0_RUSER                      : integer := 1;
		USE_M0_BUSER                      : integer := 1;
		M0_AXI_VERSION                    : string  := "AXI4";
		M0_BURST_LENGTH_WIDTH             : integer := 8;
		S0_BURST_LENGTH_WIDTH             : integer := 8;
		M0_LOCK_WIDTH                     : integer := 1;
		S0_LOCK_WIDTH                     : integer := 1;
		S0_AXI_VERSION                    : string  := "AXI4";
		ACE_LITE_SUPPORT                  : integer := 0;
		USE_M0_AWUSER_ADDRCHK             : integer := 0;
		USE_M0_AWUSER_SAI                 : integer := 0;
		USE_M0_ARUSER_ADDRCHK             : integer := 0;
		USE_M0_ARUSER_SAI                 : integer := 0;
		USE_M0_WUSER_DATACHK              : integer := 0;
		USE_M0_WUSER_POISON               : integer := 0;
		USE_M0_RUSER_DATACHK              : integer := 0;
		USE_M0_RUSER_POISON               : integer := 0;
		USE_M0_WUSER_DATA                 : integer := 0;
		USE_M0_RUSER_DATA                 : integer := 0;
		USE_S0_AWUSER_ADDRCHK             : integer := 0;
		USE_S0_AWUSER_SAI                 : integer := 0;
		USE_S0_ARUSER_ADDRCHK             : integer := 0;
		USE_S0_ARUSER_SAI                 : integer := 0;
		USE_S0_WUSER_DATACHK              : integer := 0;
		USE_S0_WUSER_POISON               : integer := 0;
		USE_S0_RUSER_DATACHK              : integer := 0;
		USE_S0_WUSER_DATA                 : integer := 0;
		USE_S0_RUSER_DATA                 : integer := 0;
		USE_S0_RUSER_POISON               : integer := 0;
		REGENERATE_ADDRCHK                : integer := 0;
		ROLE_BASED_USER                   : integer := 0
	);
	port (
		aclk              : in  std_logic                     := '0';             --       clk.clk
		aresetn           : in  std_logic                     := '0';             -- clk_reset.reset_n
		m0_awid           : out std_logic_vector(0 downto 0);                     --        m0.awid
		m0_awaddr         : out std_logic_vector(31 downto 0);                    --          .awaddr
		m0_awlen          : out std_logic_vector(7 downto 0);                     --          .awlen
		m0_awsize         : out std_logic_vector(2 downto 0);                     --          .awsize
		m0_awburst        : out std_logic_vector(1 downto 0);                     --          .awburst
		m0_awlock         : out std_logic_vector(0 downto 0);                     --          .awlock
		m0_awcache        : out std_logic_vector(3 downto 0);                     --          .awcache
		m0_awprot         : out std_logic_vector(2 downto 0);                     --          .awprot
		m0_awuser         : out std_logic_vector(0 downto 0);                     --          .awuser
		m0_awqos          : out std_logic_vector(3 downto 0);                     --          .awqos
		m0_awregion       : out std_logic_vector(3 downto 0);                     --          .awregion
		m0_awvalid        : out std_logic;                                        --          .awvalid
		m0_awready        : in  std_logic                     := '0';             --          .awready
		m0_wdata          : out std_logic_vector(31 downto 0);                    --          .wdata
		m0_wstrb          : out std_logic_vector(3 downto 0);                     --          .wstrb
		m0_wlast          : out std_logic;                                        --          .wlast
		m0_wvalid         : out std_logic;                                        --          .wvalid
		m0_wuser          : out std_logic_vector(0 downto 0);                     --          .wuser
		m0_wready         : in  std_logic                     := '0';             --          .wready
		m0_bid            : in  std_logic_vector(0 downto 0)  := (others => '0'); --          .bid
		m0_bresp          : in  std_logic_vector(1 downto 0)  := (others => '0'); --          .bresp
		m0_buser          : in  std_logic_vector(0 downto 0)  := (others => '0'); --          .buser
		m0_bvalid         : in  std_logic                     := '0';             --          .bvalid
		m0_bready         : out std_logic;                                        --          .bready
		m0_arid           : out std_logic_vector(0 downto 0);                     --          .arid
		m0_araddr         : out std_logic_vector(31 downto 0);                    --          .araddr
		m0_arlen          : out std_logic_vector(7 downto 0);                     --          .arlen
		m0_arsize         : out std_logic_vector(2 downto 0);                     --          .arsize
		m0_arburst        : out std_logic_vector(1 downto 0);                     --          .arburst
		m0_arlock         : out std_logic_vector(0 downto 0);                     --          .arlock
		m0_arcache        : out std_logic_vector(3 downto 0);                     --          .arcache
		m0_arprot         : out std_logic_vector(2 downto 0);                     --          .arprot
		m0_aruser         : out std_logic_vector(0 downto 0);                     --          .aruser
		m0_arqos          : out std_logic_vector(3 downto 0);                     --          .arqos
		m0_arregion       : out std_logic_vector(3 downto 0);                     --          .arregion
		m0_arvalid        : out std_logic;                                        --          .arvalid
		m0_arready        : in  std_logic                     := '0';             --          .arready
		m0_rid            : in  std_logic_vector(0 downto 0)  := (others => '0'); --          .rid
		m0_rdata          : in  std_logic_vector(31 downto 0) := (others => '0'); --          .rdata
		m0_rresp          : in  std_logic_vector(1 downto 0)  := (others => '0'); --          .rresp
		m0_rlast          : in  std_logic                     := '0';             --          .rlast
		m0_rvalid         : in  std_logic                     := '0';             --          .rvalid
		m0_rready         : out std_logic;                                        --          .rready
		m0_ruser          : in  std_logic_vector(0 downto 0)  := (others => '0'); --          .ruser
		s0_awaddr         : in  std_logic_vector(31 downto 0) := (others => '0'); --        s0.awaddr
		s0_awlen          : in  std_logic_vector(7 downto 0)  := (others => '0'); --          .awlen
		s0_awsize         : in  std_logic_vector(2 downto 0)  := (others => '0'); --          .awsize
		s0_awprot         : in  std_logic_vector(2 downto 0)  := (others => '0'); --          .awprot
		s0_awvalid        : in  std_logic                     := '0';             --          .awvalid
		s0_awready        : out std_logic;                                        --          .awready
		s0_wdata          : in  std_logic_vector(31 downto 0) := (others => '0'); --          .wdata
		s0_wstrb          : in  std_logic_vector(3 downto 0)  := (others => '0'); --          .wstrb
		s0_wlast          : in  std_logic                     := '0';             --          .wlast
		s0_wvalid         : in  std_logic                     := '0';             --          .wvalid
		s0_wready         : out std_logic;                                        --          .wready
		s0_bresp          : out std_logic_vector(1 downto 0);                     --          .bresp
		s0_bvalid         : out std_logic;                                        --          .bvalid
		s0_bready         : in  std_logic                     := '0';             --          .bready
		s0_araddr         : in  std_logic_vector(31 downto 0) := (others => '0'); --          .araddr
		s0_arlen          : in  std_logic_vector(7 downto 0)  := (others => '0'); --          .arlen
		s0_arsize         : in  std_logic_vector(2 downto 0)  := (others => '0'); --          .arsize
		s0_arprot         : in  std_logic_vector(2 downto 0)  := (others => '0'); --          .arprot
		s0_arvalid        : in  std_logic                     := '0';             --          .arvalid
		s0_arready        : out std_logic;                                        --          .arready
		s0_rdata          : out std_logic_vector(31 downto 0);                    --          .rdata
		s0_rresp          : out std_logic_vector(1 downto 0);                     --          .rresp
		s0_rlast          : out std_logic;                                        --          .rlast
		s0_rvalid         : out std_logic;                                        --          .rvalid
		s0_rready         : in  std_logic                     := '0';             --          .rready
		m0_arbar          : out std_logic_vector(1 downto 0);
		m0_ardomain       : out std_logic_vector(1 downto 0);
		m0_arsnoop        : out std_logic_vector(3 downto 0);
		m0_aruser_addrchk : out std_logic_vector(3 downto 0);
		m0_aruser_sai     : out std_logic_vector(3 downto 0);
		m0_awbar          : out std_logic_vector(1 downto 0);
		m0_awdomain       : out std_logic_vector(1 downto 0);
		m0_awsnoop        : out std_logic_vector(2 downto 0);
		m0_awunique       : out std_logic_vector(0 downto 0);
		m0_awuser_addrchk : out std_logic_vector(3 downto 0);
		m0_awuser_sai     : out std_logic_vector(3 downto 0);
		m0_ruser_data     : in  std_logic_vector(3 downto 0)  := (others => '0');
		m0_ruser_datachk  : in  std_logic_vector(3 downto 0)  := (others => '0');
		m0_ruser_poison   : in  std_logic_vector(0 downto 0)  := (others => '0');
		m0_wid            : out std_logic_vector(0 downto 0);
		m0_wuser_data     : out std_logic_vector(3 downto 0);
		m0_wuser_datachk  : out std_logic_vector(3 downto 0);
		m0_wuser_poison   : out std_logic_vector(0 downto 0);
		s0_arbar          : in  std_logic_vector(1 downto 0)  := (others => '0');
		s0_arburst        : in  std_logic_vector(1 downto 0)  := (others => '0');
		s0_arcache        : in  std_logic_vector(3 downto 0)  := (others => '0');
		s0_ardomain       : in  std_logic_vector(1 downto 0)  := (others => '0');
		s0_arid           : in  std_logic_vector(0 downto 0)  := (others => '0');
		s0_arlock         : in  std_logic_vector(0 downto 0)  := (others => '0');
		s0_arqos          : in  std_logic_vector(3 downto 0)  := (others => '0');
		s0_arregion       : in  std_logic_vector(3 downto 0)  := (others => '0');
		s0_arsnoop        : in  std_logic_vector(3 downto 0)  := (others => '0');
		s0_aruser         : in  std_logic_vector(0 downto 0)  := (others => '0');
		s0_aruser_addrchk : in  std_logic_vector(3 downto 0)  := (others => '0');
		s0_aruser_sai     : in  std_logic_vector(3 downto 0)  := (others => '0');
		s0_awbar          : in  std_logic_vector(1 downto 0)  := (others => '0');
		s0_awburst        : in  std_logic_vector(1 downto 0)  := (others => '0');
		s0_awcache        : in  std_logic_vector(3 downto 0)  := (others => '0');
		s0_awdomain       : in  std_logic_vector(1 downto 0)  := (others => '0');
		s0_awid           : in  std_logic_vector(0 downto 0)  := (others => '0');
		s0_awlock         : in  std_logic_vector(0 downto 0)  := (others => '0');
		s0_awqos          : in  std_logic_vector(3 downto 0)  := (others => '0');
		s0_awregion       : in  std_logic_vector(3 downto 0)  := (others => '0');
		s0_awsnoop        : in  std_logic_vector(2 downto 0)  := (others => '0');
		s0_awunique       : in  std_logic_vector(0 downto 0)  := (others => '0');
		s0_awuser         : in  std_logic_vector(0 downto 0)  := (others => '0');
		s0_awuser_addrchk : in  std_logic_vector(3 downto 0)  := (others => '0');
		s0_awuser_sai     : in  std_logic_vector(3 downto 0)  := (others => '0');
		s0_bid            : out std_logic_vector(0 downto 0);
		s0_buser          : out std_logic_vector(0 downto 0);
		s0_rid            : out std_logic_vector(0 downto 0);
		s0_ruser          : out std_logic_vector(0 downto 0);
		s0_ruser_data     : out std_logic_vector(3 downto 0);
		s0_ruser_datachk  : out std_logic_vector(3 downto 0);
		s0_ruser_poison   : out std_logic_vector(0 downto 0);
		s0_wid            : in  std_logic_vector(0 downto 0)  := (others => '0');
		s0_wuser          : in  std_logic_vector(0 downto 0)  := (others => '0');
		s0_wuser_data     : in  std_logic_vector(3 downto 0)  := (others => '0');
		s0_wuser_datachk  : in  std_logic_vector(3 downto 0)  := (others => '0');
		s0_wuser_poison   : in  std_logic_vector(0 downto 0)  := (others => '0')
	);
end entity pr_test_top_altera_mm_interconnect_1920_ho7sqxa_intel_niosv_g_0_data_manager_translator;

architecture rtl of pr_test_top_altera_mm_interconnect_1920_ho7sqxa_intel_niosv_g_0_data_manager_translator is
	component PR_Test_Top_altera_merlin_axi_translator_1950_sjnedva_cmp is
		generic (
			USE_S0_AWID                       : integer := 1;
			USE_S0_AWREGION                   : integer := 0;
			USE_M0_AWREGION                   : integer := 1;
			USE_S0_AWLEN                      : integer := 1;
			USE_S0_AWSIZE                     : integer := 1;
			USE_S0_AWBURST                    : integer := 1;
			USE_S0_AWLOCK                     : integer := 1;
			USE_M0_AWLOCK                     : integer := 1;
			USE_S0_AWCACHE                    : integer := 1;
			USE_M0_AWCACHE                    : integer := 1;
			USE_M0_AWPROT                     : integer := 1;
			USE_S0_AWQOS                      : integer := 0;
			USE_M0_AWQOS                      : integer := 1;
			USE_S0_WSTRB                      : integer := 1;
			USE_M0_WLAST                      : integer := 1;
			USE_S0_BID                        : integer := 1;
			USE_S0_BRESP                      : integer := 1;
			USE_M0_BRESP                      : integer := 1;
			USE_S0_ARID                       : integer := 1;
			USE_S0_ARREGION                   : integer := 0;
			USE_M0_ARREGION                   : integer := 1;
			USE_S0_ARLEN                      : integer := 1;
			USE_S0_ARSIZE                     : integer := 1;
			USE_S0_ARBURST                    : integer := 1;
			USE_S0_ARLOCK                     : integer := 1;
			USE_M0_ARLOCK                     : integer := 1;
			USE_M0_ARCACHE                    : integer := 1;
			USE_M0_ARQOS                      : integer := 1;
			USE_M0_ARPROT                     : integer := 1;
			USE_S0_ARCACHE                    : integer := 1;
			USE_S0_ARQOS                      : integer := 0;
			USE_S0_RID                        : integer := 1;
			USE_S0_RRESP                      : integer := 1;
			USE_M0_RRESP                      : integer := 1;
			USE_S0_RLAST                      : integer := 1;
			M0_ID_WIDTH                       : integer := 8;
			DATA_WIDTH                        : integer := 32;
			M0_SAI_WIDTH                      : integer := 4;
			S0_SAI_WIDTH                      : integer := 4;
			USER_DATA_WIDTH                   : integer := 4;
			M0_USER_ADDRCHK_WIDTH             : integer := 4;
			S0_USER_ADDRCHK_WIDTH             : integer := 4;
			S0_ID_WIDTH                       : integer := 4;
			M0_ADDR_WIDTH                     : integer := 12;
			S0_WRITE_ADDR_USER_WIDTH          : integer := 64;
			S0_READ_ADDR_USER_WIDTH           : integer := 64;
			M0_WRITE_ADDR_USER_WIDTH          : integer := 64;
			M0_READ_ADDR_USER_WIDTH           : integer := 64;
			S0_WRITE_DATA_USER_WIDTH          : integer := 64;
			S0_WRITE_RESPONSE_DATA_USER_WIDTH : integer := 64;
			S0_READ_DATA_USER_WIDTH           : integer := 64;
			M0_WRITE_DATA_USER_WIDTH          : integer := 64;
			M0_WRITE_RESPONSE_DATA_USER_WIDTH : integer := 64;
			M0_READ_DATA_USER_WIDTH           : integer := 64;
			S0_ADDR_WIDTH                     : integer := 11;
			USE_S0_AWUSER                     : integer := 0;
			USE_S0_ARUSER                     : integer := 0;
			USE_S0_WUSER                      : integer := 0;
			USE_S0_RUSER                      : integer := 0;
			USE_S0_BUSER                      : integer := 0;
			USE_M0_AWUSER                     : integer := 0;
			USE_M0_ARUSER                     : integer := 0;
			USE_M0_WUSER                      : integer := 0;
			USE_M0_RUSER                      : integer := 0;
			USE_M0_BUSER                      : integer := 0;
			M0_AXI_VERSION                    : string  := "AXI3";
			M0_BURST_LENGTH_WIDTH             : integer := 4;
			S0_BURST_LENGTH_WIDTH             : integer := 4;
			M0_LOCK_WIDTH                     : integer := 2;
			S0_LOCK_WIDTH                     : integer := 2;
			S0_AXI_VERSION                    : string  := "AXI3";
			ACE_LITE_SUPPORT                  : integer := 0;
			USE_M0_AWUSER_ADDRCHK             : integer := 0;
			USE_M0_AWUSER_SAI                 : integer := 0;
			USE_M0_ARUSER_ADDRCHK             : integer := 0;
			USE_M0_ARUSER_SAI                 : integer := 0;
			USE_M0_WUSER_DATACHK              : integer := 0;
			USE_M0_WUSER_POISON               : integer := 0;
			USE_M0_RUSER_DATACHK              : integer := 0;
			USE_M0_RUSER_POISON               : integer := 0;
			USE_M0_WUSER_DATA                 : integer := 0;
			USE_M0_RUSER_DATA                 : integer := 0;
			USE_S0_AWUSER_ADDRCHK             : integer := 0;
			USE_S0_AWUSER_SAI                 : integer := 0;
			USE_S0_ARUSER_ADDRCHK             : integer := 0;
			USE_S0_ARUSER_SAI                 : integer := 0;
			USE_S0_WUSER_DATACHK              : integer := 0;
			USE_S0_WUSER_POISON               : integer := 0;
			USE_S0_RUSER_DATACHK              : integer := 0;
			USE_S0_WUSER_DATA                 : integer := 0;
			USE_S0_RUSER_DATA                 : integer := 0;
			USE_S0_RUSER_POISON               : integer := 0;
			REGENERATE_ADDRCHK                : integer := 0;
			ROLE_BASED_USER                   : integer := 0
		);
		port (
			aclk              : in  std_logic                     := 'X';             -- clk
			aresetn           : in  std_logic                     := 'X';             -- reset_n
			m0_awid           : out std_logic_vector(0 downto 0);                     -- awid
			m0_awaddr         : out std_logic_vector(31 downto 0);                    -- awaddr
			m0_awlen          : out std_logic_vector(7 downto 0);                     -- awlen
			m0_awsize         : out std_logic_vector(2 downto 0);                     -- awsize
			m0_awburst        : out std_logic_vector(1 downto 0);                     -- awburst
			m0_awlock         : out std_logic_vector(0 downto 0);                     -- awlock
			m0_awcache        : out std_logic_vector(3 downto 0);                     -- awcache
			m0_awprot         : out std_logic_vector(2 downto 0);                     -- awprot
			m0_awuser         : out std_logic_vector(0 downto 0);                     -- awuser
			m0_awqos          : out std_logic_vector(3 downto 0);                     -- awqos
			m0_awregion       : out std_logic_vector(3 downto 0);                     -- awregion
			m0_awvalid        : out std_logic;                                        -- awvalid
			m0_awready        : in  std_logic                     := 'X';             -- awready
			m0_wdata          : out std_logic_vector(31 downto 0);                    -- wdata
			m0_wstrb          : out std_logic_vector(3 downto 0);                     -- wstrb
			m0_wlast          : out std_logic;                                        -- wlast
			m0_wvalid         : out std_logic;                                        -- wvalid
			m0_wuser          : out std_logic_vector(0 downto 0);                     -- wuser
			m0_wready         : in  std_logic                     := 'X';             -- wready
			m0_bid            : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- bid
			m0_bresp          : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- bresp
			m0_buser          : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- buser
			m0_bvalid         : in  std_logic                     := 'X';             -- bvalid
			m0_bready         : out std_logic;                                        -- bready
			m0_arid           : out std_logic_vector(0 downto 0);                     -- arid
			m0_araddr         : out std_logic_vector(31 downto 0);                    -- araddr
			m0_arlen          : out std_logic_vector(7 downto 0);                     -- arlen
			m0_arsize         : out std_logic_vector(2 downto 0);                     -- arsize
			m0_arburst        : out std_logic_vector(1 downto 0);                     -- arburst
			m0_arlock         : out std_logic_vector(0 downto 0);                     -- arlock
			m0_arcache        : out std_logic_vector(3 downto 0);                     -- arcache
			m0_arprot         : out std_logic_vector(2 downto 0);                     -- arprot
			m0_aruser         : out std_logic_vector(0 downto 0);                     -- aruser
			m0_arqos          : out std_logic_vector(3 downto 0);                     -- arqos
			m0_arregion       : out std_logic_vector(3 downto 0);                     -- arregion
			m0_arvalid        : out std_logic;                                        -- arvalid
			m0_arready        : in  std_logic                     := 'X';             -- arready
			m0_rid            : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- rid
			m0_rdata          : in  std_logic_vector(31 downto 0) := (others => 'X'); -- rdata
			m0_rresp          : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- rresp
			m0_rlast          : in  std_logic                     := 'X';             -- rlast
			m0_rvalid         : in  std_logic                     := 'X';             -- rvalid
			m0_rready         : out std_logic;                                        -- rready
			m0_ruser          : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- ruser
			s0_awaddr         : in  std_logic_vector(31 downto 0) := (others => 'X'); -- awaddr
			s0_awlen          : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- awlen
			s0_awsize         : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- awsize
			s0_awprot         : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- awprot
			s0_awvalid        : in  std_logic                     := 'X';             -- awvalid
			s0_awready        : out std_logic;                                        -- awready
			s0_wdata          : in  std_logic_vector(31 downto 0) := (others => 'X'); -- wdata
			s0_wstrb          : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- wstrb
			s0_wlast          : in  std_logic                     := 'X';             -- wlast
			s0_wvalid         : in  std_logic                     := 'X';             -- wvalid
			s0_wready         : out std_logic;                                        -- wready
			s0_bresp          : out std_logic_vector(1 downto 0);                     -- bresp
			s0_bvalid         : out std_logic;                                        -- bvalid
			s0_bready         : in  std_logic                     := 'X';             -- bready
			s0_araddr         : in  std_logic_vector(31 downto 0) := (others => 'X'); -- araddr
			s0_arlen          : in  std_logic_vector(7 downto 0)  := (others => 'X'); -- arlen
			s0_arsize         : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- arsize
			s0_arprot         : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- arprot
			s0_arvalid        : in  std_logic                     := 'X';             -- arvalid
			s0_arready        : out std_logic;                                        -- arready
			s0_rdata          : out std_logic_vector(31 downto 0);                    -- rdata
			s0_rresp          : out std_logic_vector(1 downto 0);                     -- rresp
			s0_rlast          : out std_logic;                                        -- rlast
			s0_rvalid         : out std_logic;                                        -- rvalid
			s0_rready         : in  std_logic                     := 'X';             -- rready
			m0_awuser_addrchk : out std_logic_vector(3 downto 0);                     -- awaddrchk
			m0_awuser_sai     : out std_logic_vector(3 downto 0);                     -- awsai
			m0_wuser_datachk  : out std_logic_vector(3 downto 0);                     -- wdatachk
			m0_wuser_data     : out std_logic_vector(3 downto 0);                     -- wuserdata
			m0_wuser_poison   : out std_logic_vector(0 downto 0);                     -- wpoison
			m0_aruser_addrchk : out std_logic_vector(3 downto 0);                     -- araddrchk
			m0_aruser_sai     : out std_logic_vector(3 downto 0);                     -- arsai
			m0_ruser_datachk  : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- rdatachk
			m0_ruser_data     : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- ruserdata
			m0_ruser_poison   : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- rpoison
			s0_awid           : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- awid
			s0_awburst        : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- awburst
			s0_awlock         : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- awlock
			s0_awcache        : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- awcache
			s0_awuser         : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- awuser
			s0_awuser_addrchk : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- awaddrchk
			s0_awuser_sai     : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- awsai
			s0_awqos          : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- awqos
			s0_awregion       : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- awregion
			s0_wuser          : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- wuser
			s0_wuser_datachk  : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- wdatachk
			s0_wuser_data     : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- wuserdata
			s0_wuser_poison   : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- wpoison
			s0_bid            : out std_logic_vector(0 downto 0);                     -- bid
			s0_buser          : out std_logic_vector(0 downto 0);                     -- buser
			s0_arid           : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- arid
			s0_arburst        : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- arburst
			s0_arlock         : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- arlock
			s0_arcache        : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- arcache
			s0_aruser         : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- aruser
			s0_aruser_addrchk : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- araddrchk
			s0_aruser_sai     : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- arsai
			s0_arqos          : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- arqos
			s0_arregion       : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- arregion
			s0_rid            : out std_logic_vector(0 downto 0);                     -- rid
			s0_ruser          : out std_logic_vector(0 downto 0);                     -- ruser
			s0_ruser_datachk  : out std_logic_vector(3 downto 0);                     -- rdatachk
			s0_ruser_data     : out std_logic_vector(3 downto 0);                     -- ruserdata
			s0_ruser_poison   : out std_logic_vector(0 downto 0);                     -- rpoison
			s0_wid            : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- s0_wid
			s0_ardomain       : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- s0_ardomain
			s0_arsnoop        : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- s0_arsnoop
			s0_arbar          : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- s0_arbar
			s0_awdomain       : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- s0_awdomain
			s0_awsnoop        : in  std_logic_vector(2 downto 0)  := (others => 'X'); -- s0_awsnoop
			s0_awbar          : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- s0_awbar
			s0_awunique       : in  std_logic_vector(0 downto 0)  := (others => 'X'); -- s0_awunique
			m0_wid            : out std_logic_vector(0 downto 0);                     -- m0_wid
			m0_ardomain       : out std_logic_vector(1 downto 0);                     -- m0_ardomain
			m0_arsnoop        : out std_logic_vector(3 downto 0);                     -- m0_arsnoop
			m0_arbar          : out std_logic_vector(1 downto 0);                     -- m0_arbar
			m0_awdomain       : out std_logic_vector(1 downto 0);                     -- m0_awdomain
			m0_awsnoop        : out std_logic_vector(2 downto 0);                     -- m0_awsnoop
			m0_awbar          : out std_logic_vector(1 downto 0);                     -- m0_awbar
			m0_awunique       : out std_logic_vector(0 downto 0)                      -- m0_awunique
		);
	end component PR_Test_Top_altera_merlin_axi_translator_1950_sjnedva_cmp;

	for intel_niosv_g_0_data_manager_translator : PR_Test_Top_altera_merlin_axi_translator_1950_sjnedva_cmp
		use entity altera_merlin_axi_translator_1950.PR_Test_Top_altera_merlin_axi_translator_1950_sjnedva;
begin

	m0_burst_length_width_check : if M0_BURST_LENGTH_WIDTH /= 8 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	s0_burst_length_width_check : if S0_BURST_LENGTH_WIDTH /= 8 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	m0_lock_width_check : if M0_LOCK_WIDTH /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	s0_lock_width_check : if S0_LOCK_WIDTH /= 1 generate
		assert false report "Supplied generics do not match expected generics" severity Failure;
	end generate;

	intel_niosv_g_0_data_manager_translator : component PR_Test_Top_altera_merlin_axi_translator_1950_sjnedva_cmp
		generic map (
			USE_S0_AWID                       => USE_S0_AWID,
			USE_S0_AWREGION                   => USE_S0_AWREGION,
			USE_M0_AWREGION                   => USE_M0_AWREGION,
			USE_S0_AWLEN                      => USE_S0_AWLEN,
			USE_S0_AWSIZE                     => USE_S0_AWSIZE,
			USE_S0_AWBURST                    => USE_S0_AWBURST,
			USE_S0_AWLOCK                     => USE_S0_AWLOCK,
			USE_M0_AWLOCK                     => USE_M0_AWLOCK,
			USE_S0_AWCACHE                    => USE_S0_AWCACHE,
			USE_M0_AWCACHE                    => USE_M0_AWCACHE,
			USE_M0_AWPROT                     => USE_M0_AWPROT,
			USE_S0_AWQOS                      => USE_S0_AWQOS,
			USE_M0_AWQOS                      => USE_M0_AWQOS,
			USE_S0_WSTRB                      => USE_S0_WSTRB,
			USE_M0_WLAST                      => USE_M0_WLAST,
			USE_S0_BID                        => USE_S0_BID,
			USE_S0_BRESP                      => USE_S0_BRESP,
			USE_M0_BRESP                      => USE_M0_BRESP,
			USE_S0_ARID                       => USE_S0_ARID,
			USE_S0_ARREGION                   => USE_S0_ARREGION,
			USE_M0_ARREGION                   => USE_M0_ARREGION,
			USE_S0_ARLEN                      => USE_S0_ARLEN,
			USE_S0_ARSIZE                     => USE_S0_ARSIZE,
			USE_S0_ARBURST                    => USE_S0_ARBURST,
			USE_S0_ARLOCK                     => USE_S0_ARLOCK,
			USE_M0_ARLOCK                     => USE_M0_ARLOCK,
			USE_M0_ARCACHE                    => USE_M0_ARCACHE,
			USE_M0_ARQOS                      => USE_M0_ARQOS,
			USE_M0_ARPROT                     => USE_M0_ARPROT,
			USE_S0_ARCACHE                    => USE_S0_ARCACHE,
			USE_S0_ARQOS                      => USE_S0_ARQOS,
			USE_S0_RID                        => USE_S0_RID,
			USE_S0_RRESP                      => USE_S0_RRESP,
			USE_M0_RRESP                      => USE_M0_RRESP,
			USE_S0_RLAST                      => USE_S0_RLAST,
			M0_ID_WIDTH                       => M0_ID_WIDTH,
			DATA_WIDTH                        => DATA_WIDTH,
			M0_SAI_WIDTH                      => M0_SAI_WIDTH,
			S0_SAI_WIDTH                      => S0_SAI_WIDTH,
			USER_DATA_WIDTH                   => USER_DATA_WIDTH,
			M0_USER_ADDRCHK_WIDTH             => M0_USER_ADDRCHK_WIDTH,
			S0_USER_ADDRCHK_WIDTH             => S0_USER_ADDRCHK_WIDTH,
			S0_ID_WIDTH                       => S0_ID_WIDTH,
			M0_ADDR_WIDTH                     => M0_ADDR_WIDTH,
			S0_WRITE_ADDR_USER_WIDTH          => S0_WRITE_ADDR_USER_WIDTH,
			S0_READ_ADDR_USER_WIDTH           => S0_READ_ADDR_USER_WIDTH,
			M0_WRITE_ADDR_USER_WIDTH          => M0_WRITE_ADDR_USER_WIDTH,
			M0_READ_ADDR_USER_WIDTH           => M0_READ_ADDR_USER_WIDTH,
			S0_WRITE_DATA_USER_WIDTH          => S0_WRITE_DATA_USER_WIDTH,
			S0_WRITE_RESPONSE_DATA_USER_WIDTH => S0_WRITE_RESPONSE_DATA_USER_WIDTH,
			S0_READ_DATA_USER_WIDTH           => S0_READ_DATA_USER_WIDTH,
			M0_WRITE_DATA_USER_WIDTH          => M0_WRITE_DATA_USER_WIDTH,
			M0_WRITE_RESPONSE_DATA_USER_WIDTH => M0_WRITE_RESPONSE_DATA_USER_WIDTH,
			M0_READ_DATA_USER_WIDTH           => M0_READ_DATA_USER_WIDTH,
			S0_ADDR_WIDTH                     => S0_ADDR_WIDTH,
			USE_S0_AWUSER                     => USE_S0_AWUSER,
			USE_S0_ARUSER                     => USE_S0_ARUSER,
			USE_S0_WUSER                      => USE_S0_WUSER,
			USE_S0_RUSER                      => USE_S0_RUSER,
			USE_S0_BUSER                      => USE_S0_BUSER,
			USE_M0_AWUSER                     => USE_M0_AWUSER,
			USE_M0_ARUSER                     => USE_M0_ARUSER,
			USE_M0_WUSER                      => USE_M0_WUSER,
			USE_M0_RUSER                      => USE_M0_RUSER,
			USE_M0_BUSER                      => USE_M0_BUSER,
			M0_AXI_VERSION                    => M0_AXI_VERSION,
			M0_BURST_LENGTH_WIDTH             => 8,
			S0_BURST_LENGTH_WIDTH             => 8,
			M0_LOCK_WIDTH                     => 1,
			S0_LOCK_WIDTH                     => 1,
			S0_AXI_VERSION                    => S0_AXI_VERSION,
			ACE_LITE_SUPPORT                  => ACE_LITE_SUPPORT,
			USE_M0_AWUSER_ADDRCHK             => USE_M0_AWUSER_ADDRCHK,
			USE_M0_AWUSER_SAI                 => USE_M0_AWUSER_SAI,
			USE_M0_ARUSER_ADDRCHK             => USE_M0_ARUSER_ADDRCHK,
			USE_M0_ARUSER_SAI                 => USE_M0_ARUSER_SAI,
			USE_M0_WUSER_DATACHK              => USE_M0_WUSER_DATACHK,
			USE_M0_WUSER_POISON               => USE_M0_WUSER_POISON,
			USE_M0_RUSER_DATACHK              => USE_M0_RUSER_DATACHK,
			USE_M0_RUSER_POISON               => USE_M0_RUSER_POISON,
			USE_M0_WUSER_DATA                 => USE_M0_WUSER_DATA,
			USE_M0_RUSER_DATA                 => USE_M0_RUSER_DATA,
			USE_S0_AWUSER_ADDRCHK             => USE_S0_AWUSER_ADDRCHK,
			USE_S0_AWUSER_SAI                 => USE_S0_AWUSER_SAI,
			USE_S0_ARUSER_ADDRCHK             => USE_S0_ARUSER_ADDRCHK,
			USE_S0_ARUSER_SAI                 => USE_S0_ARUSER_SAI,
			USE_S0_WUSER_DATACHK              => USE_S0_WUSER_DATACHK,
			USE_S0_WUSER_POISON               => USE_S0_WUSER_POISON,
			USE_S0_RUSER_DATACHK              => USE_S0_RUSER_DATACHK,
			USE_S0_WUSER_DATA                 => USE_S0_WUSER_DATA,
			USE_S0_RUSER_DATA                 => USE_S0_RUSER_DATA,
			USE_S0_RUSER_POISON               => USE_S0_RUSER_POISON,
			REGENERATE_ADDRCHK                => REGENERATE_ADDRCHK,
			ROLE_BASED_USER                   => ROLE_BASED_USER
		)
		port map (
			aclk              => aclk,        --       clk.clk
			aresetn           => aresetn,     -- clk_reset.reset_n
			m0_awid           => m0_awid,     --        m0.awid
			m0_awaddr         => m0_awaddr,   --          .awaddr
			m0_awlen          => m0_awlen,    --          .awlen
			m0_awsize         => m0_awsize,   --          .awsize
			m0_awburst        => m0_awburst,  --          .awburst
			m0_awlock         => m0_awlock,   --          .awlock
			m0_awcache        => m0_awcache,  --          .awcache
			m0_awprot         => m0_awprot,   --          .awprot
			m0_awuser         => m0_awuser,   --          .awuser
			m0_awqos          => m0_awqos,    --          .awqos
			m0_awregion       => m0_awregion, --          .awregion
			m0_awvalid        => m0_awvalid,  --          .awvalid
			m0_awready        => m0_awready,  --          .awready
			m0_wdata          => m0_wdata,    --          .wdata
			m0_wstrb          => m0_wstrb,    --          .wstrb
			m0_wlast          => m0_wlast,    --          .wlast
			m0_wvalid         => m0_wvalid,   --          .wvalid
			m0_wuser          => m0_wuser,    --          .wuser
			m0_wready         => m0_wready,   --          .wready
			m0_bid            => m0_bid,      --          .bid
			m0_bresp          => m0_bresp,    --          .bresp
			m0_buser          => m0_buser,    --          .buser
			m0_bvalid         => m0_bvalid,   --          .bvalid
			m0_bready         => m0_bready,   --          .bready
			m0_arid           => m0_arid,     --          .arid
			m0_araddr         => m0_araddr,   --          .araddr
			m0_arlen          => m0_arlen,    --          .arlen
			m0_arsize         => m0_arsize,   --          .arsize
			m0_arburst        => m0_arburst,  --          .arburst
			m0_arlock         => m0_arlock,   --          .arlock
			m0_arcache        => m0_arcache,  --          .arcache
			m0_arprot         => m0_arprot,   --          .arprot
			m0_aruser         => m0_aruser,   --          .aruser
			m0_arqos          => m0_arqos,    --          .arqos
			m0_arregion       => m0_arregion, --          .arregion
			m0_arvalid        => m0_arvalid,  --          .arvalid
			m0_arready        => m0_arready,  --          .arready
			m0_rid            => m0_rid,      --          .rid
			m0_rdata          => m0_rdata,    --          .rdata
			m0_rresp          => m0_rresp,    --          .rresp
			m0_rlast          => m0_rlast,    --          .rlast
			m0_rvalid         => m0_rvalid,   --          .rvalid
			m0_rready         => m0_rready,   --          .rready
			m0_ruser          => m0_ruser,    --          .ruser
			s0_awaddr         => s0_awaddr,   --        s0.awaddr
			s0_awlen          => s0_awlen,    --          .awlen
			s0_awsize         => s0_awsize,   --          .awsize
			s0_awprot         => s0_awprot,   --          .awprot
			s0_awvalid        => s0_awvalid,  --          .awvalid
			s0_awready        => s0_awready,  --          .awready
			s0_wdata          => s0_wdata,    --          .wdata
			s0_wstrb          => s0_wstrb,    --          .wstrb
			s0_wlast          => s0_wlast,    --          .wlast
			s0_wvalid         => s0_wvalid,   --          .wvalid
			s0_wready         => s0_wready,   --          .wready
			s0_bresp          => s0_bresp,    --          .bresp
			s0_bvalid         => s0_bvalid,   --          .bvalid
			s0_bready         => s0_bready,   --          .bready
			s0_araddr         => s0_araddr,   --          .araddr
			s0_arlen          => s0_arlen,    --          .arlen
			s0_arsize         => s0_arsize,   --          .arsize
			s0_arprot         => s0_arprot,   --          .arprot
			s0_arvalid        => s0_arvalid,  --          .arvalid
			s0_arready        => s0_arready,  --          .arready
			s0_rdata          => s0_rdata,    --          .rdata
			s0_rresp          => s0_rresp,    --          .rresp
			s0_rlast          => s0_rlast,    --          .rlast
			s0_rvalid         => s0_rvalid,   --          .rvalid
			s0_rready         => s0_rready,   --          .rready
			m0_awuser_addrchk => open,        -- (terminated)
			m0_awuser_sai     => open,        -- (terminated)
			m0_wuser_datachk  => open,        -- (terminated)
			m0_wuser_data     => open,        -- (terminated)
			m0_wuser_poison   => open,        -- (terminated)
			m0_aruser_addrchk => open,        -- (terminated)
			m0_aruser_sai     => open,        -- (terminated)
			m0_ruser_datachk  => "0000",      -- (terminated)
			m0_ruser_data     => "0000",      -- (terminated)
			m0_ruser_poison   => "0",         -- (terminated)
			s0_awid           => "0",         -- (terminated)
			s0_awburst        => "00",        -- (terminated)
			s0_awlock         => "0",         -- (terminated)
			s0_awcache        => "0000",      -- (terminated)
			s0_awuser         => "0",         -- (terminated)
			s0_awuser_addrchk => "0000",      -- (terminated)
			s0_awuser_sai     => "0000",      -- (terminated)
			s0_awqos          => "0000",      -- (terminated)
			s0_awregion       => "0000",      -- (terminated)
			s0_wuser          => "0",         -- (terminated)
			s0_wuser_datachk  => "0000",      -- (terminated)
			s0_wuser_data     => "0000",      -- (terminated)
			s0_wuser_poison   => "0",         -- (terminated)
			s0_bid            => open,        -- (terminated)
			s0_buser          => open,        -- (terminated)
			s0_arid           => "0",         -- (terminated)
			s0_arburst        => "00",        -- (terminated)
			s0_arlock         => "0",         -- (terminated)
			s0_arcache        => "0000",      -- (terminated)
			s0_aruser         => "0",         -- (terminated)
			s0_aruser_addrchk => "0000",      -- (terminated)
			s0_aruser_sai     => "0000",      -- (terminated)
			s0_arqos          => "0000",      -- (terminated)
			s0_arregion       => "0000",      -- (terminated)
			s0_rid            => open,        -- (terminated)
			s0_ruser          => open,        -- (terminated)
			s0_ruser_datachk  => open,        -- (terminated)
			s0_ruser_data     => open,        -- (terminated)
			s0_ruser_poison   => open,        -- (terminated)
			s0_wid            => "0",         -- (terminated)
			s0_ardomain       => "00",        -- (terminated)
			s0_arsnoop        => "0000",      -- (terminated)
			s0_arbar          => "00",        -- (terminated)
			s0_awdomain       => "00",        -- (terminated)
			s0_awsnoop        => "000",       -- (terminated)
			s0_awbar          => "00",        -- (terminated)
			s0_awunique       => "0",         -- (terminated)
			m0_wid            => open,        -- (terminated)
			m0_ardomain       => open,        -- (terminated)
			m0_arsnoop        => open,        -- (terminated)
			m0_arbar          => open,        -- (terminated)
			m0_awdomain       => open,        -- (terminated)
			m0_awsnoop        => open,        -- (terminated)
			m0_awbar          => open,        -- (terminated)
			m0_awunique       => open         -- (terminated)
		);

end architecture rtl; -- of pr_test_top_altera_mm_interconnect_1920_ho7sqxa_intel_niosv_g_0_data_manager_translator
