library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity tb_systolic_array is
end entity;

architecture sim of tb_systolic_array is
    -- PASTE THE CONSTANTS GENERATED BY PYTHON HERE
    constant ACTIVE_ROWS : integer := 4; 
    constant ACTIVE_K    : integer := 4;
    constant ACTIVE_COLS : integer := 4;


    signal clk   : std_logic := '0';
    signal start : std_logic := '0';
    signal done  : std_logic;
    signal cycles : integer := 0;

begin
    -- Clock Generation (100MHz)
    clk <= not clk after 5 ns;

    DUT: entity work.top_level_systolic_array
    port map (
        clk           => clk,
        reset         => reset,
        ready         => tb_ready,

        matrix_data   => matrix_data_sig,
        matrix_weight => matrix_weight_sig,

        active_rows   => MAX_ACTIVE_ROWS,
        active_cols   => MAX_ACTIVE_COLS,
        active_k      => ACTIVE_K

        output        => result_matrix_sig,
        cycle_count   => cycle_count_sig,
    );

    -- Cycle Counter Process
    process(clk)
    begin
        if rising_edge(clk) then
            if start = '1' and done = '0' then
                cycles <= cycles + 1;
            end if;
        end if;
    end process;

    -- Test Stimulus
    process
    begin
        wait for 20 ns;
        start <= '1';
        wait until done = '1';
        start <= '0';
        report "Simulation Finished. Total Cycles: " & integer'image(cycles);
        wait;
    end process;
end architecture;