# TCL File Generated by Component Editor 24.1
# Sun Feb 01 15:54:08 NZDT 2026
# DO NOT MODIFY


# 
# npu_system "npu_system" v1.0
#  2026.02.01.15:54:08
# 
# 

# 
# request TCL package from ACDS 24.1
# 
package require -exact qsys 24.1


# 
# module npu_system
# 
set_module_property DESCRIPTION ""
set_module_property NAME npu_system
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME npu_system
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL npu_system_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file npu_system_wrapper.vhd VHDL PATH "../Systolic Array/npu_system_wrapper.vhd" TOP_LEVEL_FILE
add_fileset_file top_level_systolic_array.vhd VHDL PATH "../Systolic Array/top_level_systolic_array.vhd"
add_fileset_file control_unit.vhd VHDL PATH "../Systolic Array/control_unit.vhd"
add_fileset_file systolic_array.vhd VHDL PATH "../Systolic Array/systolic_array.vhd"
add_fileset_file processing_element.vhd VHDL PATH "../Systolic Array/processing_element.vhd"
add_fileset_file custom_types.vhd VHDL PATH "../Systolic Array/custom_types.vhd"

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL npu_system_wrapper
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file npu_system_wrapper.vhd VHDL PATH "../Systolic Array/npu_system_wrapper.vhd"
add_fileset_file top_level_systolic_array.vhd VHDL PATH "../Systolic Array/top_level_systolic_array.vhd"
add_fileset_file control_unit.vhd VHDL PATH "../Systolic Array/control_unit.vhd"
add_fileset_file systolic_array.vhd VHDL PATH "../Systolic Array/systolic_array.vhd"
add_fileset_file custom_types.vhd VHDL PATH "../Systolic Array/custom_types.vhd"
add_fileset_file processing_element.vhd VHDL PATH "../Systolic Array/processing_element.vhd"


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock SV_INTERFACE_TYPE ""
set_interface_property clock SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""
set_interface_property reset IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset SV_INTERFACE_TYPE ""
set_interface_property reset SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressGroup 0
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 bridgedAddressOffset ""
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 minimumResponseLatency 1
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 transparentBridge false
set_interface_property avalon_slave_0 waitrequestAllowance 0
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 dfhFeatureGuid 0
set_interface_property avalon_slave_0 dfhGroupId 0
set_interface_property avalon_slave_0 dfhParameterId ""
set_interface_property avalon_slave_0 dfhParameterName ""
set_interface_property avalon_slave_0 dfhParameterVersion ""
set_interface_property avalon_slave_0 dfhParameterData ""
set_interface_property avalon_slave_0 dfhParameterDataLength ""
set_interface_property avalon_slave_0 dfhFeatureMajorVersion 0
set_interface_property avalon_slave_0 dfhFeatureMinorVersion 0
set_interface_property avalon_slave_0 dfhFeatureId 35
set_interface_property avalon_slave_0 dfhFeatureType 3
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""
set_interface_property avalon_slave_0 IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_slave_0 SV_INTERFACE_TYPE ""
set_interface_property avalon_slave_0 SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_slave_0 avs_address address Input 4
add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
add_interface_port avalon_slave_0 avs_read read Input 1
add_interface_port avalon_slave_0 avs_readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

