# TCL File Generated by Component Editor 18.1
# Fri Sep 26 01:04:52 NZST 2025
# DO NOT MODIFY


# 
# CustomTopLevel "NotVeryTopLevelTopLevel" v1.0
#  2025.09.26.01:04:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module CustomTopLevel
# 
set_module_property DESCRIPTION ""
set_module_property NAME CustomTopLevel
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME NotVeryTopLevelTopLevel
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL top_level_systolic_array
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file top_level_systolic_array.vhd VHDL PATH top_level_systolic_array.vhd
add_fileset_file control_unit.vhd VHDL PATH control_unit.vhd
add_fileset_file custom_types.vhd VHDL PATH custom_types.vhd
add_fileset_file processing_element.vhd VHDL PATH processing_element.vhd
add_fileset_file systolic_array.vhd VHDL PATH systolic_array.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point control
# 
add_interface control avalon end
set_interface_property control addressUnits WORDS
set_interface_property control associatedClock clock
set_interface_property control associatedReset reset
set_interface_property control bitsPerSymbol 8
set_interface_property control burstOnBurstBoundariesOnly false
set_interface_property control burstcountUnits WORDS
set_interface_property control explicitAddressSpan 0
set_interface_property control holdTime 0
set_interface_property control linewrapBursts false
set_interface_property control maximumPendingReadTransactions 0
set_interface_property control maximumPendingWriteTransactions 0
set_interface_property control readLatency 0
set_interface_property control readWaitTime 1
set_interface_property control setupTime 0
set_interface_property control timingUnits Cycles
set_interface_property control writeWaitTime 0
set_interface_property control ENABLED true
set_interface_property control EXPORT_OF ""
set_interface_property control PORT_NAME_MAP ""
set_interface_property control CMSIS_SVD_VARIABLES ""
set_interface_property control SVD_ADDRESS_GROUP ""

add_interface_port control avs_control_address address Input 3
add_interface_port control avs_control_write write Input 1
add_interface_port control avs_control_writedata writedata Input 32
add_interface_port control avs_control_read read Input 1
add_interface_port control avs_control_readdata readdata Output 32
set_interface_assignment control embeddedsw.configuration.isFlash 0
set_interface_assignment control embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment control embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment control embeddedsw.configuration.isPrintableDevice 0


# 
# connection point data
# 
add_interface data avalon start
set_interface_property data addressUnits SYMBOLS
set_interface_property data associatedClock clock
set_interface_property data associatedReset reset
set_interface_property data bitsPerSymbol 8
set_interface_property data burstOnBurstBoundariesOnly false
set_interface_property data burstcountUnits WORDS
set_interface_property data doStreamReads false
set_interface_property data doStreamWrites false
set_interface_property data holdTime 0
set_interface_property data linewrapBursts false
set_interface_property data maximumPendingReadTransactions 0
set_interface_property data maximumPendingWriteTransactions 0
set_interface_property data readLatency 0
set_interface_property data readWaitTime 1
set_interface_property data setupTime 0
set_interface_property data timingUnits Cycles
set_interface_property data writeWaitTime 0
set_interface_property data ENABLED true
set_interface_property data EXPORT_OF ""
set_interface_property data PORT_NAME_MAP ""
set_interface_property data CMSIS_SVD_VARIABLES ""
set_interface_property data SVD_ADDRESS_GROUP ""

add_interface_port data avm_data_address address Output 32
add_interface_port data avm_data_read read Output 1
add_interface_port data avm_data_readdata readdata Input 32
add_interface_port data avm_data_waitrequest waitrequest Input 1


# 
# connection point weight
# 
add_interface weight avalon start
set_interface_property weight addressUnits SYMBOLS
set_interface_property weight associatedClock clock
set_interface_property weight associatedReset reset
set_interface_property weight bitsPerSymbol 8
set_interface_property weight burstOnBurstBoundariesOnly false
set_interface_property weight burstcountUnits WORDS
set_interface_property weight doStreamReads false
set_interface_property weight doStreamWrites false
set_interface_property weight holdTime 0
set_interface_property weight linewrapBursts false
set_interface_property weight maximumPendingReadTransactions 0
set_interface_property weight maximumPendingWriteTransactions 0
set_interface_property weight readLatency 0
set_interface_property weight readWaitTime 1
set_interface_property weight setupTime 0
set_interface_property weight timingUnits Cycles
set_interface_property weight writeWaitTime 0
set_interface_property weight ENABLED true
set_interface_property weight EXPORT_OF ""
set_interface_property weight PORT_NAME_MAP ""
set_interface_property weight CMSIS_SVD_VARIABLES ""
set_interface_property weight SVD_ADDRESS_GROUP ""

add_interface_port weight avm_weight_address address Output 32
add_interface_port weight avm_weight_read read Output 1
add_interface_port weight avm_weight_readdata readdata Input 32
add_interface_port weight avm_weight_waitrequest waitrequest Input 1

